// Copies the OpenCV comparison images generated by the tests into static/,
// so that the docs refer to them without keeping a second copy in git.
import {cpSync, existsSync, mkdirSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const websiteDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const src = resolve(websiteDir, '../Tests/MatftTests/files/images/compare');
const dst = resolve(websiteDir, 'static/img/compare');

if (!existsSync(src)) {
  console.error(`copy-assets: ${src} not found`);
  process.exit(1);
}
mkdirSync(dst, {recursive: true});
cpSync(src, dst, {recursive: true});
console.log(`copy-assets: copied ${src} -> ${dst}`);
