// Generated by python/gen_bughunt_complex.py (numpy 2.0.2). Do not edit by hand.
import XCTest

import Matft

/// The imaginary part of complex arrays in comparisons, Bool conversion, joining, diag and abs. Expected values are numpy outputs
/// Complex operations need Accelerate, so the tests are skipped on WASI
#if !os(WASI)
final class BugHuntComplexTests: XCTestCase {
    private let ZA = MfArray(real: MfArray([1.0, 2.0, -0.0, 3.0, 0.0, 1.0, .nan, .infinity, .infinity, 2.0, 2.0, -1.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([2.0, 0.0, -1.0, 1.0, 0.0, -1.0, 0.0, 0.0, 1.0, 2.0, .nan, 5.0] as [Double], mftype: .Double, shape: [3, 4]))
    private let ZA_pad = MfArray(real: MfArray([99.0, 99.0, 99.0, 99.0, 1.0, 2.0, -0.0, 3.0, 0.0, 1.0, .nan, .infinity, .infinity, 2.0, 2.0, -1.0, 99.0, 99.0, 99.0, 99.0] as [Double], mftype: .Double, shape: [5, 4]), imag: MfArray([-77.0, -77.0, -77.0, -77.0, 2.0, 0.0, -1.0, 1.0, 0.0, -1.0, 0.0, 0.0, 1.0, 2.0, .nan, 5.0, -77.0, -77.0, -77.0, -77.0] as [Double], mftype: .Double, shape: [5, 4]))
    private let ZA_pre = MfArray(real: MfArray([1.0, 2.0, -0.0, 3.0, 0.0, 1.0, .nan, .infinity, .infinity, 2.0, 2.0, -1.0, 99.0, 99.0, 99.0, 99.0] as [Double], mftype: .Double, shape: [4, 4]), imag: MfArray([2.0, 0.0, -1.0, 1.0, 0.0, -1.0, 0.0, 0.0, 1.0, 2.0, .nan, 5.0, -77.0, -77.0, -77.0, -77.0] as [Double], mftype: .Double, shape: [4, 4]))
    private let ZA_str = MfArray(real: MfArray([1.0, 2.0, -0.0, 3.0, 99.0, 99.0, 99.0, 99.0, 0.0, 1.0, .nan, .infinity, 99.0, 99.0, 99.0, 99.0, .infinity, 2.0, 2.0, -1.0, 99.0, 99.0, 99.0, 99.0] as [Double], mftype: .Double, shape: [6, 4]), imag: MfArray([2.0, 0.0, -1.0, 1.0, -77.0, -77.0, -77.0, -77.0, 0.0, -1.0, 0.0, 0.0, -77.0, -77.0, -77.0, -77.0, 1.0, 2.0, .nan, 5.0, -77.0, -77.0, -77.0, -77.0] as [Double], mftype: .Double, shape: [6, 4]))
    private let ZA_rev = MfArray(real: MfArray([.infinity, 2.0, 2.0, -1.0, 0.0, 1.0, .nan, .infinity, 1.0, 2.0, -0.0, 3.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([1.0, 2.0, .nan, 5.0, 0.0, -1.0, 0.0, 0.0, 2.0, 0.0, -1.0, 1.0] as [Double], mftype: .Double, shape: [3, 4]))
    private let ZA_t = MfArray(real: MfArray([1.0, 0.0, .infinity, 2.0, 1.0, 2.0, -0.0, .nan, 2.0, 3.0, .infinity, -1.0] as [Double], mftype: .Double, shape: [4, 3]), imag: MfArray([2.0, 0.0, 1.0, 0.0, -1.0, 2.0, -1.0, 0.0, .nan, 1.0, 0.0, 5.0] as [Double], mftype: .Double, shape: [4, 3]))
    private let ZB = MfArray(real: MfArray([1.0, 2.0, 0.0, 3.0, 0.0, 1.0, .nan, .infinity, .infinity, 1.0, 1.0, -1.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([3.0, 0.0, 0.0, -1.0, 1.0, -1.0, 0.0, 0.0, 0.0, 5.0, 0.0, 5.0] as [Double], mftype: .Double, shape: [3, 4]))
    private let ZAF = MfArray(real: MfArray([1.0, 2.0, -0.0, 3.0, 0.0, 1.0, .nan, .infinity, .infinity, 2.0, 2.0, -1.0] as [Double], mftype: .Float, shape: [3, 4]), imag: MfArray([2.0, 0.0, -1.0, 1.0, 0.0, -1.0, 0.0, 0.0, 1.0, 2.0, .nan, 5.0] as [Double], mftype: .Float, shape: [3, 4]))
    private let ZAF_pad = MfArray(real: MfArray([99.0, 99.0, 99.0, 99.0, 1.0, 2.0, -0.0, 3.0, 0.0, 1.0, .nan, .infinity, .infinity, 2.0, 2.0, -1.0, 99.0, 99.0, 99.0, 99.0] as [Double], mftype: .Float, shape: [5, 4]), imag: MfArray([-77.0, -77.0, -77.0, -77.0, 2.0, 0.0, -1.0, 1.0, 0.0, -1.0, 0.0, 0.0, 1.0, 2.0, .nan, 5.0, -77.0, -77.0, -77.0, -77.0] as [Double], mftype: .Float, shape: [5, 4]))
    private let ZAF_pre = MfArray(real: MfArray([1.0, 2.0, -0.0, 3.0, 0.0, 1.0, .nan, .infinity, .infinity, 2.0, 2.0, -1.0, 99.0, 99.0, 99.0, 99.0] as [Double], mftype: .Float, shape: [4, 4]), imag: MfArray([2.0, 0.0, -1.0, 1.0, 0.0, -1.0, 0.0, 0.0, 1.0, 2.0, .nan, 5.0, -77.0, -77.0, -77.0, -77.0] as [Double], mftype: .Float, shape: [4, 4]))
    private let ZAF_str = MfArray(real: MfArray([1.0, 2.0, -0.0, 3.0, 99.0, 99.0, 99.0, 99.0, 0.0, 1.0, .nan, .infinity, 99.0, 99.0, 99.0, 99.0, .infinity, 2.0, 2.0, -1.0, 99.0, 99.0, 99.0, 99.0] as [Double], mftype: .Float, shape: [6, 4]), imag: MfArray([2.0, 0.0, -1.0, 1.0, -77.0, -77.0, -77.0, -77.0, 0.0, -1.0, 0.0, 0.0, -77.0, -77.0, -77.0, -77.0, 1.0, 2.0, .nan, 5.0, -77.0, -77.0, -77.0, -77.0] as [Double], mftype: .Float, shape: [6, 4]))
    private let ZAF_rev = MfArray(real: MfArray([.infinity, 2.0, 2.0, -1.0, 0.0, 1.0, .nan, .infinity, 1.0, 2.0, -0.0, 3.0] as [Double], mftype: .Float, shape: [3, 4]), imag: MfArray([1.0, 2.0, .nan, 5.0, 0.0, -1.0, 0.0, 0.0, 2.0, 0.0, -1.0, 1.0] as [Double], mftype: .Float, shape: [3, 4]))
    private let ZAF_t = MfArray(real: MfArray([1.0, 0.0, .infinity, 2.0, 1.0, 2.0, -0.0, .nan, 2.0, 3.0, .infinity, -1.0] as [Double], mftype: .Float, shape: [4, 3]), imag: MfArray([2.0, 0.0, 1.0, 0.0, -1.0, 2.0, -1.0, 0.0, .nan, 1.0, 0.0, 5.0] as [Double], mftype: .Float, shape: [4, 3]))
    private let ZBF = MfArray(real: MfArray([1.0, 2.0, 0.0, 3.0, 0.0, 1.0, .nan, .infinity, .infinity, 1.0, 1.0, -1.0] as [Double], mftype: .Float, shape: [3, 4]), imag: MfArray([3.0, 0.0, 0.0, -1.0, 1.0, -1.0, 0.0, 0.0, 0.0, 5.0, 0.0, 5.0] as [Double], mftype: .Float, shape: [3, 4]))
    private let R = MfArray([1.0, 2.0, 0.0, 3.0, 0.0, 0.0, .nan, .infinity, .infinity, 2.0, 2.0, -1.0] as [Double], mftype: .Double, shape: [3, 4])
    private let ROW = MfArray(real: MfArray([1.0, 2.0, 0.0, 3.0] as [Double], mftype: .Double, shape: [4]), imag: MfArray([1.0, 0.0, 0.0, 1.0] as [Double], mftype: .Double, shape: [4]))
    private let Z23 = MfArray(real: MfArray([1.0, -3.0, -0.0, 2.0, 0.0, 4.0] as [Double], mftype: .Double, shape: [2, 3]), imag: MfArray([2.0, 0.0, -1.0, -2.0, 0.0, 5.0] as [Double], mftype: .Double, shape: [2, 3]))
    private let Z23_pad = MfArray(real: MfArray([99.0, 99.0, 99.0, 1.0, -3.0, -0.0, 2.0, 0.0, 4.0, 99.0, 99.0, 99.0] as [Double], mftype: .Double, shape: [4, 3]), imag: MfArray([-77.0, -77.0, -77.0, 2.0, 0.0, -1.0, -2.0, 0.0, 5.0, -77.0, -77.0, -77.0] as [Double], mftype: .Double, shape: [4, 3]))
    private let Z23_pre = MfArray(real: MfArray([1.0, -3.0, -0.0, 2.0, 0.0, 4.0, 99.0, 99.0, 99.0] as [Double], mftype: .Double, shape: [3, 3]), imag: MfArray([2.0, 0.0, -1.0, -2.0, 0.0, 5.0, -77.0, -77.0, -77.0] as [Double], mftype: .Double, shape: [3, 3]))
    private let Z23_str = MfArray(real: MfArray([1.0, -3.0, -0.0, 99.0, 99.0, 99.0, 2.0, 0.0, 4.0, 99.0, 99.0, 99.0] as [Double], mftype: .Double, shape: [4, 3]), imag: MfArray([2.0, 0.0, -1.0, -77.0, -77.0, -77.0, -2.0, 0.0, 5.0, -77.0, -77.0, -77.0] as [Double], mftype: .Double, shape: [4, 3]))
    private let Z23_rev = MfArray(real: MfArray([2.0, 0.0, 4.0, 1.0, -3.0, -0.0] as [Double], mftype: .Double, shape: [2, 3]), imag: MfArray([-2.0, 0.0, 5.0, 2.0, 0.0, -1.0] as [Double], mftype: .Double, shape: [2, 3]))
    private let Z23_t = MfArray(real: MfArray([1.0, 2.0, -3.0, 0.0, -0.0, 4.0] as [Double], mftype: .Double, shape: [3, 2]), imag: MfArray([2.0, -2.0, 0.0, 0.0, -1.0, 5.0] as [Double], mftype: .Double, shape: [3, 2]))
    private let R23 = MfArray([7.0, 8.0, 9.0, 10.0, 11.0, 12.0] as [Double], mftype: .Double, shape: [2, 3])
    private let R23F = MfArray([7.0, 8.0, 9.0, 10.0, 11.0, 12.0] as [Double], mftype: .Float, shape: [2, 3])
    private let Z23F = MfArray(real: MfArray([1.0, -3.0, -0.0, 2.0, 0.0, 4.0] as [Double], mftype: .Float, shape: [2, 3]), imag: MfArray([2.0, 0.0, -1.0, -2.0, 0.0, 5.0] as [Double], mftype: .Float, shape: [2, 3]))
    private let Z1 = MfArray(real: MfArray([1.0, 2.0, 0.0] as [Double], mftype: .Double, shape: [3]), imag: MfArray([1.0, -1.0, 3.0] as [Double], mftype: .Double, shape: [3]))
    private let R1 = MfArray([4.0, 5.0, 6.0] as [Double], mftype: .Double, shape: [3])
    private let Z3D = MfArray(real: MfArray([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0] as [Double], mftype: .Double, shape: [2, 3, 2]), imag: MfArray([-5.0, -4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0] as [Double], mftype: .Double, shape: [2, 3, 2]))
    private let R3D = MfArray([0.0, 10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0] as [Double], mftype: .Double, shape: [2, 2, 2])
    private let ABS = MfArray(real: MfArray([1e+200, 1e-200, 3e+307, .infinity, .nan, 3.0, 0.0, .nan, -.infinity, -5e-320, 1e+300, 1e-170] as [Double], mftype: .Double, shape: [12]), imag: MfArray([1e+200, 1e-200, 3e+307, .nan, .infinity, 4.0, 0.0, 1.0, 0.0, 0.0, 1e-300, 1e-160] as [Double], mftype: .Double, shape: [12]))
    private let ABSF = MfArray(real: MfArray([1.0000000200408773e+20, 1.0000000195414814e-25, 3.0000000054977558e+38, .infinity, 3.0, 0.0, .nan, 9.99994610111476e-41, 3.000000104103097e+19] as [Double], mftype: .Float, shape: [9]), imag: MfArray([1.0000000200408773e+20, 1.0000000195414814e-25, 3.0000000054977558e+38, .nan, 4.0, 0.0, 1.0, 0.0, -3.999999992202579e+19] as [Double], mftype: .Float, shape: [9]))
    private let ABS2 = MfArray(real: MfArray([1e+200, 3.0, 1e-200, .infinity] as [Double], mftype: .Double, shape: [2, 2]), imag: MfArray([1e+200, 4.0, 1e-200, .nan] as [Double], mftype: .Double, shape: [2, 2]))
    private let ABS2_pad = MfArray(real: MfArray([99.0, 99.0, 1e+200, 3.0, 1e-200, .infinity, 99.0, 99.0] as [Double], mftype: .Double, shape: [4, 2]), imag: MfArray([-77.0, -77.0, 1e+200, 4.0, 1e-200, .nan, -77.0, -77.0] as [Double], mftype: .Double, shape: [4, 2]))
    private let ABS2_pre = MfArray(real: MfArray([1e+200, 3.0, 1e-200, .infinity, 99.0, 99.0] as [Double], mftype: .Double, shape: [3, 2]), imag: MfArray([1e+200, 4.0, 1e-200, .nan, -77.0, -77.0] as [Double], mftype: .Double, shape: [3, 2]))
    private let ABS2_str = MfArray(real: MfArray([1e+200, 3.0, 99.0, 99.0, 1e-200, .infinity, 99.0, 99.0] as [Double], mftype: .Double, shape: [4, 2]), imag: MfArray([1e+200, 4.0, -77.0, -77.0, 1e-200, .nan, -77.0, -77.0] as [Double], mftype: .Double, shape: [4, 2]))
    private let ABS2_rev = MfArray(real: MfArray([1e-200, .infinity, 1e+200, 3.0] as [Double], mftype: .Double, shape: [2, 2]), imag: MfArray([1e-200, .nan, 1e+200, 4.0] as [Double], mftype: .Double, shape: [2, 2]))
    private let ABS2_t = MfArray(real: MfArray([1e+200, 1e-200, 3.0, .infinity] as [Double], mftype: .Double, shape: [2, 2]), imag: MfArray([1e+200, 1e-200, 4.0, .nan] as [Double], mftype: .Double, shape: [2, 2]))
    private let LOGZ = MfArray(real: MfArray([1e+200, 1e-200] as [Double], mftype: .Double, shape: [2]), imag: MfArray([1e+200, 1e-200] as [Double], mftype: .Double, shape: [2]))

    func test_compare_complex_arrays() {
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x === ZB, MfArray([false, true, false, false, false, true, false, true, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x === ZB \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(ZB === x, MfArray([false, true, false, false, false, true, false, true, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "ZB === x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x === ZBF, MfArray([false, true, false, false, false, true, false, true, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x === ZBF \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x !== ZB, MfArray([true, false, true, true, true, false, true, false, true, true, true, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x !== ZB \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(ZB !== x, MfArray([true, false, true, true, true, false, true, false, true, true, true, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "ZB !== x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x !== ZBF, MfArray([true, false, true, true, true, false, true, false, true, true, true, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x !== ZBF \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x < ZB, MfArray([true, false, true, false, true, false, false, false, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x < ZB \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(ZB < x, MfArray([false, false, false, true, false, false, false, false, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "ZB < x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x < ZBF, MfArray([true, false, true, false, true, false, false, false, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x < ZBF \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x <= ZB, MfArray([true, true, true, false, true, true, false, true, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x <= ZB \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(ZB <= x, MfArray([false, true, false, true, false, true, false, true, true, true, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "ZB <= x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x <= ZBF, MfArray([true, true, true, false, true, true, false, true, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x <= ZBF \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x > ZB, MfArray([false, false, false, true, false, false, false, false, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x > ZB \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(ZB > x, MfArray([true, false, true, false, true, false, false, false, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "ZB > x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x > ZBF, MfArray([false, false, false, true, false, false, false, false, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x > ZBF \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x >= ZB, MfArray([false, true, false, true, false, true, false, true, true, true, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x >= ZB \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(ZB >= x, MfArray([true, true, true, false, true, true, false, true, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "ZB >= x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x >= ZBF, MfArray([false, true, false, true, false, true, false, true, true, true, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x >= ZBF \(name)")
        }
    }

    func test_compare_complex_real_and_broadcast() {
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x === R, MfArray([false, true, false, false, true, false, false, true, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x === R \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(R === x, MfArray([false, true, false, false, true, false, false, true, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "R === x \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x !== R, MfArray([true, false, true, true, false, true, true, false, true, true, true, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x !== R \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(R !== x, MfArray([true, false, true, true, false, true, true, false, true, true, true, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "R !== x \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x < R, MfArray([false, false, true, false, false, false, false, false, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x < R \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(R < x, MfArray([true, false, false, true, false, true, false, false, true, true, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "R < x \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x <= R, MfArray([false, true, true, false, true, false, false, true, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x <= R \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(R <= x, MfArray([true, true, false, true, true, true, false, true, true, true, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "R <= x \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x > R, MfArray([true, false, false, true, false, true, false, false, true, true, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x > R \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(R > x, MfArray([false, false, true, false, false, false, false, false, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "R > x \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x >= R, MfArray([true, true, false, true, true, true, false, true, true, true, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x >= R \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(R >= x, MfArray([false, true, true, false, true, false, false, true, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "R >= x \(name)")
        }
        XCTAssertClose(ZA === ROW, MfArray([false, true, false, true, false, false, false, false, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "ZA === ROW")
        XCTAssertClose(ZA !== ROW, MfArray([true, false, true, false, true, true, true, true, true, true, true, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "ZA !== ROW")
        XCTAssertClose(ZA < ROW, MfArray([false, false, true, false, true, true, false, false, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "ZA < ROW")
        XCTAssertClose(ZA <= ROW, MfArray([false, true, true, true, true, true, false, false, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "ZA <= ROW")
        XCTAssertClose(ZA > ROW, MfArray([true, false, false, false, false, false, false, true, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "ZA > ROW")
        XCTAssertClose(ZA >= ROW, MfArray([true, true, false, true, false, false, false, true, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "ZA >= ROW")
    }

    func test_compare_complex_scalar() {
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x === 0, MfArray([false, false, false, false, true, false, false, false, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x === 0 \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(0 === x, MfArray([false, false, false, false, true, false, false, false, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "0 === x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x === Float(0), MfArray([false, false, false, false, true, false, false, false, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x === Float(0) \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x === 1, MfArray([false, false, false, false, false, false, false, false, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x === 1 \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(1 === x, MfArray([false, false, false, false, false, false, false, false, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "1 === x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x === Float(1), MfArray([false, false, false, false, false, false, false, false, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x === Float(1) \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x === 2, MfArray([false, true, false, false, false, false, false, false, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x === 2 \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(2 === x, MfArray([false, true, false, false, false, false, false, false, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "2 === x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x === Float(2), MfArray([false, true, false, false, false, false, false, false, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x === Float(2) \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x !== 0, MfArray([true, true, true, true, false, true, true, true, true, true, true, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x !== 0 \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(0 !== x, MfArray([true, true, true, true, false, true, true, true, true, true, true, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "0 !== x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x !== Float(0), MfArray([true, true, true, true, false, true, true, true, true, true, true, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x !== Float(0) \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x !== 1, MfArray([true, true, true, true, true, true, true, true, true, true, true, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x !== 1 \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(1 !== x, MfArray([true, true, true, true, true, true, true, true, true, true, true, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "1 !== x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x !== Float(1), MfArray([true, true, true, true, true, true, true, true, true, true, true, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x !== Float(1) \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x !== 2, MfArray([true, false, true, true, true, true, true, true, true, true, true, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x !== 2 \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(2 !== x, MfArray([true, false, true, true, true, true, true, true, true, true, true, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "2 !== x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x !== Float(2), MfArray([true, false, true, true, true, true, true, true, true, true, true, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x !== Float(2) \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x < 0, MfArray([false, false, true, false, false, false, false, false, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x < 0 \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(0 < x, MfArray([true, true, false, true, false, true, false, true, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "0 < x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x < Float(0), MfArray([false, false, true, false, false, false, false, false, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x < Float(0) \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x < 1, MfArray([false, false, true, false, true, true, false, false, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x < 1 \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(1 < x, MfArray([true, true, false, true, false, false, false, true, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "1 < x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x < Float(1), MfArray([false, false, true, false, true, true, false, false, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x < Float(1) \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x < 2, MfArray([true, false, true, false, true, true, false, false, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x < 2 \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(2 < x, MfArray([false, false, false, true, false, false, false, true, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "2 < x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x < Float(2), MfArray([true, false, true, false, true, true, false, false, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x < Float(2) \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x <= 0, MfArray([false, false, true, false, true, false, false, false, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x <= 0 \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(0 <= x, MfArray([true, true, false, true, true, true, false, true, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "0 <= x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x <= Float(0), MfArray([false, false, true, false, true, false, false, false, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x <= Float(0) \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x <= 1, MfArray([false, false, true, false, true, true, false, false, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x <= 1 \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(1 <= x, MfArray([true, true, false, true, false, false, false, true, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "1 <= x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x <= Float(1), MfArray([false, false, true, false, true, true, false, false, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x <= Float(1) \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x <= 2, MfArray([true, true, true, false, true, true, false, false, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x <= 2 \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(2 <= x, MfArray([false, true, false, true, false, false, false, true, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "2 <= x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x <= Float(2), MfArray([true, true, true, false, true, true, false, false, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x <= Float(2) \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x > 0, MfArray([true, true, false, true, false, true, false, true, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x > 0 \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(0 > x, MfArray([false, false, true, false, false, false, false, false, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "0 > x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x > Float(0), MfArray([true, true, false, true, false, true, false, true, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x > Float(0) \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x > 1, MfArray([true, true, false, true, false, false, false, true, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x > 1 \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(1 > x, MfArray([false, false, true, false, true, true, false, false, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "1 > x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x > Float(1), MfArray([true, true, false, true, false, false, false, true, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x > Float(1) \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x > 2, MfArray([false, false, false, true, false, false, false, true, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x > 2 \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(2 > x, MfArray([true, false, true, false, true, true, false, false, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "2 > x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x > Float(2), MfArray([false, false, false, true, false, false, false, true, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x > Float(2) \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x >= 0, MfArray([true, true, false, true, true, true, false, true, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x >= 0 \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(0 >= x, MfArray([false, false, true, false, true, false, false, false, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "0 >= x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x >= Float(0), MfArray([true, true, false, true, true, true, false, true, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x >= Float(0) \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x >= 1, MfArray([true, true, false, true, false, false, false, true, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x >= 1 \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(1 >= x, MfArray([false, false, true, false, true, true, false, false, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "1 >= x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x >= Float(1), MfArray([true, true, false, true, false, false, false, true, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x >= Float(1) \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x >= 2, MfArray([false, true, false, true, false, false, false, true, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x >= 2 \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(2 >= x, MfArray([true, true, true, false, true, true, false, false, false, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "2 >= x \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x >= Float(2), MfArray([false, true, false, true, false, false, false, true, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x >= Float(2) \(name)")
        }
    }

    func test_complex_to_bool() {
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(Matft.logical_not(x), MfArray([false, false, false, false, true, false, false, false, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.logical_not(x) \(name)")
        }
        for (name, x) in [("contiguous", ZA), ("column", ZA.to_contiguous(mforder: .Column)), ("offset view", ZA_pad[1~<4]), ("prefix view", ZA_pre[0~<3]), ("strided view", ZA_str[0~<6~<2]), ("reversed view", ZA_rev[Matft.reverse]), ("transposed view", ZA_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x.astype(.Bool), MfArray([true, true, true, true, false, true, true, true, true, true, true, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x.astype(.Bool) \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(Matft.logical_not(x), MfArray([false, false, false, false, true, false, false, false, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.logical_not(x) \(name)")
        }
        for (name, x) in [("contiguous", ZAF), ("column", ZAF.to_contiguous(mforder: .Column)), ("offset view", ZAF_pad[1~<4]), ("prefix view", ZAF_pre[0~<3]), ("strided view", ZAF_str[0~<6~<2]), ("reversed view", ZAF_rev[Matft.reverse]), ("transposed view", ZAF_t.T)] as [(String, MfArray)]{
            XCTAssertClose(x.astype(.Bool), MfArray([true, true, true, true, false, true, true, true, true, true, true, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x.astype(.Bool) \(name)")
        }
    }

    func test_join_complex() {
        for (name, x) in [("contiguous", Z23), ("column", Z23.to_contiguous(mforder: .Column)), ("offset view", Z23_pad[1~<3]), ("prefix view", Z23_pre[0~<2]), ("strided view", Z23_str[0~<4~<2]), ("reversed view", Z23_rev[Matft.reverse]), ("transposed view", Z23_t.T)] as [(String, MfArray)]{
            do {
                let ret = Matft.vstack([x, R23])
                XCTAssertTrue(ret.isComplex, "not complex: Matft.vstack([x, R23]) \(name)")
                XCTAssertClose(ret.real, MfArray([1.0, -3.0, -0.0, 2.0, 0.0, 4.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0] as [Double], mftype: .Double, shape: [4, 3]), rtol: 1e-12, atol: 0, checkType: true, "real: Matft.vstack([x, R23]) \(name)")
                XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([2.0, 0.0, -1.0, -2.0, 0.0, 5.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] as [Double], mftype: .Double, shape: [4, 3]), rtol: 1e-12, atol: 0, checkType: true, "imag: Matft.vstack([x, R23]) \(name)")
            }
        }
        for (name, x) in [("contiguous", Z23), ("column", Z23.to_contiguous(mforder: .Column)), ("offset view", Z23_pad[1~<3]), ("prefix view", Z23_pre[0~<2]), ("strided view", Z23_str[0~<4~<2]), ("reversed view", Z23_rev[Matft.reverse]), ("transposed view", Z23_t.T)] as [(String, MfArray)]{
            do {
                let ret = Matft.vstack([R23, x])
                XCTAssertTrue(ret.isComplex, "not complex: Matft.vstack([R23, x]) \(name)")
                XCTAssertClose(ret.real, MfArray([7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 1.0, -3.0, -0.0, 2.0, 0.0, 4.0] as [Double], mftype: .Double, shape: [4, 3]), rtol: 1e-12, atol: 0, checkType: true, "real: Matft.vstack([R23, x]) \(name)")
                XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, -1.0, -2.0, 0.0, 5.0] as [Double], mftype: .Double, shape: [4, 3]), rtol: 1e-12, atol: 0, checkType: true, "imag: Matft.vstack([R23, x]) \(name)")
            }
        }
        for (name, x) in [("contiguous", Z23), ("column", Z23.to_contiguous(mforder: .Column)), ("offset view", Z23_pad[1~<3]), ("prefix view", Z23_pre[0~<2]), ("strided view", Z23_str[0~<4~<2]), ("reversed view", Z23_rev[Matft.reverse]), ("transposed view", Z23_t.T)] as [(String, MfArray)]{
            do {
                let ret = Matft.vstack([x, x])
                XCTAssertTrue(ret.isComplex, "not complex: Matft.vstack([x, x]) \(name)")
                XCTAssertClose(ret.real, MfArray([1.0, -3.0, -0.0, 2.0, 0.0, 4.0, 1.0, -3.0, -0.0, 2.0, 0.0, 4.0] as [Double], mftype: .Double, shape: [4, 3]), rtol: 1e-12, atol: 0, checkType: true, "real: Matft.vstack([x, x]) \(name)")
                XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([2.0, 0.0, -1.0, -2.0, 0.0, 5.0, 2.0, 0.0, -1.0, -2.0, 0.0, 5.0] as [Double], mftype: .Double, shape: [4, 3]), rtol: 1e-12, atol: 0, checkType: true, "imag: Matft.vstack([x, x]) \(name)")
            }
        }
        do {
            let ret = Matft.vstack([Z1, R1])
            XCTAssertTrue(ret.isComplex, "not complex: Matft.vstack([Z1, R1])")
            XCTAssertClose(ret.real, MfArray([1.0, 2.0, 0.0, 4.0, 5.0, 6.0] as [Double], mftype: .Double, shape: [2, 3]), rtol: 1e-12, atol: 0, checkType: true, "real: Matft.vstack([Z1, R1])")
            XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([1.0, -1.0, 3.0, 0.0, 0.0, 0.0] as [Double], mftype: .Double, shape: [2, 3]), rtol: 1e-12, atol: 0, checkType: true, "imag: Matft.vstack([Z1, R1])")
        }
        for (name, x) in [("contiguous", Z23), ("column", Z23.to_contiguous(mforder: .Column)), ("offset view", Z23_pad[1~<3]), ("prefix view", Z23_pre[0~<2]), ("strided view", Z23_str[0~<4~<2]), ("reversed view", Z23_rev[Matft.reverse]), ("transposed view", Z23_t.T)] as [(String, MfArray)]{
            do {
                let ret = Matft.hstack([x, R23])
                XCTAssertTrue(ret.isComplex, "not complex: Matft.hstack([x, R23]) \(name)")
                XCTAssertClose(ret.real, MfArray([1.0, -3.0, -0.0, 7.0, 8.0, 9.0, 2.0, 0.0, 4.0, 10.0, 11.0, 12.0] as [Double], mftype: .Double, shape: [2, 6]), rtol: 1e-12, atol: 0, checkType: true, "real: Matft.hstack([x, R23]) \(name)")
                XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([2.0, 0.0, -1.0, 0.0, 0.0, 0.0, -2.0, 0.0, 5.0, 0.0, 0.0, 0.0] as [Double], mftype: .Double, shape: [2, 6]), rtol: 1e-12, atol: 0, checkType: true, "imag: Matft.hstack([x, R23]) \(name)")
            }
        }
        for (name, x) in [("contiguous", Z23), ("column", Z23.to_contiguous(mforder: .Column)), ("offset view", Z23_pad[1~<3]), ("prefix view", Z23_pre[0~<2]), ("strided view", Z23_str[0~<4~<2]), ("reversed view", Z23_rev[Matft.reverse]), ("transposed view", Z23_t.T)] as [(String, MfArray)]{
            do {
                let ret = Matft.hstack([R23, x])
                XCTAssertTrue(ret.isComplex, "not complex: Matft.hstack([R23, x]) \(name)")
                XCTAssertClose(ret.real, MfArray([7.0, 8.0, 9.0, 1.0, -3.0, -0.0, 10.0, 11.0, 12.0, 2.0, 0.0, 4.0] as [Double], mftype: .Double, shape: [2, 6]), rtol: 1e-12, atol: 0, checkType: true, "real: Matft.hstack([R23, x]) \(name)")
                XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([0.0, 0.0, 0.0, 2.0, 0.0, -1.0, 0.0, 0.0, 0.0, -2.0, 0.0, 5.0] as [Double], mftype: .Double, shape: [2, 6]), rtol: 1e-12, atol: 0, checkType: true, "imag: Matft.hstack([R23, x]) \(name)")
            }
        }
        do {
            let ret = Matft.hstack([Z1, R1])
            XCTAssertTrue(ret.isComplex, "not complex: Matft.hstack([Z1, R1])")
            XCTAssertClose(ret.real, MfArray([1.0, 2.0, 0.0, 4.0, 5.0, 6.0] as [Double], mftype: .Double, shape: [6]), rtol: 1e-12, atol: 0, checkType: true, "real: Matft.hstack([Z1, R1])")
            XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([1.0, -1.0, 3.0, 0.0, 0.0, 0.0] as [Double], mftype: .Double, shape: [6]), rtol: 1e-12, atol: 0, checkType: true, "imag: Matft.hstack([Z1, R1])")
        }
        for (name, x) in [("contiguous", Z23), ("column", Z23.to_contiguous(mforder: .Column)), ("offset view", Z23_pad[1~<3]), ("prefix view", Z23_pre[0~<2]), ("strided view", Z23_str[0~<4~<2]), ("reversed view", Z23_rev[Matft.reverse]), ("transposed view", Z23_t.T)] as [(String, MfArray)]{
            do {
                let ret = Matft.concatenate([x, R23], axis: 0)
                XCTAssertTrue(ret.isComplex, "not complex: Matft.concatenate([x, R23], axis: 0) \(name)")
                XCTAssertClose(ret.real, MfArray([1.0, -3.0, -0.0, 2.0, 0.0, 4.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0] as [Double], mftype: .Double, shape: [4, 3]), rtol: 1e-12, atol: 0, checkType: true, "real: Matft.concatenate([x, R23], axis: 0) \(name)")
                XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([2.0, 0.0, -1.0, -2.0, 0.0, 5.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] as [Double], mftype: .Double, shape: [4, 3]), rtol: 1e-12, atol: 0, checkType: true, "imag: Matft.concatenate([x, R23], axis: 0) \(name)")
            }
        }
        for (name, x) in [("contiguous", Z23), ("column", Z23.to_contiguous(mforder: .Column)), ("offset view", Z23_pad[1~<3]), ("prefix view", Z23_pre[0~<2]), ("strided view", Z23_str[0~<4~<2]), ("reversed view", Z23_rev[Matft.reverse]), ("transposed view", Z23_t.T)] as [(String, MfArray)]{
            do {
                let ret = Matft.concatenate([x, R23], axis: 1)
                XCTAssertTrue(ret.isComplex, "not complex: Matft.concatenate([x, R23], axis: 1) \(name)")
                XCTAssertClose(ret.real, MfArray([1.0, -3.0, -0.0, 7.0, 8.0, 9.0, 2.0, 0.0, 4.0, 10.0, 11.0, 12.0] as [Double], mftype: .Double, shape: [2, 6]), rtol: 1e-12, atol: 0, checkType: true, "real: Matft.concatenate([x, R23], axis: 1) \(name)")
                XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([2.0, 0.0, -1.0, 0.0, 0.0, 0.0, -2.0, 0.0, 5.0, 0.0, 0.0, 0.0] as [Double], mftype: .Double, shape: [2, 6]), rtol: 1e-12, atol: 0, checkType: true, "imag: Matft.concatenate([x, R23], axis: 1) \(name)")
            }
        }
        for (name, x) in [("contiguous", Z23), ("column", Z23.to_contiguous(mforder: .Column)), ("offset view", Z23_pad[1~<3]), ("prefix view", Z23_pre[0~<2]), ("strided view", Z23_str[0~<4~<2]), ("reversed view", Z23_rev[Matft.reverse]), ("transposed view", Z23_t.T)] as [(String, MfArray)]{
            do {
                let ret = Matft.concatenate([R23, x], axis: -1)
                XCTAssertTrue(ret.isComplex, "not complex: Matft.concatenate([R23, x], axis: -1) \(name)")
                XCTAssertClose(ret.real, MfArray([7.0, 8.0, 9.0, 1.0, -3.0, -0.0, 10.0, 11.0, 12.0, 2.0, 0.0, 4.0] as [Double], mftype: .Double, shape: [2, 6]), rtol: 1e-12, atol: 0, checkType: true, "real: Matft.concatenate([R23, x], axis: -1) \(name)")
                XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([0.0, 0.0, 0.0, 2.0, 0.0, -1.0, 0.0, 0.0, 0.0, -2.0, 0.0, 5.0] as [Double], mftype: .Double, shape: [2, 6]), rtol: 1e-12, atol: 0, checkType: true, "imag: Matft.concatenate([R23, x], axis: -1) \(name)")
            }
        }
        do {
            let ret = Matft.concatenate([Z3D, R3D], axis: 1)
            XCTAssertTrue(ret.isComplex, "not complex: Matft.concatenate([Z3D, R3D], axis: 1)")
            XCTAssertClose(ret.real, MfArray([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 0.0, 10.0, 20.0, 30.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 40.0, 50.0, 60.0, 70.0] as [Double], mftype: .Double, shape: [2, 5, 2]), rtol: 1e-12, atol: 0, checkType: true, "real: Matft.concatenate([Z3D, R3D], axis: 1)")
            XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([-5.0, -4.0, -3.0, -2.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 0.0, 0.0, 0.0, 0.0] as [Double], mftype: .Double, shape: [2, 5, 2]), rtol: 1e-12, atol: 0, checkType: true, "imag: Matft.concatenate([Z3D, R3D], axis: 1)")
        }
        do {
            let ret = Matft.concatenate([R3D, Z3D, R3D], axis: 1)
            XCTAssertTrue(ret.isComplex, "not complex: Matft.concatenate([R3D, Z3D, R3D], axis: 1)")
            XCTAssertClose(ret.real, MfArray([0.0, 10.0, 20.0, 30.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 0.0, 10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 40.0, 50.0, 60.0, 70.0] as [Double], mftype: .Double, shape: [2, 7, 2]), rtol: 1e-12, atol: 0, checkType: true, "real: Matft.concatenate([R3D, Z3D, R3D], axis: 1)")
            XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([0.0, 0.0, 0.0, 0.0, -5.0, -4.0, -3.0, -2.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 0.0, 0.0, 0.0, 0.0] as [Double], mftype: .Double, shape: [2, 7, 2]), rtol: 1e-12, atol: 0, checkType: true, "imag: Matft.concatenate([R3D, Z3D, R3D], axis: 1)")
        }
        do {
            let ret = Matft.vstack([Z23F, R23F])
            XCTAssertTrue(ret.isComplex, "not complex: Matft.vstack([Z23F, R23F])")
            XCTAssertClose(ret.real, MfArray([1.0, -3.0, -0.0, 2.0, 0.0, 4.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0] as [Double], mftype: .Float, shape: [4, 3]), rtol: 1e-06, atol: 0, checkType: true, "real: Matft.vstack([Z23F, R23F])")
            XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([2.0, 0.0, -1.0, -2.0, 0.0, 5.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] as [Double], mftype: .Float, shape: [4, 3]), rtol: 1e-06, atol: 0, checkType: true, "imag: Matft.vstack([Z23F, R23F])")
        }
        do {
            let ret = Matft.vstack([Z23F, R23])
            XCTAssertTrue(ret.isComplex, "not complex: Matft.vstack([Z23F, R23])")
            XCTAssertClose(ret.real, MfArray([1.0, -3.0, -0.0, 2.0, 0.0, 4.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0] as [Double], mftype: .Double, shape: [4, 3]), rtol: 1e-12, atol: 0, checkType: true, "real: Matft.vstack([Z23F, R23])")
            XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([2.0, 0.0, -1.0, -2.0, 0.0, 5.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] as [Double], mftype: .Double, shape: [4, 3]), rtol: 1e-12, atol: 0, checkType: true, "imag: Matft.vstack([Z23F, R23])")
        }
        do {
            let ret = Matft.append(Z1, values: R1)
            XCTAssertTrue(ret.isComplex, "not complex: Matft.append(Z1, values: R1)")
            XCTAssertClose(ret.real, MfArray([1.0, 2.0, 0.0, 4.0, 5.0, 6.0] as [Double], mftype: .Double, shape: [6]), rtol: 1e-12, atol: 0, checkType: true, "real: Matft.append(Z1, values: R1)")
            XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([1.0, -1.0, 3.0, 0.0, 0.0, 0.0] as [Double], mftype: .Double, shape: [6]), rtol: 1e-12, atol: 0, checkType: true, "imag: Matft.append(Z1, values: R1)")
        }
    }

    func test_diag_complex() {
        do {
            let ret = Matft.diag(v: Z1)
            XCTAssertTrue(ret.isComplex, "not complex: Matft.diag(v: Z1)")
            XCTAssertClose(ret.real, MfArray([1.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0] as [Double], mftype: .Double, shape: [3, 3]), rtol: 1e-12, atol: 0, checkType: true, "real: Matft.diag(v: Z1)")
            XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([1.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 3.0] as [Double], mftype: .Double, shape: [3, 3]), rtol: 1e-12, atol: 0, checkType: true, "imag: Matft.diag(v: Z1)")
        }
        do {
            let ret = Matft.diag(v: Z1, k: 1)
            XCTAssertTrue(ret.isComplex, "not complex: Matft.diag(v: Z1, k: 1)")
            XCTAssertClose(ret.real, MfArray([0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] as [Double], mftype: .Double, shape: [4, 4]), rtol: 1e-12, atol: 0, checkType: true, "real: Matft.diag(v: Z1, k: 1)")
            XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([0.0, 1.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 3.0, 0.0, 0.0, 0.0, 0.0] as [Double], mftype: .Double, shape: [4, 4]), rtol: 1e-12, atol: 0, checkType: true, "imag: Matft.diag(v: Z1, k: 1)")
        }
        do {
            let ret = Matft.diag(v: Z1, k: -2)
            XCTAssertTrue(ret.isComplex, "not complex: Matft.diag(v: Z1, k: -2)")
            XCTAssertClose(ret.real, MfArray([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] as [Double], mftype: .Double, shape: [5, 5]), rtol: 1e-12, atol: 0, checkType: true, "real: Matft.diag(v: Z1, k: -2)")
            XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 0.0, 0.0] as [Double], mftype: .Double, shape: [5, 5]), rtol: 1e-12, atol: 0, checkType: true, "imag: Matft.diag(v: Z1, k: -2)")
        }
        do {
            let ret = Matft.diag(v: Z1, mforder: .Column)
            XCTAssertTrue(ret.isComplex, "not complex: Matft.diag(v: Z1, mforder: .Column)")
            XCTAssertClose(ret.real, MfArray([1.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0] as [Double], mftype: .Double, shape: [3, 3]), rtol: 1e-12, atol: 0, checkType: true, "real: Matft.diag(v: Z1, mforder: .Column)")
            XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([1.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 3.0] as [Double], mftype: .Double, shape: [3, 3]), rtol: 1e-12, atol: 0, checkType: true, "imag: Matft.diag(v: Z1, mforder: .Column)")
        }
        do {
            let ret = Matft.diag(v: Z23[1])
            XCTAssertTrue(ret.isComplex, "not complex: Matft.diag(v: Z23[1])")
            XCTAssertClose(ret.real, MfArray([2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0] as [Double], mftype: .Double, shape: [3, 3]), rtol: 1e-12, atol: 0, checkType: true, "real: Matft.diag(v: Z23[1])")
            XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([-2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.0] as [Double], mftype: .Double, shape: [3, 3]), rtol: 1e-12, atol: 0, checkType: true, "imag: Matft.diag(v: Z23[1])")
        }
        do {
            let ret = Matft.diag(v: Z23F[0])
            XCTAssertTrue(ret.isComplex, "not complex: Matft.diag(v: Z23F[0])")
            XCTAssertClose(ret.real, MfArray([1.0, 0.0, 0.0, 0.0, -3.0, 0.0, 0.0, 0.0, -0.0] as [Double], mftype: .Float, shape: [3, 3]), rtol: 1e-06, atol: 0, checkType: true, "real: Matft.diag(v: Z23F[0])")
            XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0] as [Double], mftype: .Float, shape: [3, 3]), rtol: 1e-06, atol: 0, checkType: true, "imag: Matft.diag(v: Z23F[0])")
        }
    }

    func test_abs_complex_hypot() {
        XCTAssertClose(Matft.complex.abs(ABS), MfArray([1.414213562373095e+200, 1.414213562373095e-200, 4.242640687119285e+307, .infinity, .infinity, 5.0, 0.0, .nan, .infinity, 5e-320, 1e+300, 1e-160] as [Double], mftype: .Double, shape: [12]), rtol: 1e-12, atol: 0, checkType: true, "Matft.complex.abs(ABS)")
        XCTAssertClose(Matft.math.abs(ABS), MfArray([1.414213562373095e+200, 1.414213562373095e-200, 4.242640687119285e+307, .infinity, .infinity, 5.0, 0.0, .nan, .infinity, 5e-320, 1e+300, 1e-160] as [Double], mftype: .Double, shape: [12]), rtol: 1e-12, atol: 0, checkType: true, "Matft.math.abs(ABS)")
        XCTAssertClose(Matft.complex.abs(ABSF), MfArray([1.414213581995256e+20, 1.414213624540733e-25, .infinity, .infinity, 5.0, 0.0, .nan, 9.99994610111476e-41, 5.000000100204387e+19] as [Double], mftype: .Float, shape: [9]), rtol: 1e-06, atol: 0, checkType: true, "Matft.complex.abs(ABSF)")
        for (name, x) in [("contiguous", ABS2), ("column", ABS2.to_contiguous(mforder: .Column)), ("offset view", ABS2_pad[1~<3]), ("prefix view", ABS2_pre[0~<2]), ("strided view", ABS2_str[0~<4~<2]), ("reversed view", ABS2_rev[Matft.reverse]), ("transposed view", ABS2_t.T)] as [(String, MfArray)]{
            XCTAssertClose(Matft.complex.abs(x), MfArray([1.414213562373095e+200, 5.0, 1.414213562373095e-200, .infinity] as [Double], mftype: .Double, shape: [2, 2]), rtol: 1e-12, atol: 0, checkType: true, "Matft.complex.abs(x) \(name)")
        }
        XCTAssertClose(Matft.complex.absarg(ABS).abs, MfArray([1.414213562373095e+200, 1.414213562373095e-200, 4.242640687119285e+307, .infinity, .infinity, 5.0, 0.0, .nan, .infinity, 5e-320, 1e+300, 1e-160] as [Double], mftype: .Double, shape: [12]), rtol: 1e-12, atol: 0, checkType: true, "Matft.complex.absarg(ABS).abs")
        do {
            let ret = Matft.math.log(LOGZ)
            XCTAssertTrue(ret.isComplex, "not complex: Matft.math.log(LOGZ)")
            XCTAssertClose(ret.real, MfArray([460.8635921890891, -460.1704450085292] as [Double], mftype: .Double, shape: [2]), rtol: 1e-12, atol: 0, checkType: true, "real: Matft.math.log(LOGZ)")
            XCTAssertClose(ret.imag ?? MfArray([Double.nan]), MfArray([0.7853981633974483, 0.7853981633974483] as [Double], mftype: .Double, shape: [2]), rtol: 1e-12, atol: 0, checkType: true, "imag: Matft.math.log(LOGZ)")
        }
    }
}
#endif
