// Generated by python/gen_bughunt_stats_sort.py (numpy 2.0.2). Do not edit by hand.
import XCTest

import Matft

/// Regression tests for sort / argsort with NaN, cov (ddof > N, rowvar on a single row), unique_* with NaN and stacked pinv. Expected values are numpy outputs
final class BugHuntStatsSortTests: XCTestCase {
    private let SN = MfArray([3.0, .nan, 1.0, 2.0, .nan, 0.5] as [Double], mftype: .Double, shape: [6])
    private let SNF = MfArray([3.0, .nan, 1.0, 2.0, .nan, 0.5] as [Double], mftype: .Float, shape: [6])
    private let SINF = MfArray([.infinity, -.infinity, 1.0, .nan, -0.5] as [Double], mftype: .Double, shape: [5])
    private let M = MfArray([4.0, .nan, -1.0, 7.0, .nan, .nan, 2.0, -3.0, 0.5, 9.0, .infinity, .nan] as [Double], mftype: .Double, shape: [3, 4])
    private let MF = MfArray([4.0, .nan, -1.0, 7.0, .nan, .nan, 2.0, -3.0, 0.5, 9.0, .infinity, .nan] as [Double], mftype: .Float, shape: [3, 4])
    private let M3 = MfArray([7.0, .nan, 2.0, 0.0, 5.0, -5.0, -8.0, 1.0, .nan, 6.0, -2.0, 9.0, 3.0, 4.0, -1.0, .nan, 2.5, 8.0, -6.0, -4.0, 1.5, -7.0, .nan, 12.0] as [Double], mftype: .Double, shape: [2, 3, 4])
    private let L = MfArray([-20.0, -3.0, 14.0, -10.0, 7.0, -17.0, 0.0, .nan, -7.0, 10.0, -14.0, 3.0, 20.0, -4.0, 13.0, -11.0, 6.0, -18.0, -1.0, 16.0, -8.0, 9.0, -15.0, .nan, 19.0, -5.0, 12.0, -12.0, 5.0, -19.0, -2.0, .nan, -9.0, 8.0, -16.0, 1.0, 18.0, -6.0, 11.0, -13.0] as [Double], mftype: .Double, shape: [40])
    private let LF = MfArray([-20.0, -3.0, 14.0, -10.0, 7.0, -17.0, 0.0, .nan, -7.0, 10.0, -14.0, 3.0, 20.0, -4.0, 13.0, -11.0, 6.0, -18.0, -1.0, 16.0, -8.0, 9.0, -15.0, .nan, 19.0, -5.0, 12.0, -12.0, 5.0, -19.0, -2.0, .nan, -9.0, 8.0, -16.0, 1.0, 18.0, -6.0, 11.0, -13.0] as [Double], mftype: .Float, shape: [40])
    private let ALLNAN = MfArray([.nan, .nan, .nan, 1.0, .nan, 0.0] as [Double], mftype: .Double, shape: [2, 3])
    private let NONAN = MfArray([3.0, -1.0, 2.0, 0.0, 5.0, 4.0] as [Double], mftype: .Double, shape: [2, 3])
    private let CV1 = MfArray([1.0, 2.0] as [Double], mftype: .Double, shape: [2])
    private let CV2 = MfArray([1.0, 2.0, 4.0, 3.0, 1.0, 0.0] as [Double], mftype: .Double, shape: [2, 3])
    private let ROW = MfArray([1.0, 2.0, 4.0] as [Double], mftype: .Double, shape: [1, 3])
    private let ROWY = MfArray([2.0, -1.0, 0.5] as [Double], mftype: .Double, shape: [1, 3])
    private let UN = MfArray([.nan, 1.0, .nan, 0.0] as [Double], mftype: .Double, shape: [4])
    private let UNF = MfArray([.nan, 2.0, 1.0, .nan, 2.0, .nan] as [Double], mftype: .Float, shape: [2, 3])
    private let P = MfArray([1e-06, 2e-06, 5e-07, 0.0, 1e-06, 3e-06, 4000000.0, -1000000.0, 2000000.0, 1000000.0, 3000000.0, 0.0] as [Double], mftype: .Double, shape: [2, 2, 3])
    private let Q = MfArray([1.0, 2.0, 2.0, 4.0, 0.0, 1.0, 3.0, 0.0, 0.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, -1.0, 0.0, 5.0, 7.0, 3.0] as [Double], mftype: .Double, shape: [2, 2, 3, 2])
    private let QF = MfArray([1.0, 2.0, 2.0, 4.0, 0.0, 1.0, 3.0, 0.0, 0.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, -1.0, 0.0, 5.0, 7.0, 3.0] as [Double], mftype: .Float, shape: [2, 2, 3, 2])
    private let R3 = MfArray([-2.0, 0.0, 2.0, -1.0, 1.0, -2.0, 0.0, 2.0, -1.0, 1.0, -2.0, 0.0, 2.0, -1.0, 1.0, -2.0, 0.0, 2.0, -1.0, 1.0, -2.0, 0.0, 2.0, -1.0] as [Double], mftype: .Double, shape: [2, 3, 4])

    func test_sort_nan_1d() throws {
        XCTAssertClose(Matft.sort(SN, axis: nil), MfArray([0.5, 1.0, 2.0, 3.0, .nan, .nan] as [Double], mftype: .Double, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.sort(SN, axis: nil)")
        XCTAssertClose(Matft.sort(SN, axis: nil, order: .Descending), MfArray([.nan, .nan, 3.0, 2.0, 1.0, 0.5] as [Double], mftype: .Double, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.sort(SN, axis: nil, order: .Descending)")
        XCTAssertClose(Matft.argsort(SN, axis: nil), MfArray([5, 2, 3, 0, 1, 4] as [Int], mftype: .Int, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(SN, axis: nil)")
        XCTAssertClose(Matft.argsort(SN, axis: nil, order: .Descending), MfArray([4, 1, 0, 3, 2, 5] as [Int], mftype: .Int, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(SN, axis: nil, order: .Descending)")
        XCTAssertClose(Matft.sort(SN, axis: -1), MfArray([0.5, 1.0, 2.0, 3.0, .nan, .nan] as [Double], mftype: .Double, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.sort(SN, axis: -1)")
        XCTAssertClose(Matft.sort(SN, axis: -1, order: .Descending), MfArray([.nan, .nan, 3.0, 2.0, 1.0, 0.5] as [Double], mftype: .Double, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.sort(SN, axis: -1, order: .Descending)")
        XCTAssertClose(Matft.argsort(SN, axis: -1), MfArray([5, 2, 3, 0, 1, 4] as [Int], mftype: .Int, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(SN, axis: -1)")
        XCTAssertClose(Matft.argsort(SN, axis: -1, order: .Descending), MfArray([4, 1, 0, 3, 2, 5] as [Int], mftype: .Int, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(SN, axis: -1, order: .Descending)")
        XCTAssertClose(Matft.sort(SNF, axis: nil), MfArray([0.5, 1.0, 2.0, 3.0, .nan, .nan] as [Double], mftype: .Float, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.sort(SNF, axis: nil)")
        XCTAssertClose(Matft.sort(SNF, axis: nil, order: .Descending), MfArray([.nan, .nan, 3.0, 2.0, 1.0, 0.5] as [Double], mftype: .Float, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.sort(SNF, axis: nil, order: .Descending)")
        XCTAssertClose(Matft.argsort(SNF, axis: nil), MfArray([5, 2, 3, 0, 1, 4] as [Int], mftype: .Int, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(SNF, axis: nil)")
        XCTAssertClose(Matft.argsort(SNF, axis: nil, order: .Descending), MfArray([4, 1, 0, 3, 2, 5] as [Int], mftype: .Int, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(SNF, axis: nil, order: .Descending)")
        XCTAssertClose(Matft.sort(SNF, axis: -1), MfArray([0.5, 1.0, 2.0, 3.0, .nan, .nan] as [Double], mftype: .Float, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.sort(SNF, axis: -1)")
        XCTAssertClose(Matft.sort(SNF, axis: -1, order: .Descending), MfArray([.nan, .nan, 3.0, 2.0, 1.0, 0.5] as [Double], mftype: .Float, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.sort(SNF, axis: -1, order: .Descending)")
        XCTAssertClose(Matft.argsort(SNF, axis: -1), MfArray([5, 2, 3, 0, 1, 4] as [Int], mftype: .Int, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(SNF, axis: -1)")
        XCTAssertClose(Matft.argsort(SNF, axis: -1, order: .Descending), MfArray([4, 1, 0, 3, 2, 5] as [Int], mftype: .Int, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(SNF, axis: -1, order: .Descending)")
        XCTAssertClose(Matft.sort(SINF, axis: nil), MfArray([-.infinity, -0.5, 1.0, .infinity, .nan] as [Double], mftype: .Double, shape: [5]), rtol: 0, atol: 0, checkType: true, "Matft.sort(SINF, axis: nil)")
        XCTAssertClose(Matft.sort(SINF, axis: nil, order: .Descending), MfArray([.nan, .infinity, 1.0, -0.5, -.infinity] as [Double], mftype: .Double, shape: [5]), rtol: 0, atol: 0, checkType: true, "Matft.sort(SINF, axis: nil, order: .Descending)")
        XCTAssertClose(Matft.argsort(SINF, axis: nil), MfArray([1, 4, 2, 0, 3] as [Int], mftype: .Int, shape: [5]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(SINF, axis: nil)")
        XCTAssertClose(Matft.argsort(SINF, axis: nil, order: .Descending), MfArray([3, 0, 2, 4, 1] as [Int], mftype: .Int, shape: [5]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(SINF, axis: nil, order: .Descending)")
    }

    func test_sort_nan_2d() throws {
        for (name, x) in layoutVariants(M){
            XCTAssertClose(Matft.sort(x, axis: nil), MfArray([-3.0, -1.0, 0.5, 2.0, 4.0, 7.0, 9.0, .infinity, .nan, .nan, .nan, .nan] as [Double], mftype: .Double, shape: [12]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: nil) \(name)")
        }
        for (name, x) in layoutVariants(M){
            XCTAssertClose(Matft.sort(x, axis: nil, order: .Descending), MfArray([.nan, .nan, .nan, .nan, .infinity, 9.0, 7.0, 4.0, 2.0, 0.5, -1.0, -3.0] as [Double], mftype: .Double, shape: [12]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: nil, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(M){
            XCTAssertClose(Matft.argsort(x, axis: nil), MfArray([7, 2, 8, 6, 0, 3, 9, 10, 1, 4, 5, 11] as [Int], mftype: .Int, shape: [12]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: nil) \(name)")
        }
        for (name, x) in layoutVariants(M){
            XCTAssertClose(Matft.argsort(x, axis: nil, order: .Descending), MfArray([11, 5, 4, 1, 10, 9, 3, 0, 6, 8, 2, 7] as [Int], mftype: .Int, shape: [12]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: nil, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(M){
            XCTAssertClose(Matft.sort(x, axis: 0), MfArray([0.5, 9.0, -1.0, -3.0, 4.0, .nan, 2.0, 7.0, .nan, .nan, .infinity, .nan] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(M){
            XCTAssertClose(Matft.sort(x, axis: 0, order: .Descending), MfArray([.nan, .nan, .infinity, .nan, 4.0, .nan, 2.0, 7.0, 0.5, 9.0, -1.0, -3.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 0, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(M){
            XCTAssertClose(Matft.argsort(x, axis: 0), MfArray([2, 2, 0, 1, 0, 0, 1, 0, 1, 1, 2, 2] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(M){
            XCTAssertClose(Matft.argsort(x, axis: 0, order: .Descending), MfArray([1, 1, 2, 2, 0, 0, 1, 0, 2, 2, 0, 1] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 0, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(M){
            XCTAssertClose(Matft.sort(x, axis: 1), MfArray([-1.0, 4.0, 7.0, .nan, -3.0, 2.0, .nan, .nan, 0.5, 9.0, .infinity, .nan] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(M){
            XCTAssertClose(Matft.sort(x, axis: 1, order: .Descending), MfArray([.nan, 7.0, 4.0, -1.0, .nan, .nan, 2.0, -3.0, .nan, .infinity, 9.0, 0.5] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 1, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(M){
            XCTAssertClose(Matft.argsort(x, axis: 1), MfArray([2, 0, 3, 1, 3, 2, 0, 1, 0, 1, 2, 3] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(M){
            XCTAssertClose(Matft.argsort(x, axis: 1, order: .Descending), MfArray([1, 3, 0, 2, 1, 0, 2, 3, 3, 2, 1, 0] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 1, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(M){
            XCTAssertClose(Matft.sort(x, axis: -1), MfArray([-1.0, 4.0, 7.0, .nan, -3.0, 2.0, .nan, .nan, 0.5, 9.0, .infinity, .nan] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: -1) \(name)")
        }
        for (name, x) in layoutVariants(M){
            XCTAssertClose(Matft.sort(x, axis: -1, order: .Descending), MfArray([.nan, 7.0, 4.0, -1.0, .nan, .nan, 2.0, -3.0, .nan, .infinity, 9.0, 0.5] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: -1, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(M){
            XCTAssertClose(Matft.argsort(x, axis: -1), MfArray([2, 0, 3, 1, 3, 2, 0, 1, 0, 1, 2, 3] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: -1) \(name)")
        }
        for (name, x) in layoutVariants(M){
            XCTAssertClose(Matft.argsort(x, axis: -1, order: .Descending), MfArray([1, 3, 0, 2, 1, 0, 2, 3, 3, 2, 1, 0] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: -1, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(MF){
            XCTAssertClose(Matft.sort(x, axis: nil), MfArray([-3.0, -1.0, 0.5, 2.0, 4.0, 7.0, 9.0, .infinity, .nan, .nan, .nan, .nan] as [Double], mftype: .Float, shape: [12]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: nil) \(name)")
        }
        for (name, x) in layoutVariants(MF){
            XCTAssertClose(Matft.sort(x, axis: nil, order: .Descending), MfArray([.nan, .nan, .nan, .nan, .infinity, 9.0, 7.0, 4.0, 2.0, 0.5, -1.0, -3.0] as [Double], mftype: .Float, shape: [12]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: nil, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(MF){
            XCTAssertClose(Matft.argsort(x, axis: nil), MfArray([7, 2, 8, 6, 0, 3, 9, 10, 1, 4, 5, 11] as [Int], mftype: .Int, shape: [12]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: nil) \(name)")
        }
        for (name, x) in layoutVariants(MF){
            XCTAssertClose(Matft.argsort(x, axis: nil, order: .Descending), MfArray([11, 5, 4, 1, 10, 9, 3, 0, 6, 8, 2, 7] as [Int], mftype: .Int, shape: [12]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: nil, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(MF){
            XCTAssertClose(Matft.sort(x, axis: 0), MfArray([0.5, 9.0, -1.0, -3.0, 4.0, .nan, 2.0, 7.0, .nan, .nan, .infinity, .nan] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(MF){
            XCTAssertClose(Matft.sort(x, axis: 0, order: .Descending), MfArray([.nan, .nan, .infinity, .nan, 4.0, .nan, 2.0, 7.0, 0.5, 9.0, -1.0, -3.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 0, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(MF){
            XCTAssertClose(Matft.argsort(x, axis: 0), MfArray([2, 2, 0, 1, 0, 0, 1, 0, 1, 1, 2, 2] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(MF){
            XCTAssertClose(Matft.argsort(x, axis: 0, order: .Descending), MfArray([1, 1, 2, 2, 0, 0, 1, 0, 2, 2, 0, 1] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 0, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(MF){
            XCTAssertClose(Matft.sort(x, axis: 1), MfArray([-1.0, 4.0, 7.0, .nan, -3.0, 2.0, .nan, .nan, 0.5, 9.0, .infinity, .nan] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(MF){
            XCTAssertClose(Matft.sort(x, axis: 1, order: .Descending), MfArray([.nan, 7.0, 4.0, -1.0, .nan, .nan, 2.0, -3.0, .nan, .infinity, 9.0, 0.5] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 1, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(MF){
            XCTAssertClose(Matft.argsort(x, axis: 1), MfArray([2, 0, 3, 1, 3, 2, 0, 1, 0, 1, 2, 3] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(MF){
            XCTAssertClose(Matft.argsort(x, axis: 1, order: .Descending), MfArray([1, 3, 0, 2, 1, 0, 2, 3, 3, 2, 1, 0] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 1, order: .Descending) \(name)")
        }
    }

    func test_sort_nan_3d() throws {
        for (name, x) in layoutVariants(M3){
            XCTAssertClose(Matft.sort(x, axis: nil), MfArray([-8.0, -7.0, -6.0, -5.0, -4.0, -2.0, -1.0, 0.0, 1.0, 1.5, 2.0, 2.5, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 12.0, .nan, .nan, .nan, .nan] as [Double], mftype: .Double, shape: [24]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: nil) \(name)")
        }
        for (name, x) in layoutVariants(M3){
            XCTAssertClose(Matft.sort(x, axis: nil, order: .Descending), MfArray([.nan, .nan, .nan, .nan, 12.0, 9.0, 8.0, 7.0, 6.0, 5.0, 4.0, 3.0, 2.5, 2.0, 1.5, 1.0, 0.0, -1.0, -2.0, -4.0, -5.0, -6.0, -7.0, -8.0] as [Double], mftype: .Double, shape: [24]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: nil, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(M3){
            XCTAssertClose(Matft.argsort(x, axis: nil), MfArray([6, 21, 18, 5, 19, 10, 14, 3, 7, 20, 2, 16, 12, 13, 4, 9, 0, 17, 11, 23, 1, 8, 15, 22] as [Int], mftype: .Int, shape: [24]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: nil) \(name)")
        }
        for (name, x) in layoutVariants(M3){
            XCTAssertClose(Matft.argsort(x, axis: nil, order: .Descending), MfArray([22, 15, 8, 1, 23, 11, 17, 0, 9, 4, 13, 12, 16, 2, 20, 7, 3, 14, 10, 19, 5, 18, 21, 6] as [Int], mftype: .Int, shape: [24]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: nil, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(M3){
            XCTAssertClose(Matft.sort(x, axis: 0), MfArray([3.0, 4.0, -1.0, 0.0, 2.5, -5.0, -8.0, -4.0, 1.5, -7.0, -2.0, 9.0, 7.0, .nan, 2.0, .nan, 5.0, 8.0, -6.0, 1.0, .nan, 6.0, .nan, 12.0] as [Double], mftype: .Double, shape: [2, 3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(M3){
            XCTAssertClose(Matft.sort(x, axis: 0, order: .Descending), MfArray([7.0, .nan, 2.0, .nan, 5.0, 8.0, -6.0, 1.0, .nan, 6.0, .nan, 12.0, 3.0, 4.0, -1.0, 0.0, 2.5, -5.0, -8.0, -4.0, 1.5, -7.0, -2.0, 9.0] as [Double], mftype: .Double, shape: [2, 3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 0, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(M3){
            XCTAssertClose(Matft.argsort(x, axis: 0), MfArray([1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1] as [Int], mftype: .Int, shape: [2, 3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(M3){
            XCTAssertClose(Matft.argsort(x, axis: 0, order: .Descending), MfArray([0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0] as [Int], mftype: .Int, shape: [2, 3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 0, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(M3){
            XCTAssertClose(Matft.sort(x, axis: 1), MfArray([5.0, -5.0, -8.0, 0.0, 7.0, 6.0, -2.0, 1.0, .nan, .nan, 2.0, 9.0, 1.5, -7.0, -6.0, -4.0, 2.5, 4.0, -1.0, 12.0, 3.0, 8.0, .nan, .nan] as [Double], mftype: .Double, shape: [2, 3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(M3){
            XCTAssertClose(Matft.sort(x, axis: 1, order: .Descending), MfArray([.nan, .nan, 2.0, 9.0, 7.0, 6.0, -2.0, 1.0, 5.0, -5.0, -8.0, 0.0, 3.0, 8.0, .nan, .nan, 2.5, 4.0, -1.0, 12.0, 1.5, -7.0, -6.0, -4.0] as [Double], mftype: .Double, shape: [2, 3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 1, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(M3){
            XCTAssertClose(Matft.argsort(x, axis: 1), MfArray([1, 1, 1, 0, 0, 2, 2, 1, 2, 0, 0, 2, 2, 2, 1, 1, 1, 0, 0, 2, 0, 1, 2, 0] as [Int], mftype: .Int, shape: [2, 3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(M3){
            XCTAssertClose(Matft.argsort(x, axis: 1, order: .Descending), MfArray([2, 0, 0, 2, 0, 2, 2, 1, 1, 1, 1, 0, 0, 1, 2, 0, 1, 0, 0, 2, 2, 2, 1, 1] as [Int], mftype: .Int, shape: [2, 3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 1, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(M3){
            XCTAssertClose(Matft.sort(x, axis: 2), MfArray([0.0, 2.0, 7.0, .nan, -8.0, -5.0, 1.0, 5.0, -2.0, 6.0, 9.0, .nan, -1.0, 3.0, 4.0, .nan, -6.0, -4.0, 2.5, 8.0, -7.0, 1.5, 12.0, .nan] as [Double], mftype: .Double, shape: [2, 3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 2) \(name)")
        }
        for (name, x) in layoutVariants(M3){
            XCTAssertClose(Matft.sort(x, axis: 2, order: .Descending), MfArray([.nan, 7.0, 2.0, 0.0, 5.0, 1.0, -5.0, -8.0, .nan, 9.0, 6.0, -2.0, .nan, 4.0, 3.0, -1.0, 8.0, 2.5, -4.0, -6.0, .nan, 12.0, 1.5, -7.0] as [Double], mftype: .Double, shape: [2, 3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 2, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(M3){
            XCTAssertClose(Matft.argsort(x, axis: 2), MfArray([3, 2, 0, 1, 2, 1, 3, 0, 2, 1, 3, 0, 2, 0, 1, 3, 2, 3, 0, 1, 1, 0, 3, 2] as [Int], mftype: .Int, shape: [2, 3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 2) \(name)")
        }
        for (name, x) in layoutVariants(M3){
            XCTAssertClose(Matft.argsort(x, axis: 2, order: .Descending), MfArray([1, 0, 2, 3, 0, 3, 1, 2, 0, 3, 1, 2, 3, 1, 0, 2, 1, 0, 3, 2, 2, 3, 0, 1] as [Int], mftype: .Int, shape: [2, 3, 4]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 2, order: .Descending) \(name)")
        }
    }

    func test_sort_nan_long() throws {
        XCTAssertClose(Matft.sort(L, axis: nil), MfArray([-20.0, -19.0, -18.0, -17.0, -16.0, -15.0, -14.0, -13.0, -12.0, -11.0, -10.0, -9.0, -8.0, -7.0, -6.0, -5.0, -4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 3.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 16.0, 18.0, 19.0, 20.0, .nan, .nan, .nan] as [Double], mftype: .Double, shape: [40]), rtol: 0, atol: 0, checkType: true, "Matft.sort(L, axis: nil)")
        XCTAssertClose(Matft.sort(L, axis: nil, order: .Descending), MfArray([.nan, .nan, .nan, 20.0, 19.0, 18.0, 16.0, 14.0, 13.0, 12.0, 11.0, 10.0, 9.0, 8.0, 7.0, 6.0, 5.0, 3.0, 1.0, 0.0, -1.0, -2.0, -3.0, -4.0, -5.0, -6.0, -7.0, -8.0, -9.0, -10.0, -11.0, -12.0, -13.0, -14.0, -15.0, -16.0, -17.0, -18.0, -19.0, -20.0] as [Double], mftype: .Double, shape: [40]), rtol: 0, atol: 0, checkType: true, "Matft.sort(L, axis: nil, order: .Descending)")
        XCTAssertClose(Matft.argsort(L, axis: nil), MfArray([0, 29, 17, 5, 34, 22, 10, 39, 27, 15, 3, 32, 20, 8, 37, 25, 13, 1, 30, 18, 6, 35, 11, 28, 16, 4, 33, 21, 9, 38, 26, 14, 2, 19, 36, 24, 12, 7, 23, 31] as [Int], mftype: .Int, shape: [40]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(L, axis: nil)")
        XCTAssertClose(Matft.argsort(L, axis: nil, order: .Descending), MfArray([31, 23, 7, 12, 24, 36, 19, 2, 14, 26, 38, 9, 21, 33, 4, 16, 28, 11, 35, 6, 18, 30, 1, 13, 25, 37, 8, 20, 32, 3, 15, 27, 39, 10, 22, 34, 5, 17, 29, 0] as [Int], mftype: .Int, shape: [40]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(L, axis: nil, order: .Descending)")
        XCTAssertClose(Matft.sort(LF, axis: nil), MfArray([-20.0, -19.0, -18.0, -17.0, -16.0, -15.0, -14.0, -13.0, -12.0, -11.0, -10.0, -9.0, -8.0, -7.0, -6.0, -5.0, -4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 3.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 16.0, 18.0, 19.0, 20.0, .nan, .nan, .nan] as [Double], mftype: .Float, shape: [40]), rtol: 0, atol: 0, checkType: true, "Matft.sort(LF, axis: nil)")
        XCTAssertClose(Matft.sort(LF, axis: nil, order: .Descending), MfArray([.nan, .nan, .nan, 20.0, 19.0, 18.0, 16.0, 14.0, 13.0, 12.0, 11.0, 10.0, 9.0, 8.0, 7.0, 6.0, 5.0, 3.0, 1.0, 0.0, -1.0, -2.0, -3.0, -4.0, -5.0, -6.0, -7.0, -8.0, -9.0, -10.0, -11.0, -12.0, -13.0, -14.0, -15.0, -16.0, -17.0, -18.0, -19.0, -20.0] as [Double], mftype: .Float, shape: [40]), rtol: 0, atol: 0, checkType: true, "Matft.sort(LF, axis: nil, order: .Descending)")
        XCTAssertClose(Matft.argsort(LF, axis: nil), MfArray([0, 29, 17, 5, 34, 22, 10, 39, 27, 15, 3, 32, 20, 8, 37, 25, 13, 1, 30, 18, 6, 35, 11, 28, 16, 4, 33, 21, 9, 38, 26, 14, 2, 19, 36, 24, 12, 7, 23, 31] as [Int], mftype: .Int, shape: [40]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(LF, axis: nil)")
        XCTAssertClose(Matft.argsort(LF, axis: nil, order: .Descending), MfArray([31, 23, 7, 12, 24, 36, 19, 2, 14, 26, 38, 9, 21, 33, 4, 16, 28, 11, 35, 6, 18, 30, 1, 13, 25, 37, 8, 20, 32, 3, 15, 27, 39, 10, 22, 34, 5, 17, 29, 0] as [Int], mftype: .Int, shape: [40]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(LF, axis: nil, order: .Descending)")
    }

    func test_sort_all_nan_lane() throws {
        for (name, x) in layoutVariants(ALLNAN){
            XCTAssertClose(Matft.sort(x, axis: nil), MfArray([0.0, 1.0, .nan, .nan, .nan, .nan] as [Double], mftype: .Double, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: nil) \(name)")
        }
        for (name, x) in layoutVariants(ALLNAN){
            XCTAssertClose(Matft.sort(x, axis: nil, order: .Descending), MfArray([.nan, .nan, .nan, .nan, 1.0, 0.0] as [Double], mftype: .Double, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: nil, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(ALLNAN){
            XCTAssertClose(Matft.argsort(x, axis: nil), MfArray([5, 3, 0, 1, 2, 4] as [Int], mftype: .Int, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: nil) \(name)")
        }
        for (name, x) in layoutVariants(ALLNAN){
            XCTAssertClose(Matft.argsort(x, axis: nil, order: .Descending), MfArray([4, 2, 1, 0, 3, 5] as [Int], mftype: .Int, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: nil, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(ALLNAN){
            XCTAssertClose(Matft.sort(x, axis: 0), MfArray([1.0, .nan, 0.0, .nan, .nan, .nan] as [Double], mftype: .Double, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(ALLNAN){
            XCTAssertClose(Matft.sort(x, axis: 0, order: .Descending), MfArray([.nan, .nan, .nan, 1.0, .nan, 0.0] as [Double], mftype: .Double, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 0, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(ALLNAN){
            XCTAssertClose(Matft.argsort(x, axis: 0), MfArray([1, 0, 1, 0, 1, 0] as [Int], mftype: .Int, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(ALLNAN){
            XCTAssertClose(Matft.argsort(x, axis: 0, order: .Descending), MfArray([0, 1, 0, 1, 0, 1] as [Int], mftype: .Int, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 0, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(ALLNAN){
            XCTAssertClose(Matft.sort(x, axis: 1), MfArray([.nan, .nan, .nan, 0.0, 1.0, .nan] as [Double], mftype: .Double, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(ALLNAN){
            XCTAssertClose(Matft.sort(x, axis: 1, order: .Descending), MfArray([.nan, .nan, .nan, .nan, 1.0, 0.0] as [Double], mftype: .Double, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 1, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(ALLNAN){
            XCTAssertClose(Matft.argsort(x, axis: 1), MfArray([0, 1, 2, 2, 0, 1] as [Int], mftype: .Int, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(ALLNAN){
            XCTAssertClose(Matft.argsort(x, axis: 1, order: .Descending), MfArray([2, 1, 0, 1, 0, 2] as [Int], mftype: .Int, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 1, order: .Descending) \(name)")
        }
    }

    func test_sort_no_nan() throws {
        for (name, x) in layoutVariants(NONAN){
            XCTAssertClose(Matft.sort(x, axis: nil), MfArray([-1.0, 0.0, 2.0, 3.0, 4.0, 5.0] as [Double], mftype: .Double, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: nil) \(name)")
        }
        for (name, x) in layoutVariants(NONAN){
            XCTAssertClose(Matft.sort(x, axis: nil, order: .Descending), MfArray([5.0, 4.0, 3.0, 2.0, 0.0, -1.0] as [Double], mftype: .Double, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: nil, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(NONAN){
            XCTAssertClose(Matft.argsort(x, axis: nil), MfArray([1, 3, 2, 0, 5, 4] as [Int], mftype: .Int, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: nil) \(name)")
        }
        for (name, x) in layoutVariants(NONAN){
            XCTAssertClose(Matft.argsort(x, axis: nil, order: .Descending), MfArray([4, 5, 0, 2, 3, 1] as [Int], mftype: .Int, shape: [6]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: nil, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(NONAN){
            XCTAssertClose(Matft.sort(x, axis: 0), MfArray([0.0, -1.0, 2.0, 3.0, 5.0, 4.0] as [Double], mftype: .Double, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(NONAN){
            XCTAssertClose(Matft.sort(x, axis: 0, order: .Descending), MfArray([3.0, 5.0, 4.0, 0.0, -1.0, 2.0] as [Double], mftype: .Double, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 0, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(NONAN){
            XCTAssertClose(Matft.argsort(x, axis: 0), MfArray([1, 0, 0, 0, 1, 1] as [Int], mftype: .Int, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(NONAN){
            XCTAssertClose(Matft.argsort(x, axis: 0, order: .Descending), MfArray([0, 1, 1, 1, 0, 0] as [Int], mftype: .Int, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 0, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(NONAN){
            XCTAssertClose(Matft.sort(x, axis: 1), MfArray([-1.0, 2.0, 3.0, 0.0, 4.0, 5.0] as [Double], mftype: .Double, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(NONAN){
            XCTAssertClose(Matft.sort(x, axis: 1, order: .Descending), MfArray([3.0, 2.0, -1.0, 5.0, 4.0, 0.0] as [Double], mftype: .Double, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "Matft.sort(x, axis: 1, order: .Descending) \(name)")
        }
        for (name, x) in layoutVariants(NONAN){
            XCTAssertClose(Matft.argsort(x, axis: 1), MfArray([1, 2, 0, 0, 2, 1] as [Int], mftype: .Int, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(NONAN){
            XCTAssertClose(Matft.argsort(x, axis: 1, order: .Descending), MfArray([0, 2, 1, 1, 2, 0] as [Int], mftype: .Int, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "Matft.argsort(x, axis: 1, order: .Descending) \(name)")
        }
    }

    func test_cov_ddof_larger_than_n() throws {
        XCTAssertClose(Matft.stats.cov(CV1, ddof: 2), MfArray([.infinity] as [Double], mftype: .Double, shape: [1]), rtol: 1e-10, atol: 1e-10, checkType: true, "Matft.stats.cov(CV1, ddof: 2)")
        XCTAssertClose(Matft.stats.cov(CV1, ddof: 3), MfArray([.infinity] as [Double], mftype: .Double, shape: [1]), rtol: 1e-10, atol: 1e-10, checkType: true, "Matft.stats.cov(CV1, ddof: 3)")
        XCTAssertClose(Matft.stats.cov(CV1, ddof: 5), MfArray([.infinity] as [Double], mftype: .Double, shape: [1]), rtol: 1e-10, atol: 1e-10, checkType: true, "Matft.stats.cov(CV1, ddof: 5)")
        XCTAssertClose(Matft.stats.cov(CV2, ddof: 3), MfArray([.infinity, -.infinity, -.infinity, .infinity] as [Double], mftype: .Double, shape: [2, 2]), rtol: 1e-10, atol: 1e-10, checkType: true, "Matft.stats.cov(CV2, ddof: 3)")
        XCTAssertClose(Matft.stats.cov(CV2, ddof: 4), MfArray([.infinity, -.infinity, -.infinity, .infinity] as [Double], mftype: .Double, shape: [2, 2]), rtol: 1e-10, atol: 1e-10, checkType: true, "Matft.stats.cov(CV2, ddof: 4)")
        XCTAssertClose(Matft.stats.cov(CV2, ddof: 5), MfArray([.infinity, -.infinity, -.infinity, .infinity] as [Double], mftype: .Double, shape: [2, 2]), rtol: 1e-10, atol: 1e-10, checkType: true, "Matft.stats.cov(CV2, ddof: 5)")
    }

    func test_cov_rowvar_false_single_row() throws {
        XCTAssertClose(Matft.stats.cov(ROW, rowvar: false), MfArray([2.333333333333333] as [Double], mftype: .Double, shape: [1]), rtol: 1e-10, atol: 1e-10, checkType: true, "Matft.stats.cov(ROW, rowvar: false)")
        XCTAssertClose(Matft.stats.cov(ROW, y: ROWY, rowvar: false), MfArray([2.333333333333333, -0.7499999999999999, -0.7499999999999999, 2.25] as [Double], mftype: .Double, shape: [2, 2]), rtol: 1e-10, atol: 1e-10, checkType: true, "Matft.stats.cov(ROW, y: ROWY, rowvar: false)")
        XCTAssertClose(Matft.stats.cov(ROW, rowvar: true), MfArray([2.333333333333333] as [Double], mftype: .Double, shape: [1]), rtol: 1e-10, atol: 1e-10, checkType: true, "Matft.stats.cov(ROW, rowvar: true)")
        XCTAssertClose(Matft.stats.corrcoef(ROW, y: ROWY, rowvar: false), MfArray([1.0, -0.32732683535398854, -0.32732683535398854, 1.0] as [Double], mftype: .Double, shape: [2, 2]), rtol: 1e-10, atol: 1e-10, checkType: true, "Matft.stats.corrcoef(ROW, y: ROWY, rowvar: false)")
        XCTAssertClose(Matft.stats.cov(CV2, rowvar: false), MfArray([2.0, -1.0, -4.0, -1.0, 0.5, 2.0, -4.0, 2.0, 8.0] as [Double], mftype: .Double, shape: [3, 3]), rtol: 1e-10, atol: 1e-10, checkType: true, "Matft.stats.cov(CV2, rowvar: false)")
    }

    func test_unique_keeps_each_nan() throws {
        XCTAssertClose(Matft.unique_all(UN).values, MfArray([0.0, 1.0, .nan, .nan] as [Double], mftype: .Double, shape: [4]), rtol: 0, atol: 0, checkType: true, "Matft.unique_all(UN).values")
        XCTAssertClose(Matft.unique_all(UN).indices, MfArray([3, 1, 0, 2] as [Int], mftype: .Int, shape: [4]), rtol: 0, atol: 0, checkType: true, "Matft.unique_all(UN).indices")
        XCTAssertClose(Matft.unique_all(UN).inverse_indices, MfArray([2, 1, 3, 0] as [Int], mftype: .Int, shape: [4]), rtol: 0, atol: 0, checkType: true, "Matft.unique_all(UN).inverse_indices")
        XCTAssertClose(Matft.unique_all(UN).counts, MfArray([1, 1, 1, 1] as [Int], mftype: .Int, shape: [4]), rtol: 0, atol: 0, checkType: true, "Matft.unique_all(UN).counts")
        XCTAssertClose(Matft.unique_counts(UN).values, MfArray([0.0, 1.0, .nan, .nan] as [Double], mftype: .Double, shape: [4]), rtol: 0, atol: 0, checkType: true, "Matft.unique_counts(UN).values")
        XCTAssertClose(Matft.unique_counts(UN).counts, MfArray([1, 1, 1, 1] as [Int], mftype: .Int, shape: [4]), rtol: 0, atol: 0, checkType: true, "Matft.unique_counts(UN).counts")
        XCTAssertClose(Matft.unique_inverse(UN).values, MfArray([0.0, 1.0, .nan, .nan] as [Double], mftype: .Double, shape: [4]), rtol: 0, atol: 0, checkType: true, "Matft.unique_inverse(UN).values")
        XCTAssertClose(Matft.unique_inverse(UN).inverse_indices, MfArray([2, 1, 3, 0] as [Int], mftype: .Int, shape: [4]), rtol: 0, atol: 0, checkType: true, "Matft.unique_inverse(UN).inverse_indices")
        XCTAssertClose(Matft.unique(UN), MfArray([0.0, 1.0, .nan] as [Double], mftype: .Double, shape: [3]), rtol: 0, atol: 0, checkType: true, "Matft.unique(UN)")
        XCTAssertClose(Matft.unique_all(UNF).values, MfArray([1.0, 2.0, .nan, .nan, .nan] as [Double], mftype: .Float, shape: [5]), rtol: 0, atol: 0, checkType: true, "Matft.unique_all(UNF).values")
        XCTAssertClose(Matft.unique_all(UNF).indices, MfArray([2, 1, 0, 3, 5] as [Int], mftype: .Int, shape: [5]), rtol: 0, atol: 0, checkType: true, "Matft.unique_all(UNF).indices")
        XCTAssertClose(Matft.unique_all(UNF).inverse_indices, MfArray([2, 1, 0, 3, 1, 4] as [Int], mftype: .Int, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "Matft.unique_all(UNF).inverse_indices")
        XCTAssertClose(Matft.unique_all(UNF).counts, MfArray([1, 2, 1, 1, 1] as [Int], mftype: .Int, shape: [5]), rtol: 0, atol: 0, checkType: true, "Matft.unique_all(UNF).counts")
        XCTAssertClose(Matft.unique_counts(UNF).values, MfArray([1.0, 2.0, .nan, .nan, .nan] as [Double], mftype: .Float, shape: [5]), rtol: 0, atol: 0, checkType: true, "Matft.unique_counts(UNF).values")
        XCTAssertClose(Matft.unique_counts(UNF).counts, MfArray([1, 2, 1, 1, 1] as [Int], mftype: .Int, shape: [5]), rtol: 0, atol: 0, checkType: true, "Matft.unique_counts(UNF).counts")
        XCTAssertClose(Matft.unique_inverse(UNF).values, MfArray([1.0, 2.0, .nan, .nan, .nan] as [Double], mftype: .Float, shape: [5]), rtol: 0, atol: 0, checkType: true, "Matft.unique_inverse(UNF).values")
        XCTAssertClose(Matft.unique_inverse(UNF).inverse_indices, MfArray([2, 1, 0, 3, 1, 4] as [Int], mftype: .Int, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "Matft.unique_inverse(UNF).inverse_indices")
        XCTAssertClose(Matft.unique(UNF), MfArray([1.0, 2.0, .nan] as [Double], mftype: .Float, shape: [3]), rtol: 0, atol: 0, checkType: true, "Matft.unique(UNF)")
    }

    #if !os(WASI)
    func test_pinv_stacked() throws {
        XCTAssertClose(try Matft.linalg.pinv(P), MfArray([248447.20496894416, -86956.52173913048, 409937.8881987577, -43478.26086956518, -136645.96273291926, 347826.08695652185, 1.866028708133973e-07, 8.133971291866029e-08, -6.220095693779908e-08, 3.0622009569377994e-07, 9.56937799043063e-08, -9.569377990430631e-09] as [Double], mftype: .Double, shape: [2, 3, 2]), rtol: 1e-08, atol: 0, checkType: true, "try Matft.linalg.pinv(P)")
        XCTAssertClose(try Matft.linalg.pinv(P, rcond: 1e-3), MfArray([248447.20496894416, -86956.52173913048, 409937.8881987577, -43478.26086956518, -136645.96273291926, 347826.08695652185, 1.866028708133973e-07, 8.133971291866029e-08, -6.220095693779908e-08, 3.0622009569377994e-07, 9.56937799043063e-08, -9.569377990430631e-09] as [Double], mftype: .Double, shape: [2, 3, 2]), rtol: 1e-08, atol: 0, checkType: true, "try Matft.linalg.pinv(P, rcond: 1e-3)")
        for (name, x) in layoutVariants(Q){
            XCTAssertClose(try Matft.linalg.pinv(x), MfArray([0.2000000000000008, 0.3999999999999996, -2.0, -4.0949444169424e-16, 1.4288332180587713e-16, 1.0, 0.30612244897959195, -0.04081632653061226, 0.08163265306122448, -0.06122448979591837, 0.40816326530612246, 0.18367346938775514, 0.16666666666666669, 0.16666666666666669, 0.16666666666666669, 0.16666666666666666, 0.16666666666666666, 0.16666666666666666, 0.05957161981258364, -0.06358768406961175, 0.12583668005354748, -0.06091030789825967, 0.17737617135207492, 0.0174029451137885] as [Double], mftype: .Double, shape: [2, 2, 2, 3]), rtol: 1e-08, atol: 1e-10, checkType: true, "try Matft.linalg.pinv(x) \(name)")
        }
        XCTAssertClose(try Matft.linalg.pinv(QF, rcond: 1e-5), MfArray([0.20000000298023224, 0.4000000059604645, -2.0, -4.0949445199028607e-16, 1.4288332765947795e-16, 1.0, 0.30612245202064514, -0.040816325694322586, 0.08163265138864517, -0.06122449040412903, 0.40816327929496765, 0.18367347121238708, 0.1666666716337204, 0.1666666716337204, 0.1666666716337204, 0.1666666716337204, 0.1666666716337204, 0.1666666716337204, 0.05957162007689476, -0.06358768045902252, 0.12583668529987335, -0.06091030687093735, 0.1773761659860611, 0.017402945086359978] as [Double], mftype: .Float, shape: [2, 2, 2, 3]), rtol: 0.0001, atol: 1e-05, checkType: true, "try Matft.linalg.pinv(QF, rcond: 1e-5)")
        XCTAssertClose(try Matft.linalg.pinv(R3), MfArray([-0.4000000000000003, -0.20000000000000032, -0.4000000000000003, -0.13333333333333344, -0.288888888888889, -0.022222222222222254, 0.1333333333333333, -0.044444444444444425, -0.31111111111111117, 0.06666666666666683, 0.3111111111111112, 0.17777777777777795, 0.2666666666666666, 0.13333333333333322, -0.1777777777777777, 0.1999999999999999, 0.6, 0.20000000000000004, 0.1333333333333333, 0.06666666666666665, 0.24444444444444435, -0.2666666666666666, -0.1333333333333333, -0.15555555555555559] as [Double], mftype: .Double, shape: [2, 4, 3]), rtol: 1e-08, atol: 1e-10, checkType: true, "try Matft.linalg.pinv(R3)")
        XCTAssertClose(try Matft.linalg.pinv(R3, rcond: 0.5), MfArray([-0.11055728090000841, 0.12360679774997896, -0.021114561800016904, -0.010864032288515313, -0.1519640477423393, 0.13809217413466612, 0.21497953402987866, 0.04683878298658862, -0.20423484687318566, -0.09662573472642402, 0.12854465624904496, -0.03597475069807326, 0.179550586812126, -0.010653894471971471, -0.2372430364419876, -0.11641002958599161, 0.07703107065937634, -0.015980841707957154, 0.035571879139762265, -0.09491545226075998, 0.1777126749397011, -0.12534717254582525, 0.10024239949674572, -0.05909115671870737] as [Double], mftype: .Double, shape: [2, 4, 3]), rtol: 1e-08, atol: 1e-10, checkType: true, "try Matft.linalg.pinv(R3, rcond: 0.5)")
    }
    #endif
}
