// Generated by python/gen_bughunt_view_setter.py. Do not edit by hand.
import XCTest

import Matft

/// Setter, view and copy regressions found by the 2026-09-27 bug hunt. Expected values are numpy outputs
final class BugHuntViewSetterTests: XCTestCase {
    func testLeadingOnes_IntIndex() {
        let a = Matft.arange(start: 0.0, to: 12.0, by: 1.0, shape: [3, 4], mftype: .Double)
        a[0] = MfArray([[1.0, 2, 3, 4]] as [[Double]])
        XCTAssertTrue(a.isReal, "a must stay real")
        XCTAssertClose(a, MfArray([1.0, 2.0, 3.0, 4.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0] as [Double], shape: [3, 4]).astype(.Double), checkType: true)
    }

    func testLeadingOnes_Slice() {
        let a = Matft.arange(start: 0.0, to: 12.0, by: 1.0, shape: [3, 4], mftype: .Double)
        a[0~<2] = MfArray([[[9.0]]] as [[[Double]]])
        XCTAssertTrue(a.isReal, "a must stay real")
        XCTAssertClose(a, MfArray([9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 8.0, 9.0, 10.0, 11.0] as [Double], shape: [3, 4]).astype(.Double), checkType: true)
    }

    func testLeadingOnes_SliceRow() {
        let a = Matft.arange(start: 0.0, to: 12.0, by: 1.0, shape: [3, 4], mftype: .Double)
        a[1~<3] = MfArray([[[1.0, 2, 3, 4]]] as [[[Double]]])
        XCTAssertTrue(a.isReal, "a must stay real")
        XCTAssertClose(a, MfArray([0.0, 1.0, 2.0, 3.0, 1.0, 2.0, 3.0, 4.0, 1.0, 2.0, 3.0, 4.0] as [Double], shape: [3, 4]).astype(.Double), checkType: true)
    }

    func testLeadingOnes_Fancy() {
        let a = Matft.arange(start: 0.0, to: 12.0, by: 1.0, shape: [3, 4], mftype: .Double)
        a[MfArray([0, 2])] = MfArray([[[1.0, 2, 3, 4]]] as [[[Double]]])
        XCTAssertTrue(a.isReal, "a must stay real")
        XCTAssertClose(a, MfArray([1.0, 2.0, 3.0, 4.0, 4.0, 5.0, 6.0, 7.0, 1.0, 2.0, 3.0, 4.0] as [Double], shape: [3, 4]).astype(.Double), checkType: true)
    }

    func testLeadingOnes_FancyAll() {
        let a = Matft.arange(start: 0.0, to: 12.0, by: 1.0, shape: [3, 4], mftype: .Double)
        a[MfArray([0, 2]), MfArray([1, 3])] = MfArray([[[5.0, 6.0]]] as [[[Double]]])
        XCTAssertTrue(a.isReal, "a must stay real")
        XCTAssertClose(a, MfArray([0.0, 5.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 6.0] as [Double], shape: [3, 4]).astype(.Double), checkType: true)
    }

    func testLeadingOnes_FancyMixed() {
        let a = Matft.arange(start: 0.0, to: 12.0, by: 1.0, shape: [3, 4], mftype: .Double)
        a[1~<, MfArray([0, 2])] = MfArray([[[7.0, 8.0]]] as [[[Double]]])
        XCTAssertTrue(a.isReal, "a must stay real")
        XCTAssertClose(a, MfArray([0.0, 1.0, 2.0, 3.0, 7.0, 5.0, 8.0, 7.0, 7.0, 9.0, 8.0, 11.0] as [Double], shape: [3, 4]).astype(.Double), checkType: true)
    }

    func testLeadingOnes_BoolMask() {
        let a = Matft.arange(start: 0.0, to: 12.0, by: 1.0, shape: [3, 4], mftype: .Double)
        a[MfArray([true, false, true])] = MfArray([[[1.0, 2, 3, 4]]] as [[[Double]]])
        XCTAssertTrue(a.isReal, "a must stay real")
        XCTAssertClose(a, MfArray([1.0, 2.0, 3.0, 4.0, 4.0, 5.0, 6.0, 7.0, 1.0, 2.0, 3.0, 4.0] as [Double], shape: [3, 4]).astype(.Double), checkType: true)
    }

    func testBoolMask_LeadingAxisGet() {
        let a = Matft.arange(start: 0.0, to: 12.0, by: 1.0, shape: [3, 4], mftype: .Double)
        let r = a[MfArray([false, true, true])]
        XCTAssertTrue(r.isReal, "r must stay real")
        XCTAssertClose(r, MfArray([4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0] as [Double], shape: [2, 4]).astype(.Double), checkType: true)
    }

    func testBoolMask_FullShapeGetOnView() {
        let a = Matft.arange(start: 0.0, to: 12.0, by: 1.0, shape: [3, 4], mftype: .Double)
        let v = a[0~<, Matft.reverse]
        let r = v[v > 6]
        XCTAssertTrue(r.isReal, "r must stay real")
        XCTAssertClose(r, MfArray([7.0, 11.0, 10.0, 9.0, 8.0] as [Double], shape: [5]).astype(.Double), checkType: true)
    }

    func testBoolMask_LeadingAxisSetOnView() {
        let a = Matft.arange(start: 0.0, to: 12.0, by: 1.0, shape: [3, 4], mftype: .Double)
        let v = a.T
        v[MfArray([true, false, false, true])] = MfArray([0.5, 1.5, 2.5] as [Double])
        XCTAssertTrue(a.isReal, "a must stay real")
        XCTAssertClose(a, MfArray([0.5, 1.0, 2.0, 0.5, 1.5, 5.0, 6.0, 1.5, 2.5, 9.0, 10.0, 2.5] as [Double], shape: [3, 4]).astype(.Double), checkType: true)
    }

    func testComplexInit_ImagOnlyOffsetView() {
        let a = Matft.arange(start: 0.0, to: 12.0, by: 1.0, shape: [3, 4], mftype: .Double)
        let z = MfArray(real: nil, imag: a[1~<2])
        XCTAssertTrue(z.isComplex, "z must be complex")
        XCTAssertClose(z.real, MfArray([0.0, 0.0, 0.0, 0.0] as [Double], shape: [1, 4]).astype(.Double), checkType: true)
        XCTAssertClose(z.imag!, MfArray([4.0, 5.0, 6.0, 7.0] as [Double], shape: [1, 4]).astype(.Double), checkType: true)
    }

    func testComplexInit_RealOnlyOffsetView() {
        let a = Matft.arange(start: 0.0, to: 12.0, by: 1.0, shape: [3, 4], mftype: .Double)
        let z = MfArray(real: a[1~<2], imag: nil)
        XCTAssertTrue(z.isComplex, "z must be complex")
        XCTAssertClose(z.real, MfArray([4.0, 5.0, 6.0, 7.0] as [Double], shape: [1, 4]).astype(.Double), checkType: true)
        XCTAssertClose(z.imag!, MfArray([0.0, 0.0, 0.0, 0.0] as [Double], shape: [1, 4]).astype(.Double), checkType: true)
    }

    func testComplexInit_ImagOnlyStridedView() {
        let a = Matft.arange(start: 0.0, to: 12.0, by: 1.0, shape: [3, 4], mftype: .Double)
        let z = MfArray(real: nil, imag: a[0~<, 1~<4~<2])
        XCTAssertTrue(z.isComplex, "z must be complex")
        XCTAssertClose(z.real, MfArray([0.0, 0.0, 0.0, 0.0, 0.0, 0.0] as [Double], shape: [3, 2]).astype(.Double), checkType: true)
        XCTAssertClose(z.imag!, MfArray([1.0, 3.0, 5.0, 7.0, 9.0, 11.0] as [Double], shape: [3, 2]).astype(.Double), checkType: true)
    }

    func testComplexIntoReal_NestedView() {
        let a = Matft.arange(start: 0.0, to: 12.0, by: 1.0, shape: [3, 4], mftype: .Double)
        let v = a[1~<]
        let w = v[0~<, 1~<]
        w[0, 0] = MfArray(real: MfArray([7.5] as [Double]), imag: MfArray([8.0] as [Double]))
        XCTAssertTrue(a.isReal, "a must stay real")
        XCTAssertClose(a, MfArray([0.0, 1.0, 2.0, 3.0, 4.0, 7.5, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0] as [Double], shape: [3, 4]).astype(.Double), checkType: true)
        XCTAssertTrue(v.isReal, "v must stay real")
        XCTAssertClose(v, MfArray([4.0, 7.5, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0] as [Double], shape: [2, 4]).astype(.Double), checkType: true)
        XCTAssertTrue(w.isReal, "w must stay real")
        XCTAssertClose(w, MfArray([7.5, 6.0, 7.0, 9.0, 10.0, 11.0] as [Double], shape: [2, 3]).astype(.Double), checkType: true)
    }

    func testComplexIntoReal_IntArray() {
        let a = MfArray([1, 2, 3])
        a[0] = MfArray(real: MfArray([7.5] as [Double]), imag: MfArray([8.0] as [Double]))
        XCTAssertTrue(a.isReal, "a must stay real")
        XCTAssertClose(a, MfArray([7.0, 2.0, 3.0] as [Double], shape: [3]).astype(.Int), checkType: true)
    }

    func testComplexIntoReal_Slice() {
        let a = Matft.arange(start: 0.0, to: 12.0, by: 1.0, shape: [3, 4], mftype: .Double)
        a[0~<2] = MfArray(real: MfArray([7.5] as [Double]), imag: MfArray([8.0] as [Double]))
        XCTAssertTrue(a.isReal, "a must stay real")
        XCTAssertClose(a, MfArray([7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 8.0, 9.0, 10.0, 11.0] as [Double], shape: [3, 4]).astype(.Double), checkType: true)
    }

    func testComplexIntoReal_BoolMask() {
        let a = Matft.arange(start: 0.0, to: 12.0, by: 1.0, shape: [3, 4], mftype: .Double)
        a[a > 8] = MfArray(real: MfArray([7.5] as [Double]), imag: MfArray([8.0] as [Double]))
        XCTAssertTrue(a.isReal, "a must stay real")
        XCTAssertClose(a, MfArray([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 7.5, 7.5, 7.5] as [Double], shape: [3, 4]).astype(.Double), checkType: true)
    }

    func testComplexIntoReal_Fancy() {
        let a = Matft.arange(start: 0.0, to: 12.0, by: 1.0, shape: [3, 4], mftype: .Double)
        a[MfArray([0, 2])] = MfArray(real: MfArray([7.5] as [Double]), imag: MfArray([8.0] as [Double]))
        XCTAssertTrue(a.isReal, "a must stay real")
        XCTAssertClose(a, MfArray([7.5, 7.5, 7.5, 7.5, 4.0, 5.0, 6.0, 7.0, 7.5, 7.5, 7.5, 7.5] as [Double], shape: [3, 4]).astype(.Double), checkType: true)
    }

    func testComplexIntoReal_FancyAll() {
        let a = Matft.arange(start: 0.0, to: 12.0, by: 1.0, shape: [3, 4], mftype: .Double)
        a[MfArray([0, 2]), MfArray([1, 3])] = MfArray(real: MfArray([7.5] as [Double]), imag: MfArray([8.0] as [Double]))
        XCTAssertTrue(a.isReal, "a must stay real")
        XCTAssertClose(a, MfArray([0.0, 7.5, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 7.5] as [Double], shape: [3, 4]).astype(.Double), checkType: true)
    }

    func testComplexIntoRealPart_OfComplex() {
        let z = MfArray(real: MfArray([1.0, 2.0] as [Double]), imag: MfArray([3.0, 4.0] as [Double]))
        let r = z.real
        r[0] = MfArray(real: MfArray([7.5] as [Double]), imag: MfArray([8.0] as [Double]))
        XCTAssertTrue(z.isComplex, "z must be complex")
        XCTAssertClose(z.real, MfArray([7.5, 2.0] as [Double], shape: [2]).astype(.Double), checkType: true)
        XCTAssertClose(z.imag!, MfArray([3.0, 4.0] as [Double], shape: [2]).astype(.Double), checkType: true)
    }

    func testDeepcopy_DensePermutedNonView() {
        let p = Matft.arange(start: 0.0, to: 24.0, by: 1.0, shape: [2, 3, 4], mftype: .Double).transpose(axes: [0, 2, 1]) + 1
        let c = p.deepcopy()
        p[0, 0, 0] = MfArray([100.0] as [Double])
        XCTAssertTrue(c.isReal, "c must stay real")
        XCTAssertClose(c, MfArray([1.0, 5.0, 9.0, 2.0, 6.0, 10.0, 3.0, 7.0, 11.0, 4.0, 8.0, 12.0, 13.0, 17.0, 21.0, 14.0, 18.0, 22.0, 15.0, 19.0, 23.0, 16.0, 20.0, 24.0] as [Double], shape: [2, 4, 3]).astype(.Double), checkType: true)
        XCTAssertTrue(p.isReal, "p must stay real")
        XCTAssertClose(p, MfArray([100.0, 5.0, 9.0, 2.0, 6.0, 10.0, 3.0, 7.0, 11.0, 4.0, 8.0, 12.0, 13.0, 17.0, 21.0, 14.0, 18.0, 22.0, 15.0, 19.0, 23.0, 16.0, 20.0, 24.0] as [Double], shape: [2, 4, 3]).astype(.Double), checkType: true)
    }
}
