#if canImport(Accelerate) && canImport(ImageIO)
import XCTest

@testable import Matft

/// PIL / transformers compatible preprocessing for vision models.
/// Reference values are generated by python/gen_image_preprocess_fixtures.py (Pillow 12.3, transformers 5.17)
final class ImagePreprocessTest: XCTestCase {

    static let resamples: [(String, MfResample)] = [("nearest", .nearest), ("bilinear", .bilinear), ("bicubic", .bicubic), ("lanczos", .lanczos)]
    /// (width, height): up (non-integer), down, horizontal only, vertical only
    static let sizes: [(Int, Int)] = [(31, 20), (7, 5), (9, 13), (17, 6)]

    func test_smart_resize() {
        // transformers.models.qwen2_vl.image_processing_pil_qwen2_vl.smart_resize
        XCTAssertTrue(Matft.image.smart_resize(height: 225, width: 225) == (224, 224))
        XCTAssertTrue(Matft.image.smart_resize(height: 1080, width: 1920) == (728, 1316))
        XCTAssertTrue(Matft.image.smart_resize(height: 30, width: 40) == (56, 84))
        XCTAssertTrue(Matft.image.smart_resize(height: 4000, width: 3000) == (1148, 840))
        XCTAssertTrue(Matft.image.smart_resize(height: 100, width: 300, factor: 14) == (98, 294))
        XCTAssertTrue(Matft.image.smart_resize(height: 225, width: 225, min_pixels: 28 * 28, max_pixels: 28 * 28 * 4) == (56, 56))
        XCTAssertTrue(Matft.image.smart_resize(height: 50, width: 9000) == (56, 8988))
    }

    func test_resize_pil_uint8() {
        let rgb = _synthetic_image(height: 13, width: 17, channels: 3)
        let gray = _synthetic_image(height: 13, width: 17, channels: 1)[Matft.all, Matft.all, 0]
        XCTAssertEqual(gray.shape, [13, 17])

        for (name, resample) in ImagePreprocessTest.resamples {
            for (w, h) in ImagePreprocessTest.sizes {
                let ret = Matft.image.resize(rgb, width: w, height: h, resample: resample)
                XCTAssertEqual(ret.mftype, .UInt8)
                // np.array(Image.fromarray(rgb).resize((w, h), resample))
                XCTAssertEqual(ret, _load("resize_rgb_\(name)_\(w)x\(h).csv", shape: [h, w, 3]), "rgb \(name) \(w)x\(h)")

                let retg = Matft.image.resize(gray, width: w, height: h, resample: resample)
                XCTAssertEqual(retg, _load("resize_gray_\(name)_\(w)x\(h).csv", shape: [h, w]), "gray \(name) \(w)x\(h)")
            }
        }
        // same size returns a copy
        XCTAssertEqual(Matft.image.resize(rgb, width: 17, height: 13, resample: .bicubic), rgb)
    }

    func test_resize_pil_float() {
        // PIL mode "F"
        let f = _synthetic_image(height: 13, width: 17, channels: 1)[Matft.all, Matft.all, 0].astype(.Float) / Float(255)
        for (name, resample) in ImagePreprocessTest.resamples {
            for (w, h) in ImagePreprocessTest.sizes {
                let ret = Matft.image.resize(f, width: w, height: h, resample: resample)
                XCTAssertEqual(ret.mftype, .Float)
                _assertClose(ret, _load("resize_float_\(name)_\(w)x\(h).csv", shape: [h, w]), rtol: 1e-5, atol: 1e-6)
            }
        }
    }

    func test_resize_pil_rena() {
        let rena = _rena_rgb()
        // decoded values are the same as PIL
        XCTAssertEqual(rena[0, 0], MfArray([224, 138, 121], mftype: .UInt8))

        let bicubic = Matft.image.resize(rena, width: 100, height: 60, resample: .bicubic)
        XCTAssertEqual(bicubic, _load("resize_rena_bicubic_100x60.csv", shape: [60, 100, 3]))
        let bilinear = Matft.image.resize(rena, width: 100, height: 60, resample: .bilinear)
        XCTAssertEqual(bilinear, _load("resize_rena_bilinear_100x60.csv", shape: [60, 100, 3]))

        ImageSnapshot.check(Matft.image.color(bicubic, conversion: .RGB2RGBA), as: "resize_pil_bicubic_100x60")
        let up = Matft.image.resize(rena, width: 300, height: 400, resample: .bicubic)
        ImageSnapshot.check(Matft.image.color(up, conversion: .RGB2RGBA), as: "resize_pil_bicubic_300x400")
    }

    func test_center_crop() {
        // transformers.image_transforms.center_crop(img, size, input_data_format="channels_last")
        let img = _synthetic_image(height: 5, width: 6, channels: 1)
        XCTAssertEqual(Matft.image.center_crop(img, height: 3, width: 4)[Matft.all, Matft.all, 0],
                       MfArray([[129, 167, 205, 243], [221, 4, 43, 82], [57, 97, 137, 177]] as [[Int]], mftype: .UInt8))
        XCTAssertEqual(Matft.image.center_crop(img, height: 4, width: 3)[Matft.all, Matft.all, 0],
                       MfArray([[37, 74, 111], [129, 167, 205], [221, 4, 43], [57, 97, 137]] as [[Int]], mftype: .UInt8))
        // padded with zeros
        XCTAssertEqual(Matft.image.center_crop(img, height: 7, width: 8)[Matft.all, Matft.all, 0],
                       MfArray([[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 37, 74, 111, 148, 185, 0], [0, 91, 129, 167, 205, 243, 25, 0],
                                [0, 182, 221, 4, 43, 82, 121, 0], [0, 17, 57, 97, 137, 177, 217, 0], [0, 108, 149, 190, 231, 16, 57, 0],
                                [0, 0, 0, 0, 0, 0, 0, 0]] as [[Int]], mftype: .UInt8))
        XCTAssertEqual(Matft.image.center_crop(img, height: 2, width: 9)[Matft.all, Matft.all, 0],
                       MfArray([[0, 0, 91, 129, 167, 205, 243, 25, 0], [0, 0, 182, 221, 4, 43, 82, 121, 0]] as [[Int]], mftype: .UInt8))
        XCTAssertEqual(Matft.image.center_crop(img, height: 3, width: 4).mftype, .UInt8)
        // 2d image
        XCTAssertEqual(Matft.image.center_crop(img[Matft.all, Matft.all, 0], height: 3, width: 4).shape, [3, 4])
    }

    func test_rescale_normalize() {
        let img = MfArray([[[0, 128, 255], [10, 20, 30]]] as [[[Int]]], mftype: .UInt8)
        let rescaled = Matft.image.rescale(img, scale: 1.0 / 255)
        XCTAssertEqual(rescaled.mftype, .Float)
        _assertClose(rescaled, MfArray([[[0.0, 0.50196078, 1.0], [0.03921569, 0.07843138, 0.11764706]]]), rtol: 1e-6)

        // (image - mean) / std along the last axis
        let normalized = Matft.image.normalize_meanstd(rescaled, mean: [0.5, 0.25, 0.0], std: [0.5, 0.25, 2.0])
        XCTAssertEqual(normalized.mftype, .Float)
        _assertClose(normalized, MfArray([[[-1.0, 1.00784314, 0.5], [-0.92156863, -0.68627447, 0.05882353]]]), rtol: 1e-6)
        // uint8 is converted to float
        XCTAssertEqual(Matft.image.normalize_meanstd(img, mean: [0, 0, 0], std: [1, 1, 1]).mftype, .Float)
    }

    func test_clip_preprocess() {
        let rena = _rena_rgb()
        do {
            // CLIPImageProcessorPil(size={"shortest_edge": 32}, crop_size={"height": 32, "width": 32})
            let pv = Matft.image.clip_preprocess(rena, size: 32, crop_height: 32, crop_width: 32)
            XCTAssertEqual(pv.shape, [1, 3, 32, 32])
            XCTAssertEqual(pv.mftype, .Float)
            _assertClose(pv, _load("clip_rena_32.csv", shape: [1, 3, 32, 32]), rtol: 1e-5, atol: 1e-6)
        }
        do {
            // non-square input and crop: rena[:150], shortest_edge 24, crop 20x28
            let pv = Matft.image.clip_preprocess(rena[0~<150], size: 24, crop_height: 20, crop_width: 28)
            _assertClose(pv, _load("clip_rena_24_crop20x28.csv", shape: [1, 3, 20, 28]), rtol: 1e-5, atol: 1e-6)
        }
        do {
            // CLIPImageProcessorPil() default
            let pv = Matft.image.clip_preprocess(rena)
            XCTAssertEqual(pv.shape, [1, 3, 224, 224])
            XCTAssertEqual(pv.astype(.Double).sum().scalar(Double.self)!, 28664.38467005419, accuracy: 1e-2)
            _assertClose(pv[0, Matft.all, 0, 0], MfArray([1.4777849912643433, 0.31897497177124023, 0.24040821194648743]), rtol: 1e-6)
            _assertClose(pv[0, Matft.all, 100, 150], MfArray([1.1712180376052856, -0.11625037342309952, 0.1693078875541687]), rtol: 1e-6)
        }
    }

    func test_qwen2vl_preprocess() {
        let rena = _rena_rgb()
        do {
            // Qwen2VLImageProcessorPil(min_pixels=28*28, max_pixels=28*28*4)
            let (pv, grid) = Matft.image.qwen2vl_preprocess(rena, min_pixels: 28 * 28, max_pixels: 28 * 28 * 4)
            XCTAssertTrue(grid == (1, 4, 4))
            XCTAssertEqual(pv.shape, [16, 1176])
            XCTAssertEqual(pv.mftype, .Float)
            _assertClose(pv, _load("qwen2vl_rena_small.csv", shape: [16, 1176]), rtol: 1e-5, atol: 1e-6)
        }
        do {
            // default
            let (pv, grid) = Matft.image.qwen2vl_preprocess(rena)
            XCTAssertTrue(grid == (1, 16, 16))
            XCTAssertEqual(pv.shape, [256, 1176])
            XCTAssertEqual(pv.astype(.Double).sum().scalar(Double.self)!, 57328.76934010838, accuracy: 1e-2)
            _assertClose(pv[0, 0~<4], MfArray([1.4777849912643433, 1.4777849912643433, 1.4777849912643433, 1.463186502456665]), rtol: 1e-6)
            _assertClose(pv[255, MfSlice(start: -3)], MfArray([-0.18619374930858612, -0.21463386714458466, -0.17197367548942566]), rtol: 1e-6)
        }
    }
}

/// Same as `synthetic_image` in python/gen_image_preprocess_fixtures.py
fileprivate func _synthetic_image(height: Int, width: Int, channels: Int) -> MfArray {
    var values: [UInt8] = []
    for y in 0..<height {
        for x in 0..<width {
            for c in 0..<channels {
                values.append(UInt8((x * 37 + y * 91 + c * 53 + (x * y) % 29) % 256))
            }
        }
    }
    return MfArray(values, mftype: .UInt8, shape: [height, width, channels])
}

fileprivate func _rena_rgb() -> MfArray {
    let rgba = Matft.image.cgimage2mfarray(ImageSnapshot.loadFixture(), mftype: .UInt8)
    return rgba[Matft.all, Matft.all, 0~<3].to_contiguous(mforder: .Row)
}

fileprivate func _load(_ name: String, shape: [Int]) -> MfArray {
    let url = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
        .appendingPathComponent("files").appendingPathComponent("image_preprocess").appendingPathComponent(name)
    return Matft.file.loadtxt(url: url, delimiter: ",", mftype: .Double)!.reshape(shape)
}

fileprivate func _assertClose(_ actual: MfArray, _ expected: MfArray, rtol: Double = 1e-6, atol: Double = 1e-8, file: StaticString = #filePath, line: UInt = #line) {
    XCTAssertClose(actual, expected, rtol: rtol, atol: atol, checkType: false, file: file, line: line)
}
#endif
