// Generated by python/gen_indexing_coverage.py (numpy 2.0.2). Do not edit by hand.
import XCTest

import Matft

/// Subscript getters and setters (int, slice, step, all/reverse/newaxis, fancy and boolean indexing) over dtypes, memory layouts (`layoutVariants`) and edge cases. Expected values are numpy outputs
final class IndexingCoverageTests: XCTestCase {
    private let A = MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4])
    private let AF = MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Float, shape: [3, 4])
    private let AI = MfArray([3, -1, 4, 1, 5, 9, -2, 6, 5, 3, 5, 8] as [Int], mftype: .Int, shape: [3, 4])
    private let U8 = MfArray([0, 1, 127, 128, 254, 255, 3, 9, 200, 5, 0, 77] as [Int], mftype: .UInt8, shape: [3, 4])
    private let B = MfArray([true, false, false, true, false, true, true, false, true, true, false, false] as [Bool], shape: [3, 4])
    private let C = MfArray([-12.0, -11.0, -10.0, -9.0, -8.0, -7.0, -6.0, -5.0, -4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0] as [Double], mftype: .Double, shape: [2, 3, 4])
    private let D = MfArray([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0] as [Double], mftype: .Double, shape: [2, 3, 2, 4])
    private let V = MfArray([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0] as [Double], mftype: .Double, shape: [5, 4])

    func test_slicing_layouts() {
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[1] as! MfArray, MfArray([5.0, 9.0, -2.0, 6.0] as [Double], mftype: .Double, shape: [4]), rtol: 0, atol: 0, checkType: true, "x[1] as! MfArray \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[-1] as! MfArray, MfArray([5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [4]), rtol: 0, atol: 0, checkType: true, "x[-1] as! MfArray \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[1~<], MfArray([5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [2, 4]), rtol: 0, atol: 0, checkType: true, "x[1~<] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[~<-1], MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0] as [Double], mftype: .Double, shape: [2, 4]), rtol: 0, atol: 0, checkType: true, "x[~<-1] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[(-2)~<], MfArray([5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [2, 4]), rtol: 0, atol: 0, checkType: true, "x[(-2)~<] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[~<<-1], MfArray([5.0, 3.0, 5.0, 8.0, 5.0, 9.0, -2.0, 6.0, 3.0, -1.0, 4.0, 1.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[~<<-1] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[~<<2], MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [2, 4]), rtol: 0, atol: 0, checkType: true, "x[~<<2] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[1~<3, 1~<], MfArray([9.0, -2.0, 6.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "x[1~<3, 1~<] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[0~<3~<5], MfArray([3.0, -1.0, 4.0, 1.0] as [Double], mftype: .Double, shape: [1, 4]), rtol: 0, atol: 0, checkType: true, "x[0~<3~<5] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[Matft.all, 1~<4~<2], MfArray([-1.0, 1.0, 9.0, 6.0, 3.0, 8.0] as [Double], mftype: .Double, shape: [3, 2]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 1~<4~<2] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[Matft.all, 3~<0~<-1], MfArray([1.0, 4.0, -1.0, 6.0, -2.0, 9.0, 8.0, 5.0, 3.0] as [Double], mftype: .Double, shape: [3, 3]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 3~<0~<-1] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[Matft.all, ~<<-2], MfArray([1.0, -1.0, 6.0, 9.0, 8.0, 3.0] as [Double], mftype: .Double, shape: [3, 2]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, ~<<-2] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[Matft.all, 2~<~<-1], MfArray([4.0, -1.0, 3.0, -2.0, 9.0, 5.0, 5.0, 3.0, 5.0] as [Double], mftype: .Double, shape: [3, 3]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 2~<~<-1] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[Matft.all, (-1)~<~<-3], MfArray([1.0, 3.0, 6.0, 5.0, 8.0, 5.0] as [Double], mftype: .Double, shape: [3, 2]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, (-1)~<~<-3] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[Matft.all, (-2)~<(-4)~<-1], MfArray([4.0, -1.0, -2.0, 9.0, 5.0, 3.0] as [Double], mftype: .Double, shape: [3, 2]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, (-2)~<(-4)~<-1] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[10~<], MfArray([] as [Double], mftype: .Double, shape: [0, 4]), rtol: 0, atol: 0, checkType: true, "x[10~<] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[(-10)~<], MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[(-10)~<] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[~<10], MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[~<10] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[Matft.all, ~<-10], MfArray([] as [Double], mftype: .Double, shape: [3, 0]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, ~<-10] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[Matft.all, 4~<~<-1], MfArray([1.0, 4.0, -1.0, 3.0, 6.0, -2.0, 9.0, 5.0, 8.0, 5.0, 3.0, 5.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 4~<~<-1] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[Matft.all, 10~<~<-1], MfArray([1.0, 4.0, -1.0, 3.0, 6.0, -2.0, 9.0, 5.0, 8.0, 5.0, 3.0, 5.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 10~<~<-1] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[Matft.all, (-10)~<~<-1], MfArray([] as [Double], mftype: .Double, shape: [3, 0]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, (-10)~<~<-1] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[Matft.all, 1~<10~<-1], MfArray([] as [Double], mftype: .Double, shape: [3, 0]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 1~<10~<-1] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[Matft.all, 10~<(-10)~<-2], MfArray([1.0, -1.0, 6.0, 9.0, 8.0, 3.0] as [Double], mftype: .Double, shape: [3, 2]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 10~<(-10)~<-2] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[2~<1], MfArray([] as [Double], mftype: .Double, shape: [0, 4]), rtol: 0, atol: 0, checkType: true, "x[2~<1] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[Matft.reverse], MfArray([5.0, 3.0, 5.0, 8.0, 5.0, 9.0, -2.0, 6.0, 3.0, -1.0, 4.0, 1.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.reverse] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[Matft.all, Matft.reverse], MfArray([1.0, 4.0, -1.0, 3.0, 6.0, -2.0, 9.0, 5.0, 8.0, 5.0, 3.0, 5.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, Matft.reverse] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[Matft.newaxis], MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [1, 3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.newaxis] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[Matft.all, Matft.newaxis, 1~<], MfArray([-1.0, 4.0, 1.0, 9.0, -2.0, 6.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 1, 3]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, Matft.newaxis, 1~<] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[Matft.newaxis, 2, ~<<-1], MfArray([8.0, 5.0, 3.0, 5.0] as [Double], mftype: .Double, shape: [1, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.newaxis, 2, ~<<-1] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[1, Matft.newaxis], MfArray([5.0, 9.0, -2.0, 6.0] as [Double], mftype: .Double, shape: [1, 4]), rtol: 0, atol: 0, checkType: true, "x[1, Matft.newaxis] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[1, ~<<2], MfArray([5.0, -2.0] as [Double], mftype: .Double, shape: [2]), rtol: 0, atol: 0, checkType: true, "x[1, ~<<2] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[Matft.all, -1], MfArray([1.0, 6.0, 8.0] as [Double], mftype: .Double, shape: [3]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, -1] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[1~<, 2], MfArray([-2.0, 5.0] as [Double], mftype: .Double, shape: [2]), rtol: 0, atol: 0, checkType: true, "x[1~<, 2] \(name)")
        }
    }

    func test_slicing_dtypes() {
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(x[1] as! MfArray, MfArray([5.0, 9.0, -2.0, 6.0] as [Double], mftype: .Float, shape: [4]), rtol: 0, atol: 0, checkType: true, "x[1] as! MfArray \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(x[~<<-1], MfArray([5.0, 3.0, 5.0, 8.0, 5.0, 9.0, -2.0, 6.0, 3.0, -1.0, 4.0, 1.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[~<<-1] \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(x[1~<3, 1~<], MfArray([9.0, -2.0, 6.0, 3.0, 5.0, 8.0] as [Double], mftype: .Float, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "x[1~<3, 1~<] \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(x[Matft.all, 3~<0~<-1], MfArray([1.0, 4.0, -1.0, 6.0, -2.0, 9.0, 8.0, 5.0, 3.0] as [Double], mftype: .Float, shape: [3, 3]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 3~<0~<-1] \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(x[Matft.all, 10~<~<-1], MfArray([1.0, 4.0, -1.0, 3.0, 6.0, -2.0, 9.0, 5.0, 8.0, 5.0, 3.0, 5.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 10~<~<-1] \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(x[Matft.all, Matft.reverse], MfArray([1.0, 4.0, -1.0, 3.0, 6.0, -2.0, 9.0, 5.0, 8.0, 5.0, 3.0, 5.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, Matft.reverse] \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(x[Matft.all, Matft.newaxis, 1~<], MfArray([-1.0, 4.0, 1.0, 9.0, -2.0, 6.0, 3.0, 5.0, 8.0] as [Double], mftype: .Float, shape: [3, 1, 3]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, Matft.newaxis, 1~<] \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertClose(x[1] as! MfArray, MfArray([5, 9, -2, 6] as [Int], mftype: .Int, shape: [4]), rtol: 0, atol: 0, checkType: true, "x[1] as! MfArray \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertClose(x[~<<-1], MfArray([5, 3, 5, 8, 5, 9, -2, 6, 3, -1, 4, 1] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[~<<-1] \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertClose(x[1~<3, 1~<], MfArray([9, -2, 6, 3, 5, 8] as [Int], mftype: .Int, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "x[1~<3, 1~<] \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertClose(x[Matft.all, 3~<0~<-1], MfArray([1, 4, -1, 6, -2, 9, 8, 5, 3] as [Int], mftype: .Int, shape: [3, 3]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 3~<0~<-1] \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertClose(x[Matft.all, 10~<~<-1], MfArray([1, 4, -1, 3, 6, -2, 9, 5, 8, 5, 3, 5] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 10~<~<-1] \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertClose(x[Matft.all, Matft.reverse], MfArray([1, 4, -1, 3, 6, -2, 9, 5, 8, 5, 3, 5] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, Matft.reverse] \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertClose(x[Matft.all, Matft.newaxis, 1~<], MfArray([-1, 4, 1, 9, -2, 6, 3, 5, 8] as [Int], mftype: .Int, shape: [3, 1, 3]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, Matft.newaxis, 1~<] \(name)")
        }
        for (name, x) in layoutVariants(U8){
            XCTAssertClose(x[1] as! MfArray, MfArray([254, 255, 3, 9] as [Int], mftype: .UInt8, shape: [4]), rtol: 0, atol: 0, checkType: true, "x[1] as! MfArray \(name)")
        }
        for (name, x) in layoutVariants(U8){
            XCTAssertClose(x[~<<-1], MfArray([200, 5, 0, 77, 254, 255, 3, 9, 0, 1, 127, 128] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[~<<-1] \(name)")
        }
        for (name, x) in layoutVariants(U8){
            XCTAssertClose(x[1~<3, 1~<], MfArray([255, 3, 9, 5, 0, 77] as [Int], mftype: .UInt8, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "x[1~<3, 1~<] \(name)")
        }
        for (name, x) in layoutVariants(U8){
            XCTAssertClose(x[Matft.all, 3~<0~<-1], MfArray([128, 127, 1, 9, 3, 255, 77, 0, 5] as [Int], mftype: .UInt8, shape: [3, 3]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 3~<0~<-1] \(name)")
        }
        for (name, x) in layoutVariants(U8){
            XCTAssertClose(x[Matft.all, 10~<~<-1], MfArray([128, 127, 1, 0, 9, 3, 255, 254, 77, 0, 5, 200] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 10~<~<-1] \(name)")
        }
        for (name, x) in layoutVariants(U8){
            XCTAssertClose(x[Matft.all, Matft.reverse], MfArray([128, 127, 1, 0, 9, 3, 255, 254, 77, 0, 5, 200] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, Matft.reverse] \(name)")
        }
        for (name, x) in layoutVariants(U8){
            XCTAssertClose(x[Matft.all, Matft.newaxis, 1~<], MfArray([1, 127, 128, 255, 3, 9, 5, 0, 77] as [Int], mftype: .UInt8, shape: [3, 1, 3]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, Matft.newaxis, 1~<] \(name)")
        }
        for (name, x) in layoutVariants(B){
            XCTAssertClose(x[1] as! MfArray, MfArray([false, true, true, false] as [Bool], shape: [4]), rtol: 0, atol: 0, checkType: true, "x[1] as! MfArray \(name)")
        }
        for (name, x) in layoutVariants(B){
            XCTAssertClose(x[~<<-1], MfArray([true, true, false, false, false, true, true, false, true, false, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[~<<-1] \(name)")
        }
        for (name, x) in layoutVariants(B){
            XCTAssertClose(x[1~<3, 1~<], MfArray([true, true, false, true, false, false] as [Bool], shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "x[1~<3, 1~<] \(name)")
        }
        for (name, x) in layoutVariants(B){
            XCTAssertClose(x[Matft.all, 3~<0~<-1], MfArray([true, false, false, false, true, true, false, false, true] as [Bool], shape: [3, 3]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 3~<0~<-1] \(name)")
        }
        for (name, x) in layoutVariants(B){
            XCTAssertClose(x[Matft.all, 10~<~<-1], MfArray([true, false, false, true, false, true, true, false, false, false, true, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 10~<~<-1] \(name)")
        }
        for (name, x) in layoutVariants(B){
            XCTAssertClose(x[Matft.all, Matft.reverse], MfArray([true, false, false, true, false, true, true, false, false, false, true, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, Matft.reverse] \(name)")
        }
        for (name, x) in layoutVariants(B){
            XCTAssertClose(x[Matft.all, Matft.newaxis, 1~<], MfArray([false, false, true, true, true, false, true, false, false] as [Bool], shape: [3, 1, 3]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, Matft.newaxis, 1~<] \(name)")
        }
    }

    func test_slicing_3d() {
        for (name, x) in layoutVariants(C){
            XCTAssertClose(x[1] as! MfArray, MfArray([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[1] as! MfArray \(name)")
        }
        for (name, x) in layoutVariants(C){
            XCTAssertClose(x[-1, 1] as! MfArray, MfArray([4.0, 5.0, 6.0, 7.0] as [Double], mftype: .Double, shape: [4]), rtol: 0, atol: 0, checkType: true, "x[-1, 1] as! MfArray \(name)")
        }
        for (name, x) in layoutVariants(C){
            XCTAssertClose(x[Matft.all, 1, Matft.reverse], MfArray([-5.0, -6.0, -7.0, -8.0, 7.0, 6.0, 5.0, 4.0] as [Double], mftype: .Double, shape: [2, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 1, Matft.reverse] \(name)")
        }
        for (name, x) in layoutVariants(C){
            XCTAssertClose(x[Matft.all, Matft.all, 1~<3], MfArray([-11.0, -10.0, -7.0, -6.0, -3.0, -2.0, 1.0, 2.0, 5.0, 6.0, 9.0, 10.0] as [Double], mftype: .Double, shape: [2, 3, 2]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, Matft.all, 1~<3] \(name)")
        }
        for (name, x) in layoutVariants(C){
            XCTAssertClose(x[-1, ~<<-1, 0], MfArray([8.0, 4.0, 0.0] as [Double], mftype: .Double, shape: [3]), rtol: 0, atol: 0, checkType: true, "x[-1, ~<<-1, 0] \(name)")
        }
        for (name, x) in layoutVariants(C){
            XCTAssertClose(x[Matft.reverse, Matft.newaxis, ~<<2, (-1)~<~<-2], MfArray([3.0, 1.0, 11.0, 9.0, -9.0, -11.0, -1.0, -3.0] as [Double], mftype: .Double, shape: [2, 1, 2, 2]), rtol: 0, atol: 0, checkType: true, "x[Matft.reverse, Matft.newaxis, ~<<2, (-1)~<~<-2] \(name)")
        }
        for (name, x) in layoutVariants(C){
            XCTAssertClose(x[Matft.all, 5~<], MfArray([] as [Double], mftype: .Double, shape: [2, 0, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 5~<] \(name)")
        }
    }

    func test_scalar_getter() {
        XCTAssertEqual(A[1, -1] as! Double, 6.0)
        XCTAssertEqual(AF[-1, 0] as! Float, 5.0)
        XCTAssertEqual(AI[0, -3] as! Int, -1)
        XCTAssertEqual(C[1, -1, 2] as! Double, 10.0)
    }

    func test_fancy_getter() {
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[MfArray([2, 0, -1, 0] as [Int], mftype: .Int, shape: [4])], MfArray([5.0, 3.0, 5.0, 8.0, 3.0, -1.0, 4.0, 1.0, 5.0, 3.0, 5.0, 8.0, 3.0, -1.0, 4.0, 1.0] as [Double], mftype: .Double, shape: [4, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([2, 0, -1, 0] as [Int], mftype: .Int, shape: [4])] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[MfArray([1, 0, 2, 2] as [Int], mftype: .Int, shape: [2, 2])], MfArray([5.0, 9.0, -2.0, 6.0, 3.0, -1.0, 4.0, 1.0, 5.0, 3.0, 5.0, 8.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [2, 2, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([1, 0, 2, 2] as [Int], mftype: .Int, shape: [2, 2])] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[Matft.all, MfArray([3, 0, -1] as [Int], mftype: .Int, shape: [3])], MfArray([1.0, 3.0, 1.0, 6.0, 5.0, 6.0, 8.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 3]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, MfArray([3, 0, -1] as [Int], mftype: .Int, shape: [3])] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, -1] as [Int], mftype: .Int, shape: [2])], MfArray([-1.0, 8.0] as [Double], mftype: .Double, shape: [2]), rtol: 0, atol: 0, checkType: true, "x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, -1] as [Int], mftype: .Int, shape: [2])] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2, 1]), MfArray([1, 3, 0] as [Int], mftype: .Int, shape: [3])], MfArray([-1.0, 1.0, 3.0, 3.0, 8.0, 5.0] as [Double], mftype: .Double, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2, 1]), MfArray([1, 3, 0] as [Int], mftype: .Int, shape: [3])] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[MfArray([2, 0] as [Int], mftype: .Int, shape: [2]), 1~<3], MfArray([3.0, 5.0, -1.0, 4.0] as [Double], mftype: .Double, shape: [2, 2]), rtol: 0, atol: 0, checkType: true, "x[MfArray([2, 0] as [Int], mftype: .Int, shape: [2]), 1~<3] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[1~<, MfArray([3, 1] as [Int], mftype: .Int, shape: [2])], MfArray([6.0, 9.0, 8.0, 3.0] as [Double], mftype: .Double, shape: [2, 2]), rtol: 0, atol: 0, checkType: true, "x[1~<, MfArray([3, 1] as [Int], mftype: .Int, shape: [2])] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[~<<-1, MfArray([3, 1] as [Int], mftype: .Int, shape: [2])], MfArray([8.0, 3.0, 6.0, 9.0, 1.0, -1.0] as [Double], mftype: .Double, shape: [3, 2]), rtol: 0, atol: 0, checkType: true, "x[~<<-1, MfArray([3, 1] as [Int], mftype: .Int, shape: [2])] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[Matft.newaxis, MfArray([2, 0] as [Int], mftype: .Int, shape: [2])], MfArray([5.0, 3.0, 5.0, 8.0, 3.0, -1.0, 4.0, 1.0] as [Double], mftype: .Double, shape: [1, 2, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.newaxis, MfArray([2, 0] as [Int], mftype: .Int, shape: [2])] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[MfArray([] as [Int], mftype: .Int, shape: [0])], MfArray([] as [Double], mftype: .Double, shape: [0, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([] as [Int], mftype: .Int, shape: [0])] \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(x[MfArray([2, 0, -1, 0] as [Int], mftype: .Int, shape: [4])], MfArray([5.0, 3.0, 5.0, 8.0, 3.0, -1.0, 4.0, 1.0, 5.0, 3.0, 5.0, 8.0, 3.0, -1.0, 4.0, 1.0] as [Double], mftype: .Float, shape: [4, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([2, 0, -1, 0] as [Int], mftype: .Int, shape: [4])] \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(x[Matft.all, MfArray([3, 0, -1] as [Int], mftype: .Int, shape: [3])], MfArray([1.0, 3.0, 1.0, 6.0, 5.0, 6.0, 8.0, 5.0, 8.0] as [Double], mftype: .Float, shape: [3, 3]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, MfArray([3, 0, -1] as [Int], mftype: .Int, shape: [3])] \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, -1] as [Int], mftype: .Int, shape: [2])], MfArray([-1.0, 8.0] as [Double], mftype: .Float, shape: [2]), rtol: 0, atol: 0, checkType: true, "x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, -1] as [Int], mftype: .Int, shape: [2])] \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertClose(x[MfArray([2, 0, -1, 0] as [Int], mftype: .Int, shape: [4])], MfArray([5, 3, 5, 8, 3, -1, 4, 1, 5, 3, 5, 8, 3, -1, 4, 1] as [Int], mftype: .Int, shape: [4, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([2, 0, -1, 0] as [Int], mftype: .Int, shape: [4])] \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertClose(x[Matft.all, MfArray([3, 0, -1] as [Int], mftype: .Int, shape: [3])], MfArray([1, 3, 1, 6, 5, 6, 8, 5, 8] as [Int], mftype: .Int, shape: [3, 3]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, MfArray([3, 0, -1] as [Int], mftype: .Int, shape: [3])] \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertClose(x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, -1] as [Int], mftype: .Int, shape: [2])], MfArray([-1, 8] as [Int], mftype: .Int, shape: [2]), rtol: 0, atol: 0, checkType: true, "x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, -1] as [Int], mftype: .Int, shape: [2])] \(name)")
        }
        for (name, x) in layoutVariants(U8){
            XCTAssertClose(x[MfArray([2, 0, -1, 0] as [Int], mftype: .Int, shape: [4])], MfArray([200, 5, 0, 77, 0, 1, 127, 128, 200, 5, 0, 77, 0, 1, 127, 128] as [Int], mftype: .UInt8, shape: [4, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([2, 0, -1, 0] as [Int], mftype: .Int, shape: [4])] \(name)")
        }
        for (name, x) in layoutVariants(U8){
            XCTAssertClose(x[Matft.all, MfArray([3, 0, -1] as [Int], mftype: .Int, shape: [3])], MfArray([128, 0, 128, 9, 254, 9, 77, 200, 77] as [Int], mftype: .UInt8, shape: [3, 3]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, MfArray([3, 0, -1] as [Int], mftype: .Int, shape: [3])] \(name)")
        }
        for (name, x) in layoutVariants(U8){
            XCTAssertClose(x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, -1] as [Int], mftype: .Int, shape: [2])], MfArray([1, 77] as [Int], mftype: .UInt8, shape: [2]), rtol: 0, atol: 0, checkType: true, "x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, -1] as [Int], mftype: .Int, shape: [2])] \(name)")
        }
        for (name, x) in layoutVariants(B){
            XCTAssertClose(x[MfArray([2, 0, -1, 0] as [Int], mftype: .Int, shape: [4])], MfArray([true, true, false, false, true, false, false, true, true, true, false, false, true, false, false, true] as [Bool], shape: [4, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([2, 0, -1, 0] as [Int], mftype: .Int, shape: [4])] \(name)")
        }
        for (name, x) in layoutVariants(B){
            XCTAssertClose(x[Matft.all, MfArray([3, 0, -1] as [Int], mftype: .Int, shape: [3])], MfArray([true, true, true, false, false, false, false, true, false] as [Bool], shape: [3, 3]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, MfArray([3, 0, -1] as [Int], mftype: .Int, shape: [3])] \(name)")
        }
        for (name, x) in layoutVariants(B){
            XCTAssertClose(x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, -1] as [Int], mftype: .Int, shape: [2])], MfArray([false, false] as [Bool], shape: [2]), rtol: 0, atol: 0, checkType: true, "x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, -1] as [Int], mftype: .Int, shape: [2])] \(name)")
        }
    }

    func test_fancy_getter_nd() {
        for (name, x) in layoutVariants(C){
            XCTAssertClose(x[MfArray([1, 0, 1] as [Int], mftype: .Int, shape: [3])], MfArray([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, -12.0, -11.0, -10.0, -9.0, -8.0, -7.0, -6.0, -5.0, -4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0] as [Double], mftype: .Double, shape: [3, 3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([1, 0, 1] as [Int], mftype: .Int, shape: [3])] \(name)")
        }
        for (name, x) in layoutVariants(C){
            XCTAssertClose(x[Matft.all, MfArray([2, 0] as [Int], mftype: .Int, shape: [2])], MfArray([-4.0, -3.0, -2.0, -1.0, -12.0, -11.0, -10.0, -9.0, 8.0, 9.0, 10.0, 11.0, 0.0, 1.0, 2.0, 3.0] as [Double], mftype: .Double, shape: [2, 2, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, MfArray([2, 0] as [Int], mftype: .Int, shape: [2])] \(name)")
        }
        for (name, x) in layoutVariants(C){
            XCTAssertClose(x[Matft.all, MfArray([2, 0] as [Int], mftype: .Int, shape: [2]), MfArray([1, 3] as [Int], mftype: .Int, shape: [2])], MfArray([-3.0, -9.0, 9.0, 3.0] as [Double], mftype: .Double, shape: [2, 2]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, MfArray([2, 0] as [Int], mftype: .Int, shape: [2]), MfArray([1, 3] as [Int], mftype: .Int, shape: [2])] \(name)")
        }
        for (name, x) in layoutVariants(C){
            XCTAssertClose(x[MfArray([1, 0] as [Int], mftype: .Int, shape: [2]), Matft.all, MfArray([3, 3] as [Int], mftype: .Int, shape: [2])], MfArray([3.0, 7.0, 11.0, -9.0, -5.0, -1.0] as [Double], mftype: .Double, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "x[MfArray([1, 0] as [Int], mftype: .Int, shape: [2]), Matft.all, MfArray([3, 3] as [Int], mftype: .Int, shape: [2])] \(name)")
        }
        for (name, x) in layoutVariants(C){
            XCTAssertClose(x[Matft.all, Matft.all, MfArray([-1, 0] as [Int], mftype: .Int, shape: [2, 1])], MfArray([-9.0, -12.0, -5.0, -8.0, -1.0, -4.0, 3.0, 0.0, 7.0, 4.0, 11.0, 8.0] as [Double], mftype: .Double, shape: [2, 3, 2, 1]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, Matft.all, MfArray([-1, 0] as [Int], mftype: .Int, shape: [2, 1])] \(name)")
        }
        for (name, x) in layoutVariants(C){
            XCTAssertClose(x[Matft.all, MfArray([2, 0] as [Int], mftype: .Int, shape: [2, 1]), MfArray([1, 3, 0] as [Int], mftype: .Int, shape: [3])], MfArray([-3.0, -1.0, -4.0, -11.0, -9.0, -12.0, 9.0, 11.0, 8.0, 1.0, 3.0, 0.0] as [Double], mftype: .Double, shape: [2, 2, 3]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, MfArray([2, 0] as [Int], mftype: .Int, shape: [2, 1]), MfArray([1, 3, 0] as [Int], mftype: .Int, shape: [3])] \(name)")
        }
        for (name, x) in layoutVariants(C){
            XCTAssertClose(x[Matft.all, 1, MfArray([0, 2] as [Int], mftype: .Int, shape: [2])], MfArray([-8.0, -6.0, 4.0, 6.0] as [Double], mftype: .Double, shape: [2, 2]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 1, MfArray([0, 2] as [Int], mftype: .Int, shape: [2])] \(name)")
        }
        for (name, x) in layoutVariants(C){
            XCTAssertClose(x[1, Matft.all, MfArray([0, 2] as [Int], mftype: .Int, shape: [2])], MfArray([0.0, 4.0, 8.0, 2.0, 6.0, 10.0] as [Double], mftype: .Double, shape: [2, 3]), rtol: 0, atol: 0, checkType: true, "x[1, Matft.all, MfArray([0, 2] as [Int], mftype: .Int, shape: [2])] \(name)")
        }
        for (name, x) in layoutVariants(D){
            XCTAssertClose(x[Matft.all, MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), Matft.all, MfArray([1, 3] as [Int], mftype: .Int, shape: [2])], MfArray([1.0, 5.0, 25.0, 29.0, 19.0, 23.0, 43.0, 47.0] as [Double], mftype: .Double, shape: [2, 2, 2]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), Matft.all, MfArray([1, 3] as [Int], mftype: .Int, shape: [2])] \(name)")
        }
        for (name, x) in layoutVariants(D){
            XCTAssertClose(x[Matft.all, MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, 0] as [Int], mftype: .Int, shape: [2])], MfArray([4.0, 5.0, 6.0, 7.0, 16.0, 17.0, 18.0, 19.0, 28.0, 29.0, 30.0, 31.0, 40.0, 41.0, 42.0, 43.0] as [Double], mftype: .Double, shape: [2, 2, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, 0] as [Int], mftype: .Int, shape: [2])] \(name)")
        }
    }

    func test_bool_getter() {
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[x > 3], MfArray([4.0, 5.0, 9.0, 6.0, 5.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [7]), rtol: 0, atol: 0, checkType: true, "x[x > 3] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[x > 1000], MfArray([] as [Double], mftype: .Double, shape: [0]), rtol: 0, atol: 0, checkType: true, "x[x > 1000] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[x >= 0], MfArray([3.0, 4.0, 1.0, 5.0, 9.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [10]), rtol: 0, atol: 0, checkType: true, "x[x >= 0] \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(x[MfArray([true, false, true])], MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [2, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([true, false, true])] \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(x[x > 3], MfArray([4.0, 5.0, 9.0, 6.0, 5.0, 5.0, 8.0] as [Double], mftype: .Float, shape: [7]), rtol: 0, atol: 0, checkType: true, "x[x > 3] \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(x[x > 1000], MfArray([] as [Double], mftype: .Float, shape: [0]), rtol: 0, atol: 0, checkType: true, "x[x > 1000] \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(x[x >= 0], MfArray([3.0, 4.0, 1.0, 5.0, 9.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Float, shape: [10]), rtol: 0, atol: 0, checkType: true, "x[x >= 0] \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(x[MfArray([true, false, true])], MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Float, shape: [2, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([true, false, true])] \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertClose(x[x > 3], MfArray([4, 5, 9, 6, 5, 5, 8] as [Int], mftype: .Int, shape: [7]), rtol: 0, atol: 0, checkType: true, "x[x > 3] \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertClose(x[x > 1000], MfArray([] as [Int], mftype: .Int, shape: [0]), rtol: 0, atol: 0, checkType: true, "x[x > 1000] \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertClose(x[x >= 0], MfArray([3, 4, 1, 5, 9, 6, 5, 3, 5, 8] as [Int], mftype: .Int, shape: [10]), rtol: 0, atol: 0, checkType: true, "x[x >= 0] \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertClose(x[MfArray([true, false, true])], MfArray([3, -1, 4, 1, 5, 3, 5, 8] as [Int], mftype: .Int, shape: [2, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([true, false, true])] \(name)")
        }
        for (name, x) in layoutVariants(U8){
            XCTAssertClose(x[x > 3], MfArray([127, 128, 254, 255, 9, 200, 5, 77] as [Int], mftype: .UInt8, shape: [8]), rtol: 0, atol: 0, checkType: true, "x[x > 3] \(name)")
        }
        for (name, x) in layoutVariants(U8){
            XCTAssertClose(x[x > 1000], MfArray([] as [Int], mftype: .UInt8, shape: [0]), rtol: 0, atol: 0, checkType: true, "x[x > 1000] \(name)")
        }
        for (name, x) in layoutVariants(U8){
            XCTAssertClose(x[x >= 0], MfArray([0, 1, 127, 128, 254, 255, 3, 9, 200, 5, 0, 77] as [Int], mftype: .UInt8, shape: [12]), rtol: 0, atol: 0, checkType: true, "x[x >= 0] \(name)")
        }
        for (name, x) in layoutVariants(U8){
            XCTAssertClose(x[MfArray([true, false, true])], MfArray([0, 1, 127, 128, 200, 5, 0, 77] as [Int], mftype: .UInt8, shape: [2, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([true, false, true])] \(name)")
        }
        for (name, x) in layoutVariants(B){
            XCTAssertClose(x[x], MfArray([true, true, true, true, true, true] as [Bool], shape: [6]), rtol: 0, atol: 0, checkType: true, "x[x] \(name)")
        }
        for (name, x) in layoutVariants(C){
            XCTAssertClose(x[MfArray([true, false, false, true, false, false] as [Bool], shape: [2, 3])], MfArray([-12.0, -11.0, -10.0, -9.0, 0.0, 1.0, 2.0, 3.0] as [Double], mftype: .Double, shape: [2, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([true, false, false, true, false, false] as [Bool], shape: [2, 3])] \(name)")
        }
    }

    func test_slice_setter() {
        for (name, x) in layoutVariants(A){
            x[1] = MfArray([100])
            XCTAssertClose(x, MfArray([3.0, -1.0, 4.0, 1.0, 100.0, 100.0, 100.0, 100.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[1] = MfArray([100]) \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[-1] = MfArray([10, 20, 30, 40])
            XCTAssertClose(x, MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 10.0, 20.0, 30.0, 40.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[-1] = MfArray([10, 20, 30, 40]) \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[Matft.all, 1] = MfArray([7, 8, 9])
            XCTAssertClose(x, MfArray([3.0, 7.0, 4.0, 1.0, 5.0, 8.0, -2.0, 6.0, 5.0, 9.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 1] = MfArray([7, 8, 9]) \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[Matft.all, 1~<2] = MfArray([7, 8, 9] as [Int], mftype: .Int, shape: [3, 1])
            XCTAssertClose(x, MfArray([3.0, 7.0, 4.0, 1.0, 5.0, 8.0, -2.0, 6.0, 5.0, 9.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 1~<2] = MfArray([7, 8, 9] as [Int], mftype: .Int, shape: [3, 1]) \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[1~<3, 1~<] = MfArray([10, 20, 30, 40, 50, 60] as [Int], mftype: .Int, shape: [2, 3])
            XCTAssertClose(x, MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 10.0, 20.0, 30.0, 5.0, 40.0, 50.0, 60.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[1~<3, 1~<] = MfArray([10, 20, 30, 40, 50, 60] as [Int], mftype: .Int, shape: [2, 3]) \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[1~<, ~<<2] = MfArray([1, 2])
            XCTAssertClose(x, MfArray([3.0, -1.0, 4.0, 1.0, 1.0, 9.0, 2.0, 6.0, 1.0, 3.0, 2.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[1~<, ~<<2] = MfArray([1, 2]) \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[~<<-1, 3~<0~<-2] = MfArray([1, 2, 3, 4, 5, 6] as [Int], mftype: .Int, shape: [3, 2])
            XCTAssertClose(x, MfArray([3.0, 6.0, 4.0, 5.0, 5.0, 4.0, -2.0, 3.0, 5.0, 2.0, 5.0, 1.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[~<<-1, 3~<0~<-2] = MfArray([1, 2, 3, 4, 5, 6] as [Int], mftype: .Int, shape: [3, 2]) \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[Matft.reverse] = MfArray([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] as [Int], mftype: .Int, shape: [3, 4])
            XCTAssertClose(x, MfArray([8.0, 9.0, 10.0, 11.0, 4.0, 5.0, 6.0, 7.0, 0.0, 1.0, 2.0, 3.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.reverse] = MfArray([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] as [Int], mftype: .Int, shape: [3, 4]) \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[Matft.all, 10~<~<-1] = MfArray([77])
            XCTAssertClose(x, MfArray([77.0, 77.0, 77.0, 77.0, 77.0, 77.0, 77.0, 77.0, 77.0, 77.0, 77.0, 77.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 10~<~<-1] = MfArray([77]) \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[2~<1] = MfArray([55])
            XCTAssertClose(x, MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[2~<1] = MfArray([55]) \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[Matft.all, 1~<10~<-1] = MfArray([55])
            XCTAssertClose(x, MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 1~<10~<-1] = MfArray([55]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[1] = MfArray([100])
            XCTAssertClose(x, MfArray([3.0, -1.0, 4.0, 1.0, 100.0, 100.0, 100.0, 100.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[1] = MfArray([100]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[-1] = MfArray([10, 20, 30, 40])
            XCTAssertClose(x, MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 10.0, 20.0, 30.0, 40.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[-1] = MfArray([10, 20, 30, 40]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[Matft.all, 1] = MfArray([7, 8, 9])
            XCTAssertClose(x, MfArray([3.0, 7.0, 4.0, 1.0, 5.0, 8.0, -2.0, 6.0, 5.0, 9.0, 5.0, 8.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 1] = MfArray([7, 8, 9]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[Matft.all, 1~<2] = MfArray([7, 8, 9] as [Int], mftype: .Int, shape: [3, 1])
            XCTAssertClose(x, MfArray([3.0, 7.0, 4.0, 1.0, 5.0, 8.0, -2.0, 6.0, 5.0, 9.0, 5.0, 8.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 1~<2] = MfArray([7, 8, 9] as [Int], mftype: .Int, shape: [3, 1]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[1~<3, 1~<] = MfArray([10, 20, 30, 40, 50, 60] as [Int], mftype: .Int, shape: [2, 3])
            XCTAssertClose(x, MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 10.0, 20.0, 30.0, 5.0, 40.0, 50.0, 60.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[1~<3, 1~<] = MfArray([10, 20, 30, 40, 50, 60] as [Int], mftype: .Int, shape: [2, 3]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[1~<, ~<<2] = MfArray([1, 2])
            XCTAssertClose(x, MfArray([3.0, -1.0, 4.0, 1.0, 1.0, 9.0, 2.0, 6.0, 1.0, 3.0, 2.0, 8.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[1~<, ~<<2] = MfArray([1, 2]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[~<<-1, 3~<0~<-2] = MfArray([1, 2, 3, 4, 5, 6] as [Int], mftype: .Int, shape: [3, 2])
            XCTAssertClose(x, MfArray([3.0, 6.0, 4.0, 5.0, 5.0, 4.0, -2.0, 3.0, 5.0, 2.0, 5.0, 1.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[~<<-1, 3~<0~<-2] = MfArray([1, 2, 3, 4, 5, 6] as [Int], mftype: .Int, shape: [3, 2]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[Matft.reverse] = MfArray([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] as [Int], mftype: .Int, shape: [3, 4])
            XCTAssertClose(x, MfArray([8.0, 9.0, 10.0, 11.0, 4.0, 5.0, 6.0, 7.0, 0.0, 1.0, 2.0, 3.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.reverse] = MfArray([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] as [Int], mftype: .Int, shape: [3, 4]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[Matft.all, 10~<~<-1] = MfArray([77])
            XCTAssertClose(x, MfArray([77.0, 77.0, 77.0, 77.0, 77.0, 77.0, 77.0, 77.0, 77.0, 77.0, 77.0, 77.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 10~<~<-1] = MfArray([77]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[2~<1] = MfArray([55])
            XCTAssertClose(x, MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[2~<1] = MfArray([55]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[Matft.all, 1~<10~<-1] = MfArray([55])
            XCTAssertClose(x, MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 1~<10~<-1] = MfArray([55]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[1] = MfArray([100])
            XCTAssertClose(x, MfArray([3, -1, 4, 1, 100, 100, 100, 100, 5, 3, 5, 8] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[1] = MfArray([100]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[-1] = MfArray([10, 20, 30, 40])
            XCTAssertClose(x, MfArray([3, -1, 4, 1, 5, 9, -2, 6, 10, 20, 30, 40] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[-1] = MfArray([10, 20, 30, 40]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[Matft.all, 1] = MfArray([7, 8, 9])
            XCTAssertClose(x, MfArray([3, 7, 4, 1, 5, 8, -2, 6, 5, 9, 5, 8] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 1] = MfArray([7, 8, 9]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[Matft.all, 1~<2] = MfArray([7, 8, 9] as [Int], mftype: .Int, shape: [3, 1])
            XCTAssertClose(x, MfArray([3, 7, 4, 1, 5, 8, -2, 6, 5, 9, 5, 8] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 1~<2] = MfArray([7, 8, 9] as [Int], mftype: .Int, shape: [3, 1]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[1~<3, 1~<] = MfArray([10, 20, 30, 40, 50, 60] as [Int], mftype: .Int, shape: [2, 3])
            XCTAssertClose(x, MfArray([3, -1, 4, 1, 5, 10, 20, 30, 5, 40, 50, 60] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[1~<3, 1~<] = MfArray([10, 20, 30, 40, 50, 60] as [Int], mftype: .Int, shape: [2, 3]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[1~<, ~<<2] = MfArray([1, 2])
            XCTAssertClose(x, MfArray([3, -1, 4, 1, 1, 9, 2, 6, 1, 3, 2, 8] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[1~<, ~<<2] = MfArray([1, 2]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[~<<-1, 3~<0~<-2] = MfArray([1, 2, 3, 4, 5, 6] as [Int], mftype: .Int, shape: [3, 2])
            XCTAssertClose(x, MfArray([3, 6, 4, 5, 5, 4, -2, 3, 5, 2, 5, 1] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[~<<-1, 3~<0~<-2] = MfArray([1, 2, 3, 4, 5, 6] as [Int], mftype: .Int, shape: [3, 2]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[Matft.reverse] = MfArray([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] as [Int], mftype: .Int, shape: [3, 4])
            XCTAssertClose(x, MfArray([8, 9, 10, 11, 4, 5, 6, 7, 0, 1, 2, 3] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.reverse] = MfArray([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] as [Int], mftype: .Int, shape: [3, 4]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[Matft.all, 10~<~<-1] = MfArray([77])
            XCTAssertClose(x, MfArray([77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 10~<~<-1] = MfArray([77]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[2~<1] = MfArray([55])
            XCTAssertClose(x, MfArray([3, -1, 4, 1, 5, 9, -2, 6, 5, 3, 5, 8] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[2~<1] = MfArray([55]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[Matft.all, 1~<10~<-1] = MfArray([55])
            XCTAssertClose(x, MfArray([3, -1, 4, 1, 5, 9, -2, 6, 5, 3, 5, 8] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 1~<10~<-1] = MfArray([55]) \(name)")
        }
        for (name, x) in layoutVariants(U8){
            x[1] = MfArray([100])
            XCTAssertClose(x, MfArray([0, 1, 127, 128, 100, 100, 100, 100, 200, 5, 0, 77] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[1] = MfArray([100]) \(name)")
        }
        for (name, x) in layoutVariants(U8){
            x[-1] = MfArray([10, 20, 30, 40])
            XCTAssertClose(x, MfArray([0, 1, 127, 128, 254, 255, 3, 9, 10, 20, 30, 40] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[-1] = MfArray([10, 20, 30, 40]) \(name)")
        }
        for (name, x) in layoutVariants(U8){
            x[Matft.all, 1] = MfArray([7, 8, 9])
            XCTAssertClose(x, MfArray([0, 7, 127, 128, 254, 8, 3, 9, 200, 9, 0, 77] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 1] = MfArray([7, 8, 9]) \(name)")
        }
        for (name, x) in layoutVariants(U8){
            x[Matft.all, 1~<2] = MfArray([7, 8, 9] as [Int], mftype: .Int, shape: [3, 1])
            XCTAssertClose(x, MfArray([0, 7, 127, 128, 254, 8, 3, 9, 200, 9, 0, 77] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 1~<2] = MfArray([7, 8, 9] as [Int], mftype: .Int, shape: [3, 1]) \(name)")
        }
        for (name, x) in layoutVariants(U8){
            x[1~<3, 1~<] = MfArray([10, 20, 30, 40, 50, 60] as [Int], mftype: .Int, shape: [2, 3])
            XCTAssertClose(x, MfArray([0, 1, 127, 128, 254, 10, 20, 30, 200, 40, 50, 60] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[1~<3, 1~<] = MfArray([10, 20, 30, 40, 50, 60] as [Int], mftype: .Int, shape: [2, 3]) \(name)")
        }
        for (name, x) in layoutVariants(U8){
            x[1~<, ~<<2] = MfArray([1, 2])
            XCTAssertClose(x, MfArray([0, 1, 127, 128, 1, 255, 2, 9, 1, 5, 2, 77] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[1~<, ~<<2] = MfArray([1, 2]) \(name)")
        }
        for (name, x) in layoutVariants(U8){
            x[~<<-1, 3~<0~<-2] = MfArray([1, 2, 3, 4, 5, 6] as [Int], mftype: .Int, shape: [3, 2])
            XCTAssertClose(x, MfArray([0, 6, 127, 5, 254, 4, 3, 3, 200, 2, 0, 1] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[~<<-1, 3~<0~<-2] = MfArray([1, 2, 3, 4, 5, 6] as [Int], mftype: .Int, shape: [3, 2]) \(name)")
        }
        for (name, x) in layoutVariants(U8){
            x[Matft.reverse] = MfArray([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] as [Int], mftype: .Int, shape: [3, 4])
            XCTAssertClose(x, MfArray([8, 9, 10, 11, 4, 5, 6, 7, 0, 1, 2, 3] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.reverse] = MfArray([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] as [Int], mftype: .Int, shape: [3, 4]) \(name)")
        }
        for (name, x) in layoutVariants(U8){
            x[Matft.all, 10~<~<-1] = MfArray([77])
            XCTAssertClose(x, MfArray([77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 10~<~<-1] = MfArray([77]) \(name)")
        }
        for (name, x) in layoutVariants(U8){
            x[2~<1] = MfArray([55])
            XCTAssertClose(x, MfArray([0, 1, 127, 128, 254, 255, 3, 9, 200, 5, 0, 77] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[2~<1] = MfArray([55]) \(name)")
        }
        for (name, x) in layoutVariants(U8){
            x[Matft.all, 1~<10~<-1] = MfArray([55])
            XCTAssertClose(x, MfArray([0, 1, 127, 128, 254, 255, 3, 9, 200, 5, 0, 77] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 1~<10~<-1] = MfArray([55]) \(name)")
        }
        for (name, x) in layoutVariants(B){
            x[1] = MfArray([true])
            XCTAssertClose(x, MfArray([true, false, false, true, true, true, true, true, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[1] = MfArray([true]) \(name)")
        }
        for (name, x) in layoutVariants(B){
            x[Matft.all, 1~<3] = MfArray([false, true])
            XCTAssertClose(x, MfArray([true, false, true, true, false, false, true, false, true, false, true, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 1~<3] = MfArray([false, true]) \(name)")
        }
        for (name, x) in layoutVariants(B){
            x[~<<-1, ~<<-2] = MfArray([true])
            XCTAssertClose(x, MfArray([true, true, false, true, false, true, true, true, true, true, false, true] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[~<<-1, ~<<-2] = MfArray([true]) \(name)")
        }
    }

    func test_slice_setter_3d() {
        for (name, x) in layoutVariants(C){
            x[Matft.all, 1, Matft.reverse] = MfArray([1, 2, 3, 4])
            XCTAssertClose(x, MfArray([-12.0, -11.0, -10.0, -9.0, 4.0, 3.0, 2.0, 1.0, -4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 3.0, 2.0, 1.0, 8.0, 9.0, 10.0, 11.0] as [Double], mftype: .Double, shape: [2, 3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 1, Matft.reverse] = MfArray([1, 2, 3, 4]) \(name)")
        }
        for (name, x) in layoutVariants(C){
            x[-1, ~<<2] = MfArray([100])
            XCTAssertClose(x, MfArray([-12.0, -11.0, -10.0, -9.0, -8.0, -7.0, -6.0, -5.0, -4.0, -3.0, -2.0, -1.0, 100.0, 100.0, 100.0, 100.0, 4.0, 5.0, 6.0, 7.0, 100.0, 100.0, 100.0, 100.0] as [Double], mftype: .Double, shape: [2, 3, 4]), rtol: 0, atol: 0, checkType: true, "x[-1, ~<<2] = MfArray([100]) \(name)")
        }
        for (name, x) in layoutVariants(C){
            x[Matft.all, Matft.all, 1~<3] = MfArray([-1, -2, -3] as [Int], mftype: .Int, shape: [3, 1])
            XCTAssertClose(x, MfArray([-12.0, -1.0, -1.0, -9.0, -8.0, -2.0, -2.0, -5.0, -4.0, -3.0, -3.0, -1.0, 0.0, -1.0, -1.0, 3.0, 4.0, -2.0, -2.0, 7.0, 8.0, -3.0, -3.0, 11.0] as [Double], mftype: .Double, shape: [2, 3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, Matft.all, 1~<3] = MfArray([-1, -2, -3] as [Int], mftype: .Int, shape: [3, 1]) \(name)")
        }
    }

    func test_setter_dtype_conversion() {
        for (name, x) in layoutVariants(AI){
            x[0] = MfArray([2.7, -2.7, 0.5, -0.5] as [Double])
            XCTAssertClose(x, MfArray([2, -2, 0, 0, 5, 9, -2, 6, 5, 3, 5, 8] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[0] = MfArray([2.7, -2.7, 0.5, -0.5] as [Double]) \(name)")
        }
        for (name, x) in layoutVariants(U8){
            x[0] = MfArray([300, -1, 256, 255] as [Int])
            XCTAssertClose(x, MfArray([44, 255, 0, 255, 254, 255, 3, 9, 200, 5, 0, 77] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[0] = MfArray([300, -1, 256, 255] as [Int]) \(name)")
        }
        for (name, x) in layoutVariants(U8){
            x[x > 100] = MfArray([300] as [Int])
            XCTAssertClose(x, MfArray([0, 1, 44, 44, 44, 44, 3, 9, 44, 5, 0, 77] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[x > 100] = MfArray([300] as [Int]) \(name)")
        }
        for (name, x) in layoutVariants(U8){
            x[MfArray([2, 0] as [Int], mftype: .Int, shape: [2])] = MfArray([-2] as [Int])
            XCTAssertClose(x, MfArray([254, 254, 254, 254, 254, 255, 3, 9, 254, 254, 254, 254] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([2, 0] as [Int], mftype: .Int, shape: [2])] = MfArray([-2] as [Int]) \(name)")
        }
        for (name, x) in layoutVariants(B){
            x[0] = MfArray([0.0, 2.5, -1, 0] as [Double])
            XCTAssertClose(x, MfArray([false, true, true, false, false, true, true, false, true, true, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[0] = MfArray([0.0, 2.5, -1, 0] as [Double]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[1, 1~<3] = MfArray([0.1, -1e-3] as [Double])
            XCTAssertClose(x, MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 0.10000000149011612, -0.0010000000474974513, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[1, 1~<3] = MfArray([0.1, -1e-3] as [Double]) \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[Matft.all, 0] = MfArray([true, false, true])
            XCTAssertClose(x, MfArray([1.0, -1.0, 4.0, 1.0, 0.0, 9.0, -2.0, 6.0, 1.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 0] = MfArray([true, false, true]) \(name)")
        }
    }

    func test_bool_setter() {
        for (name, x) in layoutVariants(A){
            x[x > 3] = MfArray([0])
            XCTAssertClose(x, MfArray([3.0, -1.0, 0.0, 1.0, 0.0, 0.0, -2.0, 0.0, 0.0, 3.0, 0.0, 0.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[x > 3] = MfArray([0]) \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[x > 1000] = MfArray([7])
            XCTAssertClose(x, MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[x > 1000] = MfArray([7]) \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[x >= 0] = MfArray([2])
            XCTAssertClose(x, MfArray([2.0, -1.0, 2.0, 2.0, 2.0, 2.0, -2.0, 2.0, 2.0, 2.0, 2.0, 2.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[x >= 0] = MfArray([2]) \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[x > 3] = MfArray([10, 20, 30, 40, 50, 60, 70] as [Int], mftype: .Int, shape: [7])
            XCTAssertClose(x, MfArray([3.0, -1.0, 10.0, 1.0, 20.0, 30.0, -2.0, 40.0, 50.0, 3.0, 60.0, 70.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[x > 3] = MfArray([10, 20, 30, 40, 50, 60, 70] as [Int], mftype: .Int, shape: [7]) \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[MfArray([true, false, true])] = MfArray([1, 2, 3, 4])
            XCTAssertClose(x, MfArray([1.0, 2.0, 3.0, 4.0, 5.0, 9.0, -2.0, 6.0, 1.0, 2.0, 3.0, 4.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([true, false, true])] = MfArray([1, 2, 3, 4]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[x > 3] = MfArray([0])
            XCTAssertClose(x, MfArray([3.0, -1.0, 0.0, 1.0, 0.0, 0.0, -2.0, 0.0, 0.0, 3.0, 0.0, 0.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[x > 3] = MfArray([0]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[x > 1000] = MfArray([7])
            XCTAssertClose(x, MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[x > 1000] = MfArray([7]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[x >= 0] = MfArray([2])
            XCTAssertClose(x, MfArray([2.0, -1.0, 2.0, 2.0, 2.0, 2.0, -2.0, 2.0, 2.0, 2.0, 2.0, 2.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[x >= 0] = MfArray([2]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[x > 3] = MfArray([10, 20, 30, 40, 50, 60, 70] as [Int], mftype: .Int, shape: [7])
            XCTAssertClose(x, MfArray([3.0, -1.0, 10.0, 1.0, 20.0, 30.0, -2.0, 40.0, 50.0, 3.0, 60.0, 70.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[x > 3] = MfArray([10, 20, 30, 40, 50, 60, 70] as [Int], mftype: .Int, shape: [7]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[MfArray([true, false, true])] = MfArray([1, 2, 3, 4])
            XCTAssertClose(x, MfArray([1.0, 2.0, 3.0, 4.0, 5.0, 9.0, -2.0, 6.0, 1.0, 2.0, 3.0, 4.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([true, false, true])] = MfArray([1, 2, 3, 4]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[x > 3] = MfArray([0])
            XCTAssertClose(x, MfArray([3, -1, 0, 1, 0, 0, -2, 0, 0, 3, 0, 0] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[x > 3] = MfArray([0]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[x > 1000] = MfArray([7])
            XCTAssertClose(x, MfArray([3, -1, 4, 1, 5, 9, -2, 6, 5, 3, 5, 8] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[x > 1000] = MfArray([7]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[x >= 0] = MfArray([2])
            XCTAssertClose(x, MfArray([2, -1, 2, 2, 2, 2, -2, 2, 2, 2, 2, 2] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[x >= 0] = MfArray([2]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[x > 3] = MfArray([10, 20, 30, 40, 50, 60, 70] as [Int], mftype: .Int, shape: [7])
            XCTAssertClose(x, MfArray([3, -1, 10, 1, 20, 30, -2, 40, 50, 3, 60, 70] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[x > 3] = MfArray([10, 20, 30, 40, 50, 60, 70] as [Int], mftype: .Int, shape: [7]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[MfArray([true, false, true])] = MfArray([1, 2, 3, 4])
            XCTAssertClose(x, MfArray([1, 2, 3, 4, 5, 9, -2, 6, 1, 2, 3, 4] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([true, false, true])] = MfArray([1, 2, 3, 4]) \(name)")
        }
        for (name, x) in layoutVariants(U8){
            x[x > 3] = MfArray([0])
            XCTAssertClose(x, MfArray([0, 1, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[x > 3] = MfArray([0]) \(name)")
        }
        for (name, x) in layoutVariants(U8){
            x[x > 1000] = MfArray([7])
            XCTAssertClose(x, MfArray([0, 1, 127, 128, 254, 255, 3, 9, 200, 5, 0, 77] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[x > 1000] = MfArray([7]) \(name)")
        }
        for (name, x) in layoutVariants(U8){
            x[x >= 0] = MfArray([2])
            XCTAssertClose(x, MfArray([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[x >= 0] = MfArray([2]) \(name)")
        }
        for (name, x) in layoutVariants(U8){
            x[x > 3] = MfArray([10, 20, 30, 40, 50, 60, 70, 80] as [Int], mftype: .Int, shape: [8])
            XCTAssertClose(x, MfArray([0, 1, 10, 20, 30, 40, 3, 50, 60, 70, 0, 80] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[x > 3] = MfArray([10, 20, 30, 40, 50, 60, 70, 80] as [Int], mftype: .Int, shape: [8]) \(name)")
        }
        for (name, x) in layoutVariants(U8){
            x[MfArray([true, false, true])] = MfArray([1, 2, 3, 4])
            XCTAssertClose(x, MfArray([1, 2, 3, 4, 254, 255, 3, 9, 1, 2, 3, 4] as [Int], mftype: .UInt8, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([true, false, true])] = MfArray([1, 2, 3, 4]) \(name)")
        }
        for (name, x) in layoutVariants(B){
            x[x] = MfArray([false])
            XCTAssertClose(x, MfArray([false, false, false, false, false, false, false, false, false, false, false, false] as [Bool], shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[x] = MfArray([false]) \(name)")
        }
        for (name, x) in layoutVariants(C){
            x[MfArray([true, false, false, true, false, false] as [Bool], shape: [2, 3])] = MfArray([-7])
            XCTAssertClose(x, MfArray([-7.0, -7.0, -7.0, -7.0, -8.0, -7.0, -6.0, -5.0, -4.0, -3.0, -2.0, -1.0, -7.0, -7.0, -7.0, -7.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0] as [Double], mftype: .Double, shape: [2, 3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([true, false, false, true, false, false] as [Bool], shape: [2, 3])] = MfArray([-7]) \(name)")
        }
    }

    func test_fancy_setter() {
        for (name, x) in layoutVariants(A){
            x[MfArray([2, 0] as [Int], mftype: .Int, shape: [2])] = MfArray([-5])
            XCTAssertClose(x, MfArray([-5.0, -5.0, -5.0, -5.0, 5.0, 9.0, -2.0, 6.0, -5.0, -5.0, -5.0, -5.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([2, 0] as [Int], mftype: .Int, shape: [2])] = MfArray([-5]) \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[MfArray([-1, 1] as [Int], mftype: .Int, shape: [2])] = MfArray([1, 2, 3, 4, 5, 6, 7, 8] as [Int], mftype: .Int, shape: [2, 4])
            XCTAssertClose(x, MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 6.0, 7.0, 8.0, 1.0, 2.0, 3.0, 4.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([-1, 1] as [Int], mftype: .Int, shape: [2])] = MfArray([1, 2, 3, 4, 5, 6, 7, 8] as [Int], mftype: .Int, shape: [2, 4]) \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[MfArray([0, 0] as [Int], mftype: .Int, shape: [2])] = MfArray([1, 2, 3, 4, 5, 6, 7, 8] as [Int], mftype: .Int, shape: [2, 4])
            XCTAssertClose(x, MfArray([5.0, 6.0, 7.0, 8.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([0, 0] as [Int], mftype: .Int, shape: [2])] = MfArray([1, 2, 3, 4, 5, 6, 7, 8] as [Int], mftype: .Int, shape: [2, 4]) \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, -1] as [Int], mftype: .Int, shape: [2])] = MfArray([100, 200])
            XCTAssertClose(x, MfArray([3.0, 100.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 200.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, -1] as [Int], mftype: .Int, shape: [2])] = MfArray([100, 200]) \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2, 1]), MfArray([1, 3] as [Int], mftype: .Int, shape: [2])] = MfArray([9])
            XCTAssertClose(x, MfArray([3.0, 9.0, 4.0, 9.0, 5.0, 9.0, -2.0, 6.0, 5.0, 9.0, 5.0, 9.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2, 1]), MfArray([1, 3] as [Int], mftype: .Int, shape: [2])] = MfArray([9]) \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[MfArray([] as [Int], mftype: .Int, shape: [0])] = MfArray([9])
            XCTAssertClose(x, MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([] as [Int], mftype: .Int, shape: [0])] = MfArray([9]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[MfArray([2, 0] as [Int], mftype: .Int, shape: [2])] = MfArray([-5])
            XCTAssertClose(x, MfArray([-5.0, -5.0, -5.0, -5.0, 5.0, 9.0, -2.0, 6.0, -5.0, -5.0, -5.0, -5.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([2, 0] as [Int], mftype: .Int, shape: [2])] = MfArray([-5]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[MfArray([-1, 1] as [Int], mftype: .Int, shape: [2])] = MfArray([1, 2, 3, 4, 5, 6, 7, 8] as [Int], mftype: .Int, shape: [2, 4])
            XCTAssertClose(x, MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 6.0, 7.0, 8.0, 1.0, 2.0, 3.0, 4.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([-1, 1] as [Int], mftype: .Int, shape: [2])] = MfArray([1, 2, 3, 4, 5, 6, 7, 8] as [Int], mftype: .Int, shape: [2, 4]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[MfArray([0, 0] as [Int], mftype: .Int, shape: [2])] = MfArray([1, 2, 3, 4, 5, 6, 7, 8] as [Int], mftype: .Int, shape: [2, 4])
            XCTAssertClose(x, MfArray([5.0, 6.0, 7.0, 8.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([0, 0] as [Int], mftype: .Int, shape: [2])] = MfArray([1, 2, 3, 4, 5, 6, 7, 8] as [Int], mftype: .Int, shape: [2, 4]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, -1] as [Int], mftype: .Int, shape: [2])] = MfArray([100, 200])
            XCTAssertClose(x, MfArray([3.0, 100.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 200.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, -1] as [Int], mftype: .Int, shape: [2])] = MfArray([100, 200]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2, 1]), MfArray([1, 3] as [Int], mftype: .Int, shape: [2])] = MfArray([9])
            XCTAssertClose(x, MfArray([3.0, 9.0, 4.0, 9.0, 5.0, 9.0, -2.0, 6.0, 5.0, 9.0, 5.0, 9.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2, 1]), MfArray([1, 3] as [Int], mftype: .Int, shape: [2])] = MfArray([9]) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            x[MfArray([] as [Int], mftype: .Int, shape: [0])] = MfArray([9])
            XCTAssertClose(x, MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([] as [Int], mftype: .Int, shape: [0])] = MfArray([9]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[MfArray([2, 0] as [Int], mftype: .Int, shape: [2])] = MfArray([-5])
            XCTAssertClose(x, MfArray([-5, -5, -5, -5, 5, 9, -2, 6, -5, -5, -5, -5] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([2, 0] as [Int], mftype: .Int, shape: [2])] = MfArray([-5]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[MfArray([-1, 1] as [Int], mftype: .Int, shape: [2])] = MfArray([1, 2, 3, 4, 5, 6, 7, 8] as [Int], mftype: .Int, shape: [2, 4])
            XCTAssertClose(x, MfArray([3, -1, 4, 1, 5, 6, 7, 8, 1, 2, 3, 4] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([-1, 1] as [Int], mftype: .Int, shape: [2])] = MfArray([1, 2, 3, 4, 5, 6, 7, 8] as [Int], mftype: .Int, shape: [2, 4]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[MfArray([0, 0] as [Int], mftype: .Int, shape: [2])] = MfArray([1, 2, 3, 4, 5, 6, 7, 8] as [Int], mftype: .Int, shape: [2, 4])
            XCTAssertClose(x, MfArray([5, 6, 7, 8, 5, 9, -2, 6, 5, 3, 5, 8] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([0, 0] as [Int], mftype: .Int, shape: [2])] = MfArray([1, 2, 3, 4, 5, 6, 7, 8] as [Int], mftype: .Int, shape: [2, 4]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, -1] as [Int], mftype: .Int, shape: [2])] = MfArray([100, 200])
            XCTAssertClose(x, MfArray([3, 100, 4, 1, 5, 9, -2, 6, 5, 3, 5, 200] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, -1] as [Int], mftype: .Int, shape: [2])] = MfArray([100, 200]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2, 1]), MfArray([1, 3] as [Int], mftype: .Int, shape: [2])] = MfArray([9])
            XCTAssertClose(x, MfArray([3, 9, 4, 9, 5, 9, -2, 6, 5, 9, 5, 9] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([0, 2] as [Int], mftype: .Int, shape: [2, 1]), MfArray([1, 3] as [Int], mftype: .Int, shape: [2])] = MfArray([9]) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            x[MfArray([] as [Int], mftype: .Int, shape: [0])] = MfArray([9])
            XCTAssertClose(x, MfArray([3, -1, 4, 1, 5, 9, -2, 6, 5, 3, 5, 8] as [Int], mftype: .Int, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([] as [Int], mftype: .Int, shape: [0])] = MfArray([9]) \(name)")
        }
    }

    func test_fancy_setter_mixed() {
        for (name, x) in layoutVariants(A){
            x[Matft.all, MfArray([3, 0] as [Int], mftype: .Int, shape: [2])] = MfArray([-1, -2])
            XCTAssertClose(x, MfArray([-2.0, -1.0, 4.0, -1.0, -2.0, 9.0, -2.0, -1.0, -2.0, 3.0, 5.0, -1.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, MfArray([3, 0] as [Int], mftype: .Int, shape: [2])] = MfArray([-1, -2]) \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[1~<, MfArray([2] as [Int], mftype: .Int, shape: [1])] = MfArray([50])
            XCTAssertClose(x, MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, 50.0, 6.0, 5.0, 3.0, 50.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[1~<, MfArray([2] as [Int], mftype: .Int, shape: [1])] = MfArray([50]) \(name)")
        }
        for (name, x) in layoutVariants(C){
            x[Matft.all, MfArray([2, 0] as [Int], mftype: .Int, shape: [2])] = MfArray([100])
            XCTAssertClose(x, MfArray([100.0, 100.0, 100.0, 100.0, -8.0, -7.0, -6.0, -5.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 4.0, 5.0, 6.0, 7.0, 100.0, 100.0, 100.0, 100.0] as [Double], mftype: .Double, shape: [2, 3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, MfArray([2, 0] as [Int], mftype: .Int, shape: [2])] = MfArray([100]) \(name)")
        }
    }

    func test_setter_self_aliasing() {
        for (name, x) in layoutVariants(A){
            x[~<<-1] = x
            XCTAssertClose(x, MfArray([5.0, 3.0, 5.0, 8.0, 5.0, 9.0, -2.0, 6.0, 3.0, -1.0, 4.0, 1.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[~<<-1] = x \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[1~<3] = x[0~<2]
            XCTAssertClose(x, MfArray([3.0, -1.0, 4.0, 1.0, 3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[1~<3] = x[0~<2] \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[0~<2] = x[1~<3]
            XCTAssertClose(x, MfArray([5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[0~<2] = x[1~<3] \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[Matft.all, 1~<] = x[Matft.all, ~<-1]
            XCTAssertClose(x, MfArray([3.0, 3.0, -1.0, 4.0, 5.0, 5.0, 9.0, -2.0, 5.0, 5.0, 3.0, 5.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, 1~<] = x[Matft.all, ~<-1] \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[Matft.all, ~<3] = x[Matft.all, 1~<]
            XCTAssertClose(x, MfArray([-1.0, 4.0, 1.0, 1.0, 9.0, -2.0, 6.0, 6.0, 3.0, 5.0, 8.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[Matft.all, ~<3] = x[Matft.all, 1~<] \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[MfArray([2, 0, 1] as [Int], mftype: .Int, shape: [3])] = x
            XCTAssertClose(x, MfArray([5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0, 3.0, -1.0, 4.0, 1.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[MfArray([2, 0, 1] as [Int], mftype: .Int, shape: [3])] = x \(name)")
        }
        for (name, x) in layoutVariants(A){
            x[x > 3] = x[x > 3] * 2
            XCTAssertClose(x, MfArray([3.0, -1.0, 8.0, 1.0, 10.0, 18.0, -2.0, 12.0, 10.0, 3.0, 10.0, 16.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "x[x > 3] = x[x > 3] * 2 \(name)")
        }
    }

    func test_views_and_copies() {
        do {
            let base = V.deepcopy()
            let r = base[1~<3]
            r[0, 0] = MfArray([77])
            XCTAssertClose(base, MfArray([0.0, 1.0, 2.0, 3.0, 77.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0] as [Double], mftype: .Double, shape: [5, 4]), rtol: 0, atol: 0, checkType: true, "let r = base[1~<3] ; r[0, 0] = MfArray([77])")
        }
        do {
            let base = V.deepcopy()
            let r = base[1] as! MfArray
            r[Matft.reverse] = MfArray([1, 2, 3, 4])
            XCTAssertClose(base, MfArray([0.0, 1.0, 2.0, 3.0, 4.0, 3.0, 2.0, 1.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0] as [Double], mftype: .Double, shape: [5, 4]), rtol: 0, atol: 0, checkType: true, "let r = base[1] as! MfArray ; r[Matft.reverse] = MfArray([1, 2, 3, 4])")
        }
        do {
            let base = V.deepcopy()
            let r = base[Matft.newaxis]
            r[0, 2, 1] = MfArray([77])
            XCTAssertClose(base, MfArray([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 77.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0] as [Double], mftype: .Double, shape: [5, 4]), rtol: 0, atol: 0, checkType: true, "let r = base[Matft.newaxis] ; r[0, 2, 1] = MfArray([77])")
        }
        do {
            let base = V.deepcopy()
            let r = base.T
            r[1~<3] = MfArray([-1])
            XCTAssertClose(base, MfArray([0.0, -1.0, -1.0, 3.0, 4.0, -1.0, -1.0, 7.0, 8.0, -1.0, -1.0, 11.0, 12.0, -1.0, -1.0, 15.0, 16.0, -1.0, -1.0, 19.0] as [Double], mftype: .Double, shape: [5, 4]), rtol: 0, atol: 0, checkType: true, "let r = base.T ; r[1~<3] = MfArray([-1])")
        }
        do {
            let base = V.deepcopy()
            let r = base[1~<4, ~<<-1]
            r[r > 10] = MfArray([0])
            XCTAssertClose(base, MfArray([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 0.0, 0.0, 0.0, 0.0, 0.0, 16.0, 17.0, 18.0, 19.0] as [Double], mftype: .Double, shape: [5, 4]), rtol: 0, atol: 0, checkType: true, "let r = base[1~<4, ~<<-1] ; r[r > 10] = MfArray([0])")
        }
        do {
            let base = V.deepcopy()
            let r = base[~<<2]
            r[MfArray([1] as [Int], mftype: .Int, shape: [1])] = MfArray([-3])
            XCTAssertClose(base, MfArray([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, -3.0, -3.0, -3.0, -3.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0] as [Double], mftype: .Double, shape: [5, 4]), rtol: 0, atol: 0, checkType: true, "let r = base[~<<2] ; r[MfArray([1] as [Int], mftype: .Int, shape: [1])] = MfArray([-3])")
        }
        do {
            let base = V.deepcopy()
            let r = base[1~<4]
            r[Matft.all, 1~<3] = r[Matft.all, 0~<2]
            XCTAssertClose(base, MfArray([0.0, 1.0, 2.0, 3.0, 4.0, 4.0, 5.0, 7.0, 8.0, 8.0, 9.0, 11.0, 12.0, 12.0, 13.0, 15.0, 16.0, 17.0, 18.0, 19.0] as [Double], mftype: .Double, shape: [5, 4]), rtol: 0, atol: 0, checkType: true, "let r = base[1~<4] ; r[Matft.all, 1~<3] = r[Matft.all, 0~<2]")
        }
        do {
            let base = V.deepcopy()
            let r = base[MfArray([1, 2] as [Int], mftype: .Int, shape: [2])]
            r[0, 0] = MfArray([77])
            XCTAssertClose(base, MfArray([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0] as [Double], mftype: .Double, shape: [5, 4]), rtol: 0, atol: 0, checkType: true, "let r = base[MfArray([1, 2] as [Int], mftype: .Int, shape: [2])] ; r[0, 0] = MfArray([77])")
        }
        do {
            let base = V.deepcopy()
            let r = base[Matft.all, MfArray([1, 2] as [Int], mftype: .Int, shape: [2])]
            r[0, 0] = MfArray([77])
            XCTAssertClose(base, MfArray([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0] as [Double], mftype: .Double, shape: [5, 4]), rtol: 0, atol: 0, checkType: true, "let r = base[Matft.all, MfArray([1, 2] as [Int], mftype: .Int, shape: [2])] ; r[0, 0] = MfArray([77])")
        }
        do {
            let base = V.deepcopy()
            let r = base[base > 5]
            r[0] = MfArray([77])
            XCTAssertClose(base, MfArray([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0] as [Double], mftype: .Double, shape: [5, 4]), rtol: 0, atol: 0, checkType: true, "let r = base[base > 5] ; r[0] = MfArray([77])")
        }
        do {
            let base = V.deepcopy()
            _ = base[~<<-1, MfArray([0, 3] as [Int], mftype: .Int, shape: [2])]
            _ = base[base > 3]
            _ = base[1~<, ~<<-2]
            XCTAssertClose(base, MfArray([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0] as [Double], mftype: .Double, shape: [5, 4]), rtol: 0, atol: 0, checkType: true, "_ = base[~<<-1, MfArray([0, 3] as [Int], mftype: .Int, shape: [2])] ; _ = base[base > 3] ; _ = base[1~<, ~<<-2]")
        }
    }

    func test_complex_slicing_mask() {
        do {
            let r = MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]))[1~<, ~<<-1]
            XCTAssertClose(r.real, MfArray([6.0, -2.0, 9.0, 5.0, 8.0, 5.0, 3.0, 5.0] as [Double], mftype: .Double, shape: [2, 4]), rtol: 0, atol: 0, checkType: true, "real MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]))[1~<, ~<<-1]")
            XCTAssertClose(r.imag!, MfArray([-11.0, 5.0, -17.0, -9.0, -15.0, -9.0, -5.0, -9.0] as [Double], mftype: .Double, shape: [2, 4]), rtol: 0, atol: 0, checkType: true, "imag MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]))[1~<, ~<<-1]")
        }
        do {
            let r = MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4])).T[Matft.all, 2~<0~<-1]
            XCTAssertClose(r.real, MfArray([5.0, 5.0, 3.0, 9.0, 5.0, -2.0, 8.0, 6.0] as [Double], mftype: .Double, shape: [4, 2]), rtol: 0, atol: 0, checkType: true, "real MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4])).T[Matft.all, 2~<0~<-1]")
            XCTAssertClose(r.imag!, MfArray([-9.0, -9.0, -5.0, -17.0, -9.0, 5.0, -15.0, -11.0] as [Double], mftype: .Double, shape: [4, 2]), rtol: 0, atol: 0, checkType: true, "imag MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4])).T[Matft.all, 2~<0~<-1]")
        }
        do {
            let r = MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]))[Matft.newaxis, -1]
            XCTAssertClose(r.real, MfArray([5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [1, 4]), rtol: 0, atol: 0, checkType: true, "real MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]))[Matft.newaxis, -1]")
            XCTAssertClose(r.imag!, MfArray([-9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [1, 4]), rtol: 0, atol: 0, checkType: true, "imag MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]))[Matft.newaxis, -1]")
        }
        do {
            let z = MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]))
            z[1~<, 1~<3] = MfArray([1, 2])
            let r = z
            XCTAssertClose(r.real, MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 1.0, 2.0, 6.0, 5.0, 1.0, 2.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "real z")
            XCTAssertClose(r.imag!, MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, 0.0, 0.0, -11.0, -9.0, 0.0, 0.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "imag z")
        }
        do {
            let z = MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]))
            z[~<<-1, 0] = MfArray(real: MfArray([1.5, 2.5, 3.5] as [Double]), imag: MfArray([-1, -2, -3] as [Double]))
            let r = z
            XCTAssertClose(r.real, MfArray([3.5, -1.0, 4.0, 1.0, 2.5, 9.0, -2.0, 6.0, 1.5, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "real z")
            XCTAssertClose(r.imag!, MfArray([-3.0, 3.0, -7.0, -1.0, -2.0, -17.0, 5.0, -11.0, -1.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "imag z")
        }
        do {
            let z = MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]))
            z[z.real > 3] = MfArray(real: MfArray([0.5] as [Double]), imag: MfArray([9] as [Double]))
            let r = z
            XCTAssertClose(r.real, MfArray([3.0, -1.0, 0.5, 1.0, 0.5, 0.5, -2.0, 0.5, 0.5, 3.0, 0.5, 0.5] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "real z")
            XCTAssertClose(r.imag!, MfArray([-5.0, 3.0, 9.0, -1.0, 9.0, 9.0, 5.0, 9.0, 9.0, -5.0, 9.0, 9.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "imag z")
        }
    }

    #if !os(WASI)
    func test_complex_fancy() {
        do {
            let r = MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]))[MfArray([2, 0, -1] as [Int], mftype: .Int, shape: [3])]
            XCTAssertClose(r.real, MfArray([5.0, 3.0, 5.0, 8.0, 3.0, -1.0, 4.0, 1.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "real MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]))[MfArray([2, 0, -1] as [Int], mftype: .Int, shape: [3])]")
            XCTAssertClose(r.imag!, MfArray([-9.0, -5.0, -9.0, -15.0, -5.0, 3.0, -7.0, -1.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "imag MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]))[MfArray([2, 0, -1] as [Int], mftype: .Int, shape: [3])]")
        }
        do {
            let r = MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]))[MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, -1] as [Int], mftype: .Int, shape: [2])]
            XCTAssertClose(r.real, MfArray([-1.0, 8.0] as [Double], mftype: .Double, shape: [2]), rtol: 0, atol: 0, checkType: true, "real MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]))[MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, -1] as [Int], mftype: .Int, shape: [2])]")
            XCTAssertClose(r.imag!, MfArray([3.0, -15.0] as [Double], mftype: .Double, shape: [2]), rtol: 0, atol: 0, checkType: true, "imag MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]))[MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, -1] as [Int], mftype: .Int, shape: [2])]")
        }
        do {
            let r = MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]))[Matft.all, MfArray([3, 0] as [Int], mftype: .Int, shape: [2])]
            XCTAssertClose(r.real, MfArray([1.0, 3.0, 6.0, 5.0, 8.0, 5.0] as [Double], mftype: .Double, shape: [3, 2]), rtol: 0, atol: 0, checkType: true, "real MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]))[Matft.all, MfArray([3, 0] as [Int], mftype: .Int, shape: [2])]")
            XCTAssertClose(r.imag!, MfArray([-1.0, -5.0, -11.0, -9.0, -15.0, -9.0] as [Double], mftype: .Double, shape: [3, 2]), rtol: 0, atol: 0, checkType: true, "imag MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]))[Matft.all, MfArray([3, 0] as [Int], mftype: .Int, shape: [2])]")
        }
        do {
            let z = MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]))
            z[MfArray([2, 0] as [Int], mftype: .Int, shape: [2])] = MfArray(real: MfArray([1.5] as [Double]), imag: MfArray([-4] as [Double]))
            let r = z
            XCTAssertClose(r.real, MfArray([1.5, 1.5, 1.5, 1.5, 5.0, 9.0, -2.0, 6.0, 1.5, 1.5, 1.5, 1.5] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "real z")
            XCTAssertClose(r.imag!, MfArray([-4.0, -4.0, -4.0, -4.0, -9.0, -17.0, 5.0, -11.0, -4.0, -4.0, -4.0, -4.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "imag z")
        }
        do {
            let z = MfArray(real: MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), imag: MfArray([-5.0, 3.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, -15.0] as [Double], mftype: .Double, shape: [3, 4]))
            z[MfArray([0, 2] as [Int], mftype: .Int, shape: [2]), MfArray([1, -1] as [Int], mftype: .Int, shape: [2])] = MfArray([7, 8])
            let r = z
            XCTAssertClose(r.real, MfArray([3.0, 7.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "real z")
            XCTAssertClose(r.imag!, MfArray([-5.0, 0.0, -7.0, -1.0, -9.0, -17.0, 5.0, -11.0, -9.0, -5.0, -9.0, 0.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 0, atol: 0, checkType: true, "imag z")
        }
    }
    #endif
}
