// Generated by python/gen_numpy_gaps_coverage.py (numpy 2.0.2). Do not edit by hand.
import XCTest

import Matft

/// NumPy functions over dtypes, memory layouts (`layoutVariants`) and edge cases. Expected values are numpy / scipy outputs
final class NumpyGapsCoverageTests: XCTestCase {
    private let A = MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4])
    private let AF = MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Float, shape: [3, 4])
    private let AI = MfArray([3, -1, 4, 1, 5, 9, -2, 6, 5, 3, 5, 8] as [Int], mftype: .Int, shape: [3, 4])
    private let AN = MfArray([1.0, .nan, 3.0, 4.0, 2.0, 5.0, .nan, 1.0, .nan, 7.0, 2.0, 2.0] as [Double], mftype: .Double, shape: [3, 4])
    private let S = MfArray([-3.0, -1.0, -1.0, 0.0, 2.0, 5.0, 5.0, 9.0] as [Double], mftype: .Double, shape: [8])
    private let C3 = MfArray([-3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, -3.0, -2.0, -1.0] as [Double], mftype: .Double, shape: [2, 3, 4])
    private let B = MfArray([true, false, true, false, false, true] as [Bool], shape: [2, 3])
    private let M = MfArray([1.0, 2.0, 1.0, 3.0, 1.0, 5.0, 1.0, 7.0] as [Double], mftype: .Double, shape: [4, 2])
    private let NEWX = MfArray([-1.0, 0.0, 0.5, 2.0, 2.5, 3.9, 5.0] as [Double], mftype: .Double, shape: [7])
    private let Z = MfArray([1.0, -.infinity, 0.0, .infinity, .nan, -2.0] as [Double], mftype: .Double, shape: [2, 3])

    func test_orderstats_layouts() {
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.median(x), MfArray([4.5] as [Double], mftype: .Double, shape: [1]), rtol: 1e-10, atol: 1e-10, "Matft.stats.median(x) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.stats.median(x), MfArray([4.5] as [Double], mftype: .Float, shape: [1]), rtol: 1e-05, atol: 1e-05, "Matft.stats.median(x) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.median(x, axis: 0), MfArray([5.0, 3.0, 4.0, 6.0] as [Double], mftype: .Double, shape: [4]), rtol: 1e-10, atol: 1e-10, "Matft.stats.median(x, axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.stats.median(x, axis: 0), MfArray([5.0, 3.0, 4.0, 6.0] as [Double], mftype: .Float, shape: [4]), rtol: 1e-05, atol: 1e-05, "Matft.stats.median(x, axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.median(x, axis: 1), MfArray([2.0, 5.5, 5.0] as [Double], mftype: .Double, shape: [3]), rtol: 1e-10, atol: 1e-10, "Matft.stats.median(x, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.stats.median(x, axis: 1), MfArray([2.0, 5.5, 5.0] as [Double], mftype: .Float, shape: [3]), rtol: 1e-05, atol: 1e-05, "Matft.stats.median(x, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.median(x, axis: -1), MfArray([2.0, 5.5, 5.0] as [Double], mftype: .Double, shape: [3]), rtol: 1e-10, atol: 1e-10, "Matft.stats.median(x, axis: -1) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.stats.median(x, axis: -1), MfArray([2.0, 5.5, 5.0] as [Double], mftype: .Float, shape: [3]), rtol: 1e-05, atol: 1e-05, "Matft.stats.median(x, axis: -1) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.percentile(x, q: 30, axis: 0, method: .linear), MfArray([4.2, 1.4, 1.5999999999999996, 4.0] as [Double], mftype: .Double, shape: [4]), rtol: 1e-10, atol: 1e-10, "Matft.stats.percentile(x, q: 30, axis: 0, method: .linear) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.percentile(x, q: 30, axis: 1, method: .linear), MfArray([0.7999999999999998, 4.299999999999999, 4.8] as [Double], mftype: .Double, shape: [3]), rtol: 1e-10, atol: 1e-10, "Matft.stats.percentile(x, q: 30, axis: 1, method: .linear) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.percentile(x, q: 30, axis: 0, method: .lower), MfArray([3.0, -1.0, -2.0, 1.0] as [Double], mftype: .Double, shape: [4]), rtol: 1e-10, atol: 1e-10, "Matft.stats.percentile(x, q: 30, axis: 0, method: .lower) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.percentile(x, q: 30, axis: 1, method: .lower), MfArray([-1.0, -2.0, 3.0] as [Double], mftype: .Double, shape: [3]), rtol: 1e-10, atol: 1e-10, "Matft.stats.percentile(x, q: 30, axis: 1, method: .lower) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.percentile(x, q: 30, axis: 0, method: .higher), MfArray([5.0, 3.0, 4.0, 6.0] as [Double], mftype: .Double, shape: [4]), rtol: 1e-10, atol: 1e-10, "Matft.stats.percentile(x, q: 30, axis: 0, method: .higher) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.percentile(x, q: 30, axis: 1, method: .higher), MfArray([1.0, 5.0, 5.0] as [Double], mftype: .Double, shape: [3]), rtol: 1e-10, atol: 1e-10, "Matft.stats.percentile(x, q: 30, axis: 1, method: .higher) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.percentile(x, q: 30, axis: 0, method: .nearest), MfArray([5.0, 3.0, 4.0, 6.0] as [Double], mftype: .Double, shape: [4]), rtol: 1e-10, atol: 1e-10, "Matft.stats.percentile(x, q: 30, axis: 0, method: .nearest) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.percentile(x, q: 30, axis: 1, method: .nearest), MfArray([1.0, 5.0, 5.0] as [Double], mftype: .Double, shape: [3]), rtol: 1e-10, atol: 1e-10, "Matft.stats.percentile(x, q: 30, axis: 1, method: .nearest) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.percentile(x, q: 30, axis: 0, method: .midpoint), MfArray([4.0, 1.0, 1.0, 3.5] as [Double], mftype: .Double, shape: [4]), rtol: 1e-10, atol: 1e-10, "Matft.stats.percentile(x, q: 30, axis: 0, method: .midpoint) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.percentile(x, q: 30, axis: 1, method: .midpoint), MfArray([0.0, 1.5, 4.0] as [Double], mftype: .Double, shape: [3]), rtol: 1e-10, atol: 1e-10, "Matft.stats.percentile(x, q: 30, axis: 1, method: .midpoint) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.quantile(x, q: [0.1, 0.9], axis: 1, keepDims: true), MfArray([-0.3999999999999999, 0.10000000000000053, 3.6, 3.7, 8.100000000000001, 7.1000000000000005] as [Double], mftype: .Double, shape: [2, 3, 1]), rtol: 1e-10, atol: 1e-10, "Matft.stats.quantile(x, q: [0.1, 0.9], axis: 1, keepDims: true) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.percentile(x, q: [0, 100]), MfArray([-2.0, 9.0] as [Double], mftype: .Double, shape: [2]), rtol: 1e-10, atol: 1e-10, "Matft.stats.percentile(x, q: [0, 100]) \(name)")
        }
        XCTAssertClose(Matft.stats.median(MfArray([7.5] as [Double])), MfArray([7.5] as [Double], mftype: .Double, shape: [1]), rtol: 1e-10, atol: 1e-10, "Matft.stats.median(MfArray([7.5] as [Double]))")
        XCTAssertClose(Matft.stats.percentile(MfArray([[7.5]] as [[Double]]), q: 40, axis: 0), MfArray([7.5] as [Double], mftype: .Double, shape: [1]), rtol: 1e-10, atol: 1e-10, "Matft.stats.percentile(MfArray([[7.5]] as [[Double]]), q: 40, axis: 0)")
    }

    func test_nan_functions_layouts() {
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nansum(x), MfArray([27.0] as [Double], mftype: .Double, shape: [1]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nansum(x) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanmean(x), MfArray([3.0] as [Double], mftype: .Double, shape: [1]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanmean(x) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanmax(x), MfArray([7.0] as [Double], mftype: .Double, shape: [1]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanmax(x) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanmin(x), MfArray([1.0] as [Double], mftype: .Double, shape: [1]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanmin(x) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanmedian(x), MfArray([2.0] as [Double], mftype: .Double, shape: [1]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanmedian(x) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertEqual(Matft.stats.nanargmax(x), MfArray([9] as [Int], mftype: .Int, shape: [1]), "Matft.stats.nanargmax(x) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertEqual(Matft.stats.nanargmin(x), MfArray([0] as [Int], mftype: .Int, shape: [1]), "Matft.stats.nanargmin(x) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanvar(x, keepDims: true, ddof: 0), MfArray([3.5555555555555554] as [Double], mftype: .Double, shape: [1, 1]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanvar(x, keepDims: true, ddof: 0) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanstd(x.astype(.Float), ddof: 0), MfArray([1.8856180906295776] as [Double], mftype: .Float, shape: [1]), rtol: 1e-05, atol: 1e-05, "Matft.stats.nanstd(x.astype(.Float), ddof: 0) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanvar(x, keepDims: true, ddof: 1), MfArray([4.0] as [Double], mftype: .Double, shape: [1, 1]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanvar(x, keepDims: true, ddof: 1) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanstd(x.astype(.Float), ddof: 1), MfArray([2.0] as [Double], mftype: .Float, shape: [1]), rtol: 1e-05, atol: 1e-05, "Matft.stats.nanstd(x.astype(.Float), ddof: 1) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanpercentile(x, q: [20, 75]), MfArray([1.6, 4.0] as [Double], mftype: .Double, shape: [2]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanpercentile(x, q: [20, 75]) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanquantile(x, q: 0.4, method: .nearest), MfArray([2.0] as [Double], mftype: .Double, shape: [1]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanquantile(x, q: 0.4, method: .nearest) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nansum(x, axis: 0), MfArray([3.0, 12.0, 5.0, 7.0] as [Double], mftype: .Double, shape: [4]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nansum(x, axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanmean(x, axis: 0), MfArray([1.5, 6.0, 2.5, 2.3333333333333335] as [Double], mftype: .Double, shape: [4]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanmean(x, axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanmax(x, axis: 0), MfArray([2.0, 7.0, 3.0, 4.0] as [Double], mftype: .Double, shape: [4]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanmax(x, axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanmin(x, axis: 0), MfArray([1.0, 5.0, 2.0, 1.0] as [Double], mftype: .Double, shape: [4]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanmin(x, axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanmedian(x, axis: 0), MfArray([1.5, 6.0, 2.5, 2.0] as [Double], mftype: .Double, shape: [4]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanmedian(x, axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertEqual(Matft.stats.nanargmax(x, axis: 0), MfArray([1, 2, 0, 0] as [Int], mftype: .Int, shape: [4]), "Matft.stats.nanargmax(x, axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertEqual(Matft.stats.nanargmin(x, axis: 0), MfArray([0, 1, 2, 1] as [Int], mftype: .Int, shape: [4]), "Matft.stats.nanargmin(x, axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanvar(x, axis: 0, keepDims: true, ddof: 0), MfArray([0.25, 1.0, 0.25, 1.5555555555555556] as [Double], mftype: .Double, shape: [1, 4]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanvar(x, axis: 0, keepDims: true, ddof: 0) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanstd(x.astype(.Float), axis: 0, ddof: 0), MfArray([0.5, 1.0, 0.5, 1.2472190856933594] as [Double], mftype: .Float, shape: [4]), rtol: 1e-05, atol: 1e-05, "Matft.stats.nanstd(x.astype(.Float), axis: 0, ddof: 0) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanvar(x, axis: 0, keepDims: true, ddof: 1), MfArray([0.5, 2.0, 0.5, 2.3333333333333335] as [Double], mftype: .Double, shape: [1, 4]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanvar(x, axis: 0, keepDims: true, ddof: 1) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanstd(x.astype(.Float), axis: 0, ddof: 1), MfArray([0.7071067690849304, 1.4142135381698608, 0.7071067690849304, 1.5275251865386963] as [Double], mftype: .Float, shape: [4]), rtol: 1e-05, atol: 1e-05, "Matft.stats.nanstd(x.astype(.Float), axis: 0, ddof: 1) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanpercentile(x, q: [20, 75], axis: 0), MfArray([1.2, 5.4, 2.2, 1.4, 1.75, 6.5, 2.75, 3.0] as [Double], mftype: .Double, shape: [2, 4]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanpercentile(x, q: [20, 75], axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanquantile(x, q: 0.4, axis: 0, method: .nearest), MfArray([1.0, 5.0, 2.0, 2.0] as [Double], mftype: .Double, shape: [4]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanquantile(x, q: 0.4, axis: 0, method: .nearest) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nansum(x, axis: 1), MfArray([8.0, 8.0, 11.0] as [Double], mftype: .Double, shape: [3]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nansum(x, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanmean(x, axis: 1), MfArray([2.6666666666666665, 2.6666666666666665, 3.6666666666666665] as [Double], mftype: .Double, shape: [3]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanmean(x, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanmax(x, axis: 1), MfArray([4.0, 5.0, 7.0] as [Double], mftype: .Double, shape: [3]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanmax(x, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanmin(x, axis: 1), MfArray([1.0, 1.0, 2.0] as [Double], mftype: .Double, shape: [3]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanmin(x, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanmedian(x, axis: 1), MfArray([3.0, 2.0, 2.0] as [Double], mftype: .Double, shape: [3]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanmedian(x, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertEqual(Matft.stats.nanargmax(x, axis: 1), MfArray([3, 1, 1] as [Int], mftype: .Int, shape: [3]), "Matft.stats.nanargmax(x, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertEqual(Matft.stats.nanargmin(x, axis: 1), MfArray([0, 3, 2] as [Int], mftype: .Int, shape: [3]), "Matft.stats.nanargmin(x, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanvar(x, axis: 1, keepDims: true, ddof: 0), MfArray([1.5555555555555554, 2.8888888888888893, 5.555555555555556] as [Double], mftype: .Double, shape: [3, 1]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanvar(x, axis: 1, keepDims: true, ddof: 0) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanstd(x.astype(.Float), axis: 1, ddof: 0), MfArray([1.2472190856933594, 1.6996731758117676, 2.357022523880005] as [Double], mftype: .Float, shape: [3]), rtol: 1e-05, atol: 1e-05, "Matft.stats.nanstd(x.astype(.Float), axis: 1, ddof: 0) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanvar(x, axis: 1, keepDims: true, ddof: 1), MfArray([2.333333333333333, 4.333333333333334, 8.333333333333334] as [Double], mftype: .Double, shape: [3, 1]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanvar(x, axis: 1, keepDims: true, ddof: 1) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanstd(x.astype(.Float), axis: 1, ddof: 1), MfArray([1.5275251865386963, 2.0816659927368164, 2.886751413345337] as [Double], mftype: .Float, shape: [3]), rtol: 1e-05, atol: 1e-05, "Matft.stats.nanstd(x.astype(.Float), axis: 1, ddof: 1) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanpercentile(x, q: [20, 75], axis: 1), MfArray([1.8, 1.4, 2.0, 3.5, 3.5, 4.5] as [Double], mftype: .Double, shape: [2, 3]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanpercentile(x, q: [20, 75], axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.stats.nanquantile(x, q: 0.4, axis: 1, method: .nearest), MfArray([3.0, 2.0, 2.0] as [Double], mftype: .Double, shape: [3]), rtol: 1e-10, atol: 1e-10, "Matft.stats.nanquantile(x, q: 0.4, axis: 1, method: .nearest) \(name)")
        }
    }

    func test_var_std() {
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.var(x, ddof: 0), MfArray([9.972222222222221] as [Double], mftype: .Double, shape: [1]), rtol: 1e-10, atol: 1e-10, "Matft.stats.var(x, ddof: 0) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.stats.std(x, ddof: 0), MfArray([3.1578824520111084] as [Double], mftype: .Float, shape: [1]), rtol: 1e-05, atol: 1e-05, "Matft.stats.std(x, ddof: 0) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertClose(Matft.stats.std(x, keepDims: true, ddof: 0), MfArray([3.157882553582736] as [Double], mftype: .Double, shape: [1, 1]), rtol: 1e-06, atol: 1e-06, "Matft.stats.std(x, keepDims: true, ddof: 0) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.var(x, ddof: 1), MfArray([10.878787878787877] as [Double], mftype: .Double, shape: [1]), rtol: 1e-10, atol: 1e-10, "Matft.stats.var(x, ddof: 1) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.stats.std(x, ddof: 1), MfArray([3.2983007431030273] as [Double], mftype: .Float, shape: [1]), rtol: 1e-05, atol: 1e-05, "Matft.stats.std(x, ddof: 1) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertClose(Matft.stats.std(x, keepDims: true, ddof: 1), MfArray([3.2983007562664564] as [Double], mftype: .Double, shape: [1, 1]), rtol: 1e-06, atol: 1e-06, "Matft.stats.std(x, keepDims: true, ddof: 1) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.var(x, axis: 0, ddof: 0), MfArray([0.888888888888889, 16.88888888888889, 9.555555555555557, 8.666666666666666] as [Double], mftype: .Double, shape: [4]), rtol: 1e-10, atol: 1e-10, "Matft.stats.var(x, axis: 0, ddof: 0) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.stats.std(x, axis: 0, ddof: 0), MfArray([0.9428090453147888, 4.109609127044678, 3.0912060737609863, 2.943920373916626] as [Double], mftype: .Float, shape: [4]), rtol: 1e-05, atol: 1e-05, "Matft.stats.std(x, axis: 0, ddof: 0) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertClose(Matft.stats.std(x, axis: 0, keepDims: true, ddof: 0), MfArray([0.9428090415820634, 4.109609335312651, 3.091206165165235, 2.943920288775949] as [Double], mftype: .Double, shape: [1, 4]), rtol: 1e-06, atol: 1e-06, "Matft.stats.std(x, axis: 0, keepDims: true, ddof: 0) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.var(x, axis: 0, ddof: 1), MfArray([1.3333333333333335, 25.333333333333332, 14.333333333333336, 13.0] as [Double], mftype: .Double, shape: [4]), rtol: 1e-10, atol: 1e-10, "Matft.stats.var(x, axis: 0, ddof: 1) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.stats.std(x, axis: 0, ddof: 1), MfArray([1.154700517654419, 5.0332231521606445, 3.7859389781951904, 3.605551242828369] as [Double], mftype: .Float, shape: [4]), rtol: 1e-05, atol: 1e-05, "Matft.stats.std(x, axis: 0, ddof: 1) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertClose(Matft.stats.std(x, axis: 0, keepDims: true, ddof: 1), MfArray([1.1547005383792517, 5.033222956847166, 3.785938897200183, 3.605551275463989] as [Double], mftype: .Double, shape: [1, 4]), rtol: 1e-06, atol: 1e-06, "Matft.stats.std(x, axis: 0, keepDims: true, ddof: 1) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.var(x, axis: 1, ddof: 0), MfArray([3.6875, 16.25, 3.1875] as [Double], mftype: .Double, shape: [3]), rtol: 1e-10, atol: 1e-10, "Matft.stats.var(x, axis: 1, ddof: 0) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.stats.std(x, axis: 1, ddof: 0), MfArray([1.9202864170074463, 4.031128883361816, 1.785357117652893] as [Double], mftype: .Float, shape: [3]), rtol: 1e-05, atol: 1e-05, "Matft.stats.std(x, axis: 1, ddof: 0) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertClose(Matft.stats.std(x, axis: 1, keepDims: true, ddof: 0), MfArray([1.920286436967152, 4.031128874149275, 1.7853571071357126] as [Double], mftype: .Double, shape: [3, 1]), rtol: 1e-06, atol: 1e-06, "Matft.stats.std(x, axis: 1, keepDims: true, ddof: 0) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.var(x, axis: 1, ddof: 1), MfArray([4.916666666666667, 21.666666666666668, 4.25] as [Double], mftype: .Double, shape: [3]), rtol: 1e-10, atol: 1e-10, "Matft.stats.var(x, axis: 1, ddof: 1) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.stats.std(x, axis: 1, ddof: 1), MfArray([2.217355728149414, 4.6547465324401855, 2.0615527629852295] as [Double], mftype: .Float, shape: [3]), rtol: 1e-05, atol: 1e-05, "Matft.stats.std(x, axis: 1, ddof: 1) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertClose(Matft.stats.std(x, axis: 1, keepDims: true, ddof: 1), MfArray([2.217355782608345, 4.654746681256314, 2.0615528128088303] as [Double], mftype: .Double, shape: [3, 1]), rtol: 1e-06, atol: 1e-06, "Matft.stats.std(x, axis: 1, keepDims: true, ddof: 1) \(name)")
        }
        XCTAssertClose(Matft.stats.var(MfArray([1.0, 2.0] as [Double]), ddof: 2), MfArray([.infinity] as [Double], mftype: .Double, shape: [1]), rtol: 1e-10, atol: 1e-10, "Matft.stats.var(MfArray([1.0, 2.0] as [Double]), ddof: 2)")
        XCTAssertClose(Matft.stats.var(MfArray([1.0, 2.0] as [Double]), ddof: 3), MfArray([.infinity] as [Double], mftype: .Double, shape: [1]), rtol: 1e-10, atol: 1e-10, "Matft.stats.var(MfArray([1.0, 2.0] as [Double]), ddof: 3)")
        XCTAssertClose(Matft.stats.std(MfArray([[1.0, 2.0], [3.0, 3.0]] as [[Double]]), axis: 1, ddof: 2), MfArray([.infinity, .nan] as [Double], mftype: .Double, shape: [2]), rtol: 1e-10, atol: 1e-10, "Matft.stats.std(MfArray([[1.0, 2.0], [3.0, 3.0]] as [[Double]]), axis: 1, ddof: 2)")
    }

    func test_searching() {
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.where(x > 2, x, -x), MfArray([3.0, 1.0, 4.0, -1.0, 5.0, 9.0, 2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 1e-10, atol: 1e-10, "Matft.where(x > 2, x, -x) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.where(x > 2, x, MfArray([0.5, -0.5, 1.5, -1.5] as [Double])), MfArray([3.0, -0.5, 4.0, -1.5, 5.0, 9.0, 1.5, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 1e-10, atol: 1e-10, "Matft.where(x > 2, x, MfArray([0.5, -0.5, 1.5, -1.5] as [Double])) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.where(x > 2, 100.0, x), MfArray([100.0, -1.0, 100.0, 1.0, 100.0, 100.0, -2.0, 100.0, 100.0, 100.0, 100.0, 100.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 1e-10, atol: 1e-10, "Matft.where(x > 2, 100.0, x) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.where(x > 2, x, 0.25), MfArray([3.0, 0.25, 4.0, 0.25, 5.0, 9.0, 0.25, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 1e-10, atol: 1e-10, "Matft.where(x > 2, x, 0.25) \(name)")
        }
        for (name, x) in layoutVariants(AN){
            XCTAssertClose(Matft.where(x > 2, x, MfArray([.nan] as [Double])), MfArray([.nan, .nan, 3.0, 4.0, .nan, 5.0, .nan, .nan, .nan, 7.0, .nan, .nan] as [Double], mftype: .Double, shape: [3, 4]), rtol: 1e-10, atol: 1e-10, "Matft.where(x > 2, x, MfArray([.nan] as [Double])) \(name)")
        }
        for (name, x) in layoutVariants(S){
            XCTAssertEqual(Matft.searchsorted(x, MfArray([-5, -1, 0.5, 5, 10] as [Double]), side: .left), MfArray([0, 1, 4, 5, 8] as [Int], mftype: .Int, shape: [5]), "Matft.searchsorted(x, MfArray([-5, -1, 0.5, 5, 10] as [Double]), side: .left) \(name)")
        }
        for (name, x) in layoutVariants(S){
            XCTAssertEqual(Matft.searchsorted(x, MfArray([-5, -1, 0.5, 5, 10] as [Double]), side: .right), MfArray([0, 3, 4, 7, 8] as [Int], mftype: .Int, shape: [5]), "Matft.searchsorted(x, MfArray([-5, -1, 0.5, 5, 10] as [Double]), side: .right) \(name)")
        }
        for (name, x) in layoutVariants(S){
            XCTAssertEqual(Matft.searchsorted(MfArray([-5, -1, 0.5, 5, 10] as [Double]), x), MfArray([1, 1, 1, 2, 3, 3, 3, 4] as [Int], mftype: .Int, shape: [8]), "Matft.searchsorted(MfArray([-5, -1, 0.5, 5, 10] as [Double]), x) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertEqual(Matft.digitize(x, bins: MfArray([-1, 2, 5] as [Double])), MfArray([2, 1, 2, 1, 3, 3, 0, 3, 3, 2, 3, 3] as [Int], mftype: .Int, shape: [3, 4]), "Matft.digitize(x, bins: MfArray([-1, 2, 5] as [Double])) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertEqual(Matft.digitize(x, bins: MfArray([-1, 2, 5] as [Double]), right: true), MfArray([2, 0, 2, 1, 2, 3, 0, 3, 2, 2, 2, 3] as [Int], mftype: .Int, shape: [3, 4]), "Matft.digitize(x, bins: MfArray([-1, 2, 5] as [Double]), right: true) \(name)")
        }
        do {
            for (name, x) in layoutVariants(A){
                let (hist, edges) = Matft.histogram(x, bins: 4)
                XCTAssertEqual(hist, MfArray([2, 3, 5, 2] as [Int], mftype: .Int, shape: [4]), name)
                XCTAssertClose(edges, MfArray([-2.0, 0.75, 3.5, 6.25, 9.0] as [Double], mftype: .Double, shape: [5]), rtol: 1e-12, atol: 1e-12, name)
            }
        }
        do {
            let (hist, edges) = Matft.histogram(MfArray([5.0, 5.0, 5.0] as [Double]), bins: 4)
            XCTAssertEqual(hist, MfArray([0, 0, 3, 0] as [Int], mftype: .Int, shape: [4]))
            XCTAssertClose(edges, MfArray([4.5, 4.75, 5.0, 5.25, 5.5] as [Double], mftype: .Double, shape: [5]), rtol: 1e-12)
        }
        do {
            let (hist, edges) = Matft.histogram(A, bins: 3, range: (0, 6))
            XCTAssertEqual(hist, MfArray([1, 2, 5] as [Int], mftype: .Int, shape: [3]))
            XCTAssertClose(edges, MfArray([0.0, 2.0, 4.0, 6.0] as [Double], mftype: .Double, shape: [4]), rtol: 1e-12)
        }
        XCTAssertEqual(Matft.bincount(MfArray([] as [Int], shape: [0])), MfArray([] as [Int], mftype: .Int, shape: [0]))
        XCTAssertEqual(Matft.bincount(MfArray([] as [Int], shape: [0]), minlength: 3), MfArray([0, 0, 0] as [Int], mftype: .Int, shape: [3]))
        XCTAssertEqual(Matft.bincount(MfArray([3, 1, 1, 0, 3, 3] as [Int])[Matft.reverse]), MfArray([1, 2, 0, 3] as [Int], mftype: .Int, shape: [4]))
    }

    func test_setops() {
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.unique(x), MfArray([-2.0, -1.0, 1.0, 3.0, 4.0, 5.0, 6.0, 8.0, 9.0] as [Double], mftype: .Double, shape: [9]), rtol: 1e-10, atol: 1e-10, "Matft.unique(x) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.unique(x), MfArray([-2.0, -1.0, 1.0, 3.0, 4.0, 5.0, 6.0, 8.0, 9.0] as [Double], mftype: .Float, shape: [9]), rtol: 1e-05, atol: 1e-05, "Matft.unique(x) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertEqual(Matft.unique(x), MfArray([-2, -1, 1, 3, 4, 5, 6, 8, 9] as [Int], mftype: .Int, shape: [9]), "Matft.unique(x) \(name)")
        }
        for (name, x) in layoutVariants(B){
            XCTAssertEqual(Matft.unique(x), MfArray([false, true] as [Bool], shape: [2]), "Matft.unique(x) \(name)")
        }
        for (name, x) in layoutVariants(A){
            let (values, counts) = Matft.unique_counts(x)
            XCTAssertClose(values, MfArray([-2.0, -1.0, 1.0, 3.0, 4.0, 5.0, 6.0, 8.0, 9.0] as [Double], mftype: .Double, shape: [9]), rtol: 1e-12, name)
            XCTAssertEqual(counts, MfArray([1, 1, 1, 2, 1, 3, 1, 1, 1] as [Int], mftype: .Int, shape: [9]), name)
        }
        for (name, x) in layoutVariants(A){
            let (_, inverse) = Matft.unique_inverse(x)
            XCTAssertEqual(inverse, MfArray([3, 1, 4, 2, 5, 8, 0, 6, 5, 3, 5, 7] as [Int], mftype: .Int, shape: [3, 4]), name)
        }
        for (name, x) in layoutVariants(A){
            XCTAssertEqual(Matft.isin(x, MfArray([5, -1, 100] as [Double])), MfArray([false, true, false, false, true, false, false, false, true, false, true, false] as [Bool], shape: [3, 4]), "Matft.isin(x, MfArray([5, -1, 100] as [Double])) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertEqual(Matft.isin(x, MfArray([5, -1, 100] as [Double]), invert: true), MfArray([true, false, true, true, false, true, true, true, false, true, false, true] as [Bool], shape: [3, 4]), "Matft.isin(x, MfArray([5, -1, 100] as [Double]), invert: true) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.intersect1d(x, MfArray([9, 5, 0, 3] as [Double])), MfArray([3.0, 5.0, 9.0] as [Double], mftype: .Double, shape: [3]), rtol: 1e-10, atol: 1e-10, "Matft.intersect1d(x, MfArray([9, 5, 0, 3] as [Double])) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.union1d(x, MfArray([10, 0] as [Double])), MfArray([-2.0, -1.0, 0.0, 1.0, 3.0, 4.0, 5.0, 6.0, 8.0, 9.0, 10.0] as [Double], mftype: .Double, shape: [11]), rtol: 1e-10, atol: 1e-10, "Matft.union1d(x, MfArray([10, 0] as [Double])) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.setdiff1d(x, MfArray([5, 3, 100] as [Double])), MfArray([-2.0, -1.0, 1.0, 4.0, 6.0, 8.0, 9.0] as [Double], mftype: .Double, shape: [7]), rtol: 1e-10, atol: 1e-10, "Matft.setdiff1d(x, MfArray([5, 3, 100] as [Double])) \(name)")
        }
        XCTAssertEqual(Matft.unique(MfArray([] as [Double], shape: [0])).shape, [0])
        XCTAssertEqual(Matft.isin(MfArray([] as [Double], shape: [0]), MfArray([1.0] as [Double])).shape, [0])
        XCTAssertEqual(Matft.intersect1d(MfArray([] as [Double], shape: [0]), MfArray([1.0] as [Double])).shape, [0])
        XCTAssertEqual(Matft.setdiff1d(MfArray([1.0] as [Double]), MfArray([1.0] as [Double])).shape, [0])
        XCTAssertClose(Matft.union1d(MfArray([] as [Double], shape: [0]), MfArray([2.0, 1.0] as [Double])), MfArray([1.0, 2.0] as [Double], mftype: .Double, shape: [2]), rtol: 1e-10, atol: 1e-10, "Matft.union1d(MfArray([] as [Double], shape: [0]), MfArray([2.0, 1.0] as [Double]))")
    }

    func test_manipulation() {
        for (name, x) in layoutVariants(C3){
            XCTAssertClose(Matft.pad(x, pad_width: [(1, 2), (0, 1), (2, 0)], mode: .constant), MfArray([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -3.0, -2.0, -1.0, 0.0, 0.0, 0.0, 1.0, 2.0, 3.0, -3.0, 0.0, 0.0, -2.0, -1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 3.0, -3.0, -2.0, 0.0, 0.0, -1.0, 0.0, 1.0, 2.0, 0.0, 0.0, 3.0, -3.0, -2.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] as [Double], mftype: .Double, shape: [5, 4, 6]), rtol: 1e-10, atol: 1e-10, "Matft.pad(x, pad_width: [(1, 2), (0, 1), (2, 0)], mode: .constant) \(name)")
        }
        for (name, x) in layoutVariants(C3){
            XCTAssertClose(Matft.pad(x, pad_width: [(1, 2), (0, 1), (2, 0)], mode: .edge), MfArray([-3.0, -3.0, -3.0, -2.0, -1.0, 0.0, 1.0, 1.0, 1.0, 2.0, 3.0, -3.0, -2.0, -2.0, -2.0, -1.0, 0.0, 1.0, -2.0, -2.0, -2.0, -1.0, 0.0, 1.0, -3.0, -3.0, -3.0, -2.0, -1.0, 0.0, 1.0, 1.0, 1.0, 2.0, 3.0, -3.0, -2.0, -2.0, -2.0, -1.0, 0.0, 1.0, -2.0, -2.0, -2.0, -1.0, 0.0, 1.0, 2.0, 2.0, 2.0, 3.0, -3.0, -2.0, -1.0, -1.0, -1.0, 0.0, 1.0, 2.0, 3.0, 3.0, 3.0, -3.0, -2.0, -1.0, 3.0, 3.0, 3.0, -3.0, -2.0, -1.0, 2.0, 2.0, 2.0, 3.0, -3.0, -2.0, -1.0, -1.0, -1.0, 0.0, 1.0, 2.0, 3.0, 3.0, 3.0, -3.0, -2.0, -1.0, 3.0, 3.0, 3.0, -3.0, -2.0, -1.0, 2.0, 2.0, 2.0, 3.0, -3.0, -2.0, -1.0, -1.0, -1.0, 0.0, 1.0, 2.0, 3.0, 3.0, 3.0, -3.0, -2.0, -1.0, 3.0, 3.0, 3.0, -3.0, -2.0, -1.0] as [Double], mftype: .Double, shape: [5, 4, 6]), rtol: 1e-10, atol: 1e-10, "Matft.pad(x, pad_width: [(1, 2), (0, 1), (2, 0)], mode: .edge) \(name)")
        }
        for (name, x) in layoutVariants(C3){
            XCTAssertClose(Matft.pad(x, pad_width: [(1, 2), (0, 1), (2, 0)], mode: .reflect), MfArray([-3.0, 3.0, 2.0, 3.0, -3.0, -2.0, 1.0, 0.0, -1.0, 0.0, 1.0, 2.0, -2.0, -3.0, 3.0, -3.0, -2.0, -1.0, 1.0, 0.0, -1.0, 0.0, 1.0, 2.0, -1.0, -2.0, -3.0, -2.0, -1.0, 0.0, 3.0, 2.0, 1.0, 2.0, 3.0, -3.0, 0.0, -1.0, -2.0, -1.0, 0.0, 1.0, 3.0, 2.0, 1.0, 2.0, 3.0, -3.0, -3.0, 3.0, 2.0, 3.0, -3.0, -2.0, 1.0, 0.0, -1.0, 0.0, 1.0, 2.0, -2.0, -3.0, 3.0, -3.0, -2.0, -1.0, 1.0, 0.0, -1.0, 0.0, 1.0, 2.0, -1.0, -2.0, -3.0, -2.0, -1.0, 0.0, 3.0, 2.0, 1.0, 2.0, 3.0, -3.0, 0.0, -1.0, -2.0, -1.0, 0.0, 1.0, 3.0, 2.0, 1.0, 2.0, 3.0, -3.0, -3.0, 3.0, 2.0, 3.0, -3.0, -2.0, 1.0, 0.0, -1.0, 0.0, 1.0, 2.0, -2.0, -3.0, 3.0, -3.0, -2.0, -1.0, 1.0, 0.0, -1.0, 0.0, 1.0, 2.0] as [Double], mftype: .Double, shape: [5, 4, 6]), rtol: 1e-10, atol: 1e-10, "Matft.pad(x, pad_width: [(1, 2), (0, 1), (2, 0)], mode: .reflect) \(name)")
        }
        for (name, x) in layoutVariants(C3){
            XCTAssertClose(Matft.pad(x, pad_width: [(1, 2), (0, 1), (2, 0)], mode: .symmetric), MfArray([-2.0, -3.0, -3.0, -2.0, -1.0, 0.0, 2.0, 1.0, 1.0, 2.0, 3.0, -3.0, -1.0, -2.0, -2.0, -1.0, 0.0, 1.0, -1.0, -2.0, -2.0, -1.0, 0.0, 1.0, -2.0, -3.0, -3.0, -2.0, -1.0, 0.0, 2.0, 1.0, 1.0, 2.0, 3.0, -3.0, -1.0, -2.0, -2.0, -1.0, 0.0, 1.0, -1.0, -2.0, -2.0, -1.0, 0.0, 1.0, 3.0, 2.0, 2.0, 3.0, -3.0, -2.0, 0.0, -1.0, -1.0, 0.0, 1.0, 2.0, -3.0, 3.0, 3.0, -3.0, -2.0, -1.0, -3.0, 3.0, 3.0, -3.0, -2.0, -1.0, 3.0, 2.0, 2.0, 3.0, -3.0, -2.0, 0.0, -1.0, -1.0, 0.0, 1.0, 2.0, -3.0, 3.0, 3.0, -3.0, -2.0, -1.0, -3.0, 3.0, 3.0, -3.0, -2.0, -1.0, -2.0, -3.0, -3.0, -2.0, -1.0, 0.0, 2.0, 1.0, 1.0, 2.0, 3.0, -3.0, -1.0, -2.0, -2.0, -1.0, 0.0, 1.0, -1.0, -2.0, -2.0, -1.0, 0.0, 1.0] as [Double], mftype: .Double, shape: [5, 4, 6]), rtol: 1e-10, atol: 1e-10, "Matft.pad(x, pad_width: [(1, 2), (0, 1), (2, 0)], mode: .symmetric) \(name)")
        }
        for (name, x) in layoutVariants(C3){
            XCTAssertClose(Matft.pad(x, pad_width: [(1, 2), (0, 1), (2, 0)], mode: .wrap), MfArray([-3.0, -2.0, 2.0, 3.0, -3.0, -2.0, 1.0, 2.0, -1.0, 0.0, 1.0, 2.0, -2.0, -1.0, 3.0, -3.0, -2.0, -1.0, -3.0, -2.0, 2.0, 3.0, -3.0, -2.0, -1.0, 0.0, -3.0, -2.0, -1.0, 0.0, 3.0, -3.0, 1.0, 2.0, 3.0, -3.0, 0.0, 1.0, -2.0, -1.0, 0.0, 1.0, -1.0, 0.0, -3.0, -2.0, -1.0, 0.0, -3.0, -2.0, 2.0, 3.0, -3.0, -2.0, 1.0, 2.0, -1.0, 0.0, 1.0, 2.0, -2.0, -1.0, 3.0, -3.0, -2.0, -1.0, -3.0, -2.0, 2.0, 3.0, -3.0, -2.0, -1.0, 0.0, -3.0, -2.0, -1.0, 0.0, 3.0, -3.0, 1.0, 2.0, 3.0, -3.0, 0.0, 1.0, -2.0, -1.0, 0.0, 1.0, -1.0, 0.0, -3.0, -2.0, -1.0, 0.0, -3.0, -2.0, 2.0, 3.0, -3.0, -2.0, 1.0, 2.0, -1.0, 0.0, 1.0, 2.0, -2.0, -1.0, 3.0, -3.0, -2.0, -1.0, -3.0, -2.0, 2.0, 3.0, -3.0, -2.0] as [Double], mftype: .Double, shape: [5, 4, 6]), rtol: 1e-10, atol: 1e-10, "Matft.pad(x, pad_width: [(1, 2), (0, 1), (2, 0)], mode: .wrap) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.pad(x, pad_width: 2, constant_values: -7), MfArray([-7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, 3.0, -1.0, 4.0, 1.0, -7.0, -7.0, -7.0, -7.0, 5.0, 9.0, -2.0, 6.0, -7.0, -7.0, -7.0, -7.0, 5.0, 3.0, 5.0, 8.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0, -7.0] as [Double], mftype: .Float, shape: [7, 8]), rtol: 1e-05, atol: 1e-05, "Matft.pad(x, pad_width: 2, constant_values: -7) \(name)")
        }
        for (name, x) in layoutVariants(B){
            XCTAssertEqual(Matft.pad(x, pad_width: [(1, 0), (0, 2)], mode: .edge), MfArray([true, false, true, true, true, true, false, true, true, true, false, false, true, true, true] as [Bool], shape: [3, 5]), "Matft.pad(x, pad_width: [(1, 0), (0, 2)], mode: .edge) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.pad(x, pad_width: [(4, 5), (5, 0)], mode: .reflect), MfArray([-1.0, 4.0, 1.0, 4.0, -1.0, 3.0, -1.0, 4.0, 1.0, 9.0, -2.0, 6.0, -2.0, 9.0, 5.0, 9.0, -2.0, 6.0, 3.0, 5.0, 8.0, 5.0, 3.0, 5.0, 3.0, 5.0, 8.0, 9.0, -2.0, 6.0, -2.0, 9.0, 5.0, 9.0, -2.0, 6.0, -1.0, 4.0, 1.0, 4.0, -1.0, 3.0, -1.0, 4.0, 1.0, 9.0, -2.0, 6.0, -2.0, 9.0, 5.0, 9.0, -2.0, 6.0, 3.0, 5.0, 8.0, 5.0, 3.0, 5.0, 3.0, 5.0, 8.0, 9.0, -2.0, 6.0, -2.0, 9.0, 5.0, 9.0, -2.0, 6.0, -1.0, 4.0, 1.0, 4.0, -1.0, 3.0, -1.0, 4.0, 1.0, 9.0, -2.0, 6.0, -2.0, 9.0, 5.0, 9.0, -2.0, 6.0, 3.0, 5.0, 8.0, 5.0, 3.0, 5.0, 3.0, 5.0, 8.0, 9.0, -2.0, 6.0, -2.0, 9.0, 5.0, 9.0, -2.0, 6.0] as [Double], mftype: .Double, shape: [12, 9]), rtol: 1e-10, atol: 1e-10, "Matft.pad(x, pad_width: [(4, 5), (5, 0)], mode: .reflect) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.pad(x, pad_width: [(4, 5), (5, 0)], mode: .wrap), MfArray([8.0, 5.0, 3.0, 5.0, 8.0, 5.0, 3.0, 5.0, 8.0, 1.0, 3.0, -1.0, 4.0, 1.0, 3.0, -1.0, 4.0, 1.0, 6.0, 5.0, 9.0, -2.0, 6.0, 5.0, 9.0, -2.0, 6.0, 8.0, 5.0, 3.0, 5.0, 8.0, 5.0, 3.0, 5.0, 8.0, 1.0, 3.0, -1.0, 4.0, 1.0, 3.0, -1.0, 4.0, 1.0, 6.0, 5.0, 9.0, -2.0, 6.0, 5.0, 9.0, -2.0, 6.0, 8.0, 5.0, 3.0, 5.0, 8.0, 5.0, 3.0, 5.0, 8.0, 1.0, 3.0, -1.0, 4.0, 1.0, 3.0, -1.0, 4.0, 1.0, 6.0, 5.0, 9.0, -2.0, 6.0, 5.0, 9.0, -2.0, 6.0, 8.0, 5.0, 3.0, 5.0, 8.0, 5.0, 3.0, 5.0, 8.0, 1.0, 3.0, -1.0, 4.0, 1.0, 3.0, -1.0, 4.0, 1.0, 6.0, 5.0, 9.0, -2.0, 6.0, 5.0, 9.0, -2.0, 6.0] as [Double], mftype: .Double, shape: [12, 9]), rtol: 1e-10, atol: 1e-10, "Matft.pad(x, pad_width: [(4, 5), (5, 0)], mode: .wrap) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.diff(x, n: 1, axis: -1), MfArray([-4.0, 5.0, -3.0, 4.0, -11.0, 8.0, -2.0, 2.0, 3.0] as [Double], mftype: .Double, shape: [3, 3]), rtol: 1e-10, atol: 1e-10, "Matft.diff(x, n: 1, axis: -1) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.diff(x, n: 1, axis: -1), MfArray([-4.0, 5.0, -3.0, 4.0, -11.0, 8.0, -2.0, 2.0, 3.0] as [Double], mftype: .Float, shape: [3, 3]), rtol: 1e-05, atol: 1e-05, "Matft.diff(x, n: 1, axis: -1) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.diff(x, n: 2, axis: -1), MfArray([9.0, -8.0, -15.0, 19.0, 4.0, 1.0] as [Double], mftype: .Double, shape: [3, 2]), rtol: 1e-10, atol: 1e-10, "Matft.diff(x, n: 2, axis: -1) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.diff(x, n: 2, axis: -1), MfArray([9.0, -8.0, -15.0, 19.0, 4.0, 1.0] as [Double], mftype: .Float, shape: [3, 2]), rtol: 1e-05, atol: 1e-05, "Matft.diff(x, n: 2, axis: -1) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.diff(x, n: 1, axis: 0), MfArray([2.0, 10.0, -6.0, 5.0, 0.0, -6.0, 7.0, 2.0] as [Double], mftype: .Double, shape: [2, 4]), rtol: 1e-10, atol: 1e-10, "Matft.diff(x, n: 1, axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.diff(x, n: 1, axis: 0), MfArray([2.0, 10.0, -6.0, 5.0, 0.0, -6.0, 7.0, 2.0] as [Double], mftype: .Float, shape: [2, 4]), rtol: 1e-05, atol: 1e-05, "Matft.diff(x, n: 1, axis: 0) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.diff(x, n: 0, axis: 1), MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 1e-10, atol: 1e-10, "Matft.diff(x, n: 0, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.diff(x, n: 0, axis: 1), MfArray([3.0, -1.0, 4.0, 1.0, 5.0, 9.0, -2.0, 6.0, 5.0, 3.0, 5.0, 8.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 1e-05, atol: 1e-05, "Matft.diff(x, n: 0, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.diff(x, n: 3, axis: 1), MfArray([-17.0, 34.0, -3.0] as [Double], mftype: .Double, shape: [3, 1]), rtol: 1e-10, atol: 1e-10, "Matft.diff(x, n: 3, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.diff(x, n: 3, axis: 1), MfArray([-17.0, 34.0, -3.0] as [Double], mftype: .Float, shape: [3, 1]), rtol: 1e-05, atol: 1e-05, "Matft.diff(x, n: 3, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.diff(x, n: 4, axis: 1), MfArray([] as [Double], mftype: .Double, shape: [3, 0]), rtol: 1e-10, atol: 1e-10, "Matft.diff(x, n: 4, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.diff(x, n: 4, axis: 1), MfArray([] as [Double], mftype: .Float, shape: [3, 0]), rtol: 1e-05, atol: 1e-05, "Matft.diff(x, n: 4, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.diff(x, n: 5, axis: 1), MfArray([] as [Double], mftype: .Double, shape: [3, 0]), rtol: 1e-10, atol: 1e-10, "Matft.diff(x, n: 5, axis: 1) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.diff(x, n: 5, axis: 1), MfArray([] as [Double], mftype: .Float, shape: [3, 0]), rtol: 1e-05, atol: 1e-05, "Matft.diff(x, n: 5, axis: 1) \(name)")
        }
        do {
            let grids = Matft.meshgrid([MfArray([1, 2] as [Double]), MfArray([3, 4, 5] as [Double]), MfArray([6.5] as [Double])], indexing: .ij)
            XCTAssertEqual(grids.count, 3)
            XCTAssertClose(grids[0], MfArray([1.0, 1.0, 1.0, 2.0, 2.0, 2.0] as [Double], mftype: .Double, shape: [2, 3, 1]))
            XCTAssertClose(grids[1], MfArray([3.0, 4.0, 5.0, 3.0, 4.0, 5.0] as [Double], mftype: .Double, shape: [2, 3, 1]))
            XCTAssertClose(grids[2], MfArray([6.5, 6.5, 6.5, 6.5, 6.5, 6.5] as [Double], mftype: .Double, shape: [2, 3, 1]))
        }
        do {
            let grids = Matft.meshgrid(MfArray([1, 2, 3] as [Double])[Matft.reverse], MfArray([4, 5] as [Double]))
            XCTAssertClose(grids[0], MfArray([3.0, 2.0, 1.0, 3.0, 2.0, 1.0] as [Double], mftype: .Double, shape: [2, 3]))
            XCTAssertClose(grids[1], MfArray([4.0, 4.0, 4.0, 5.0, 5.0, 5.0] as [Double], mftype: .Double, shape: [2, 3]))
        }
    }

    #if !os(WASI) // LAPACK / interp1d are not available on WASI
    func test_fit() throws {
        for (name, x) in layoutVariants(M){
            let ret = try Matft.linalg.lstsq(x, MfArray([2.0, 2.5, 5.1, 6.9] as [Double]))
            XCTAssertClose(ret.x, MfArray([-0.24745762711864608, 1.0288135593220338] as [Double], mftype: .Double, shape: [2]), rtol: 1e-10, atol: 1e-10, name)
            XCTAssertClose(ret.residuals, MfArray([0.19525423728813474] as [Double], mftype: .Double, shape: [1]), rtol: 1e-8, atol: 1e-10, name)
            XCTAssertEqual(ret.rank, 2, name)
            XCTAssertClose(ret.s, MfArray([9.505101892824838, 0.8081076704361172] as [Double], mftype: .Double, shape: [2]), rtol: 1e-10, name)
        }
        do {
            let ret = try Matft.linalg.lstsq(M.astype(.Float), MfArray([2.0, 2.5, 5.1, 6.9] as [Float]))
            XCTAssertClose(ret.x, MfArray([-0.2474576234817505, 1.0288136005401611] as [Double], mftype: .Float, shape: [2]), rtol: 1e-4, atol: 1e-4)
        }
        do {
            let xs = MfArray([5.0, 4.0, 2.0, 1.0, 0.0] as [Double])[Matft.reverse]
            let ys = MfArray([26.1, 15.9, 4.2, 1.8, 1.0] as [Double])[Matft.reverse]
            let p = try Matft.polyfit(xs, ys, deg: 2)
            XCTAssertClose(p, MfArray([1.1564935064935071, -0.8493506493506512, 1.1987012987012995] as [Double], mftype: .Double, shape: [3]), rtol: 1e-9, atol: 1e-10)
            XCTAssertClose(try Matft.polyfit(xs.astype(.Float), ys.astype(.Float), deg: 2), MfArray([1.1564935445785522, -0.84935063123703, 1.19870126247406] as [Double], mftype: .Float, shape: [3]), rtol: 1e-4, atol: 1e-4)
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.polyval(MfArray([2.0, -1.0, 0.5] as [Double])[Matft.reverse], x), MfArray([3.5, 3.5, 6.0, 1.5, 9.5, 33.5, 6.0, 14.0, 9.5, 3.5, 9.5, 26.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 1e-10, atol: 1e-10, "Matft.polyval(MfArray([2.0, -1.0, 0.5] as [Double])[Matft.reverse], x) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.polyval(MfArray([2, -1, 1] as [Int]), x), MfArray([16.0, 4.0, 29.0, 2.0, 46.0, 154.0, 11.0, 67.0, 46.0, 16.0, 46.0, 121.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 1e-05, atol: 1e-05, "Matft.polyval(MfArray([2, -1, 1] as [Int]), x) \(name)")
        }
        XCTAssertEqual(try Matft.linalg.matrix_rank(MfArray([0, 3, 0] as [Int])), 1)
        XCTAssertEqual(try Matft.linalg.matrix_rank(MfArray([0, 0] as [Float])), 0)
        XCTAssertEqual(try Matft.linalg.matrix_rank(MfArray([[1, 2], [2, 4]] as [[Int]]).T), 1)
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.cov(x), MfArray([4.916666666666666, -9.166666666666666, 1.0833333333333333, -9.166666666666666, 21.666666666666664, -1.5, 1.0833333333333333, -1.5, 4.25] as [Double], mftype: .Double, shape: [3, 3]), rtol: 1e-09, atol: 1e-10, "Matft.stats.cov(x) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.cov(x, rowvar: false), MfArray([1.3333333333333333, 4.666666666666666, -1.6666666666666665, 4.0, 4.666666666666666, 25.333333333333332, -16.333333333333336, 11.0, -1.6666666666666665, -16.333333333333336, 14.333333333333336, -1.5000000000000002, 4.0, 11.0, -1.5000000000000002, 13.0] as [Double], mftype: .Double, shape: [4, 4]), rtol: 1e-09, atol: 1e-10, "Matft.stats.cov(x, rowvar: false) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.cov(x, y: MfArray([[1, 0, 2, 5]] as [[Double]]), bias: true), MfArray([3.6875, -6.875, 0.8125, 0.5, -6.875, 16.25, -1.125, -1.25, 0.8125, -1.125, 3.1875, 3.25, 0.5, -1.25, 3.25, 3.5] as [Double], mftype: .Double, shape: [4, 4]), rtol: 1e-09, atol: 1e-10, "Matft.stats.cov(x, y: MfArray([[1, 0, 2, 5]] as [[Double]]), bias: true) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.cov(x, y: MfArray([[1, 0], [4, 4], [0, 1]] as [[Double]]), rowvar: false), MfArray([1.3333333333333333, 4.666666666666666, -1.6666666666666665, 4.0, 0.6666666666666667, 1.6666666666666667, 4.666666666666666, 25.333333333333332, -16.333333333333336, 11.0, 8.333333333333334, 10.333333333333332, -1.6666666666666665, -16.333333333333336, 14.333333333333336, -1.5000000000000002, -7.833333333333334, -7.333333333333334, 4.0, 11.0, -1.5000000000000002, 13.0, -1.1102230246251565e-16, 3.5, 0.6666666666666667, 8.333333333333334, -7.833333333333334, -1.1102230246251565e-16, 4.333333333333333, 3.833333333333333, 1.6666666666666667, 10.333333333333332, -7.333333333333334, 3.5, 3.833333333333333, 4.333333333333333] as [Double], mftype: .Double, shape: [6, 6]), rtol: 1e-09, atol: 1e-10, "Matft.stats.cov(x, y: MfArray([[1, 0], [4, 4], [0, 1]] as [[Double]]), rowvar: false) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.stats.corrcoef(x), MfArray([0.9999999999999998, -0.8881370860980515, 0.23699122097006606, -0.8881370860980515, 0.9999999999999998, -0.15631503171567182, 0.23699122097006606, -0.15631503171567182, 1.0] as [Double], mftype: .Double, shape: [3, 3]), rtol: 1e-09, atol: 1e-10, "Matft.stats.corrcoef(x) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.stats.corrcoef(x, rowvar: false), MfArray([1.0, 0.8029550909996033, -0.381246417760849, 0.9607689380645752, 0.8029550909996033, 1.0, -0.8571465015411377, 0.6061426401138306, -0.381246417760849, -0.8571465015411377, 1.0, -0.10988691449165344, 0.9607689380645752, 0.6061426401138306, -0.10988691449165344, 1.0] as [Double], mftype: .Float, shape: [4, 4]), rtol: 0.0001, atol: 1e-05, "Matft.stats.corrcoef(x, rowvar: false) \(name)")
        }
    }
    #endif

    #if !os(WASI) // LAPACK / interp1d are not available on WASI
    func test_interpolation() {
        for (name, x) in layoutVariants(NEWX){
            XCTAssertClose(Matft.interp(x, xp: MfArray([0.0, 1.0, 2.5, 4.0] as [Double]), fp: MfArray([1.0, -1.0, 3.0, 2.0] as [Double])), MfArray([1.0, 1.0, 0.0, 1.6666666269302368, 3.0, 2.066666603088379, 2.0] as [Double], mftype: .Float, shape: [7]), rtol: 1e-05, atol: 1e-05, "Matft.interp(x, xp: MfArray([0.0, 1.0, 2.5, 4.0] as [Double]), fp: MfArray([1.0, -1.0, 3.0, 2.0] as [Double])) \(name)")
        }
        for (name, x) in layoutVariants(NEWX){
            XCTAssertClose(Matft.interp(x, xp: MfArray([0.0, 1.0, 2.5, 4.0] as [Double])[Matft.reverse][Matft.reverse], fp: MfArray([1.0, -1.0, 3.0, 2.0] as [Double]), left: -9, right: 9), MfArray([-9.0, 1.0, 0.0, 1.6666666269302368, 3.0, 2.066666603088379, 9.0] as [Double], mftype: .Float, shape: [7]), rtol: 1e-05, atol: 1e-05, "Matft.interp(x, xp: MfArray([0.0, 1.0, 2.5, 4.0] as [Double])[Matft.reverse][Matft.reverse], fp: MfArray([1.0, -1.0, 3.0, 2.0] as [Double]), left: -9, right: 9) \(name)")
        }
        XCTAssertClose(Matft.interp1d.linear(x: MfArray([2.5, 0.0, 4.0, 1.0] as [Double]), y: MfArray([3.0, 1.0, 2.0, -1.0] as [Double]), assume_sorted: false).interpolate(MfArray([0.0, 0.5, 1.2, 2.5, 3.9, 4.0] as [Double])), MfArray([1.0, 0.0, -0.46666666865348816, 3.0, 2.066666603088379, 2.0] as [Double], mftype: .Float, shape: [6]), rtol: 1e-05, atol: 1e-05, "Matft.interp1d.linear(x: MfArray([2.5, 0.0, 4.0, 1.0] as [Double]), y: MfArray([3.0, 1.0, 2.0, -1.0] as [Double]), assume_sorted: false).interpolate(MfArray([0.0, 0.5, 1.2, 2.5, 3.9, 4.0] as [Double]))")
        XCTAssertClose(Matft.interp1d.nearest(x: MfArray([2.5, 0.0, 4.0, 1.0] as [Double]), y: MfArray([3.0, 1.0, 2.0, -1.0] as [Double]), assume_sorted: false).interpolate(MfArray([0.0, 0.5, 1.2, 2.5, 3.9, 4.0] as [Double])), MfArray([1.0, 1.0, -1.0, 3.0, 2.0, 2.0] as [Double], mftype: .Float, shape: [6]), rtol: 1e-05, atol: 1e-05, "Matft.interp1d.nearest(x: MfArray([2.5, 0.0, 4.0, 1.0] as [Double]), y: MfArray([3.0, 1.0, 2.0, -1.0] as [Double]), assume_sorted: false).interpolate(MfArray([0.0, 0.5, 1.2, 2.5, 3.9, 4.0] as [Double]))")
        XCTAssertClose(Matft.interp1d.previous(x: MfArray([2.5, 0.0, 4.0, 1.0] as [Double]), y: MfArray([3.0, 1.0, 2.0, -1.0] as [Double]), assume_sorted: false).interpolate(MfArray([0.0, 0.5, 1.2, 2.5, 3.9, 4.0] as [Double])), MfArray([1.0, 1.0, -1.0, 3.0, 3.0, 2.0] as [Double], mftype: .Float, shape: [6]), rtol: 1e-05, atol: 1e-05, "Matft.interp1d.previous(x: MfArray([2.5, 0.0, 4.0, 1.0] as [Double]), y: MfArray([3.0, 1.0, 2.0, -1.0] as [Double]), assume_sorted: false).interpolate(MfArray([0.0, 0.5, 1.2, 2.5, 3.9, 4.0] as [Double]))")
        XCTAssertClose(Matft.interp1d.next(x: MfArray([2.5, 0.0, 4.0, 1.0] as [Double]), y: MfArray([3.0, 1.0, 2.0, -1.0] as [Double]), assume_sorted: false).interpolate(MfArray([0.0, 0.5, 1.2, 2.5, 3.9, 4.0] as [Double])), MfArray([1.0, -1.0, 3.0, 3.0, 2.0, 2.0] as [Double], mftype: .Float, shape: [6]), rtol: 1e-05, atol: 1e-05, "Matft.interp1d.next(x: MfArray([2.5, 0.0, 4.0, 1.0] as [Double]), y: MfArray([3.0, 1.0, 2.0, -1.0] as [Double]), assume_sorted: false).interpolate(MfArray([0.0, 0.5, 1.2, 2.5, 3.9, 4.0] as [Double]))")
    }
    #endif

    func test_math() {
        for (name, x) in layoutVariants(AN){
            XCTAssertEqual(Matft.math.isnan(x), MfArray([false, true, false, false, false, false, true, false, true, false, false, false] as [Bool], shape: [3, 4]), "Matft.math.isnan(x) \(name)")
        }
        for (name, x) in layoutVariants(Z){
            XCTAssertEqual(Matft.math.isnan(x), MfArray([false, false, false, false, true, false] as [Bool], shape: [2, 3]), "Matft.math.isnan(x) \(name)")
        }
        for (name, x) in layoutVariants(Z){
            XCTAssertEqual(Matft.math.isinf(x), MfArray([false, true, false, true, false, false] as [Bool], shape: [2, 3]), "Matft.math.isinf(x) \(name)")
        }
        for (name, x) in layoutVariants(Z){
            XCTAssertEqual(Matft.math.isfinite(x), MfArray([true, false, true, false, false, true] as [Bool], shape: [2, 3]), "Matft.math.isfinite(x) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertEqual(Matft.math.isnan(x), MfArray([false, false, false, false, false, false, false, false, false, false, false, false] as [Bool], shape: [3, 4]), "Matft.math.isnan(x) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertEqual(Matft.math.isfinite(x), MfArray([true, true, true, true, true, true, true, true, true, true, true, true] as [Bool], shape: [3, 4]), "Matft.math.isfinite(x) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.math.power(bases: x, exponents: 3), MfArray([27.0, -1.0, 64.0, 1.0, 125.0, 729.0, -8.0, 216.0, 125.0, 27.0, 125.0, 512.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 1e-10, atol: 1e-10, "Matft.math.power(bases: x, exponents: 3) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.math.power(bases: Matft.math.abs(x), exponents: 0.5), MfArray([1.7320507764816284, 1.0, 2.0, 1.0, 2.2360680103302, 3.0, 1.4142135381698608, 2.4494898319244385, 2.2360680103302, 1.7320507764816284, 2.2360680103302, 2.8284270763397217] as [Double], mftype: .Float, shape: [3, 4]), rtol: 1e-05, atol: 1e-05, "Matft.math.power(bases: Matft.math.abs(x), exponents: 0.5) \(name)")
        }
        for (name, x) in layoutVariants(AI){
            XCTAssertClose(Matft.math.power(bases: x, exponents: 2), MfArray([9.0, 1.0, 16.0, 1.0, 25.0, 81.0, 4.0, 36.0, 25.0, 9.0, 25.0, 64.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 1e-05, atol: 1e-05, "Matft.math.power(bases: x, exponents: 2) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.math.exp2(x / 4), MfArray([1.681792830507429, 0.8408964152537145, 2.0, 1.189207115002721, 2.378414230005442, 4.756828460010884, 0.7071067811865476, 2.8284271247461903, 2.378414230005442, 1.681792830507429, 2.378414230005442, 4.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 1e-12, atol: 1e-12, "Matft.math.exp2(x / 4) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.math.exp2(x / 4), MfArray([1.6817928552627563, 0.8408964276313782, 2.0, 1.1892070770263672, 2.3784141540527344, 4.756828308105469, 0.7071067690849304, 2.8284270763397217, 2.3784141540527344, 1.6817928552627563, 2.3784141540527344, 4.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 1e-06, atol: 1e-06, "Matft.math.exp2(x / 4) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.math.expm1(x / 4), MfArray([1.1170000166126746, -0.22119921692859512, 1.7182818284590453, 0.2840254166877415, 2.4903429574618414, 8.487735836358526, -0.3934693402873666, 3.481689070338065, 2.4903429574618414, 1.1170000166126746, 2.4903429574618414, 6.38905609893065] as [Double], mftype: .Double, shape: [3, 4]), rtol: 1e-12, atol: 1e-12, "Matft.math.expm1(x / 4) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.math.expm1(x / 4), MfArray([1.1169999837875366, -0.22119921445846558, 1.718281865119934, 0.2840254306793213, 2.490342855453491, 8.487735748291016, -0.39346933364868164, 3.481688976287842, 2.490342855453491, 1.1169999837875366, 2.490342855453491, 6.389056205749512] as [Double], mftype: .Float, shape: [3, 4]), rtol: 1e-06, atol: 1e-06, "Matft.math.expm1(x / 4) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.math.log1p(Matft.math.abs(x) / 4), MfArray([0.5596157879354227, 0.22314355131420976, 0.6931471805599453, 0.22314355131420976, 0.8109302162163288, 1.1786549963416462, 0.4054651081081644, 0.9162907318741551, 0.8109302162163288, 0.5596157879354227, 0.8109302162163288, 1.0986122886681098] as [Double], mftype: .Double, shape: [3, 4]), rtol: 1e-12, atol: 1e-12, "Matft.math.log1p(Matft.math.abs(x) / 4) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.math.log1p(Matft.math.abs(x) / 4), MfArray([0.5596157908439636, 0.2231435477733612, 0.6931471824645996, 0.2231435477733612, 0.8109301924705505, 1.1786550283432007, 0.40546509623527527, 0.9162907600402832, 0.8109301924705505, 0.5596157908439636, 0.8109301924705505, 1.0986123085021973] as [Double], mftype: .Float, shape: [3, 4]), rtol: 1e-06, atol: 1e-06, "Matft.math.log1p(Matft.math.abs(x) / 4) \(name)")
        }
        for (name, x) in layoutVariants(A){
            XCTAssertClose(Matft.math.square(x / 4), MfArray([0.5625, 0.0625, 1.0, 0.0625, 1.5625, 5.0625, 0.25, 2.25, 1.5625, 0.5625, 1.5625, 4.0] as [Double], mftype: .Double, shape: [3, 4]), rtol: 1e-12, atol: 1e-12, "Matft.math.square(x / 4) \(name)")
        }
        for (name, x) in layoutVariants(AF){
            XCTAssertClose(Matft.math.square(x / 4), MfArray([0.5625, 0.0625, 1.0, 0.0625, 1.5625, 5.0625, 0.25, 2.25, 1.5625, 0.5625, 1.5625, 4.0] as [Double], mftype: .Float, shape: [3, 4]), rtol: 1e-06, atol: 1e-06, "Matft.math.square(x / 4) \(name)")
        }
        for (name, x) in layoutVariants(B){
            XCTAssertEqual(Matft.logical_not(x), MfArray([false, true, false, true, true, false] as [Bool], shape: [2, 3]), "Matft.logical_not(x) \(name)")
        }
    }
}
