import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const repoUrl = 'https://github.com/jjjkkkjjj/Matft';

// The API reference is generated by Swift-DocC into static/api (see docs.yml).
// `pathname://` tells Docusaurus that it is not a route of this site.
const apiReference = 'pathname:///api/documentation/matft/';

const config: Config = {
  title: 'Matft',
  tagline: 'Numpy-like multi-dimensional array library in Swift',
  favicon: 'img/logo.svg',

  future: {
    v4: true,
  },

  url: 'https://jjjkkkjjj.github.io',
  baseUrl: '/Matft/',
  trailingSlash: false,

  organizationName: 'jjjkkkjjj',
  projectName: 'Matft',

  onBrokenLinks: 'throw',
  markdown: {
    // .md is CommonMark (tables with `<`, `{` and HTML comments such as the BENCHMARK markers), .mdx is MDX
    format: 'detect',
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          editUrl: `${repoUrl}/tree/main/website/`,
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themes: [
    [
      '@easyops-cn/docusaurus-search-local',
      {
        hashed: true,
        indexBlog: false,
        docsRouteBasePath: '/docs',
        highlightSearchTermsOnTargetPage: true,
      },
    ],
  ],

  themeConfig: {
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'Matft',
      logo: {
        alt: 'Matft Logo',
        src: 'img/logo.svg',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'docsSidebar',
          position: 'left',
          label: 'Docs',
        },
        {
          type: 'docSidebar',
          sidebarId: 'mappingSidebar',
          position: 'left',
          label: 'NumPy Mapping',
        },
        {
          href: apiReference,
          label: 'API Reference',
          position: 'left',
        },
        {
          href: repoUrl,
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            {label: 'Introduction', to: '/docs/intro'},
            {label: 'Installation', to: '/docs/getting-started/installation'},
            {label: 'NumPy Mapping', to: '/docs/numpy-mapping'},
            {label: 'API Reference', href: apiReference},
          ],
        },
        {
          title: 'Community',
          items: [
            {label: 'Issues', href: `${repoUrl}/issues`},
            {label: 'Releases', href: `${repoUrl}/releases`},
          ],
        },
        {
          title: 'More',
          items: [
            {label: 'GitHub', href: repoUrl},
            {label: 'Swift Package Index', href: 'https://swiftpackageindex.com/jjjkkkjjj/Matft'},
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} jjjkkkjjj. BSD-3-Clause License. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['swift', 'bash', 'python'],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
