name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    # Use the Swift toolchain bundled with Xcode so that it always matches the macOS SDK
    - name: Show Swift version
      run: swift --version
    - name: Build and Test
      run: ./scripts/build-and-test-ios.sh
